/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, March 1, 2023 at 11:00:14 PM Israel Standard Time
* Operating System: Version 11.2.3 (Build 20D91)
* Image Source: /usr/libexec/sharingd
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol _NSUserNotificationCenterDelegatePrivate <NSUserNotificationCenterDelegate>
@optional
-(char)userNotificationCenter:(id)arg1 shouldActivateForNotification:(id)arg2;
-(void)userNotificationCenter:(id)arg1 didDismissAlert:(id)arg2;
-(void)userNotificationCenter:(id)arg1 didSnoozeAlert:(id)arg2;
-(void)userNotificationCenter:(id)arg1 didRegisterForRemoteNotificationsWithDeviceToken:(id)arg2;
-(void)userNotificationCenter:(id)arg1 didFailToRegisterForRemoteNotificationsWithError:(id)arg2;
-(void)userNotificationCenter:(id)arg1 didRemoveDeliveredNotifications:(id)arg2;
-(void)userNotificationCenter:(id)arg1 didExpireNotifications:(id)arg2;
-(void)userNotificationCenter:(id)arg1 responseChanged:(unsigned long long)arg2 forNotification:(id)arg3;
-(void)userNotificationCenter:(id)arg1 summaryShown:(char)arg2;
-(void)userNotificationCenter:(id)arg1 notificationsDisabled:(char)arg2;
-(void)userNotificationCenter:(id)arg1 notificationPreferencesChanged:(unsigned long long)arg2;
-(void)userNotificationCenterConnectionInvalidated:(id)arg1;

@end

