/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, March 1, 2023 at 11:00:16 PM Israel Standard Time
* Operating System: Version 11.2.3 (Build 20D91)
* Image Source: /usr/libexec/sharingd
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <sharingd/sharingd-Structs.h>
#import <ProtocolBuffer/PBCodable.h>
#import <libobjc.A.dylib/NSCopying.h>

@interface AWDSharingCMS2ServerTaskResponse : PBCodable <NSCopying> {

	unsigned long long _timestamp;
	int _errorCode;
	unsigned _httpStatusCode;
	unsigned _idmsEnv;
	unsigned _type;
	SCD_Struct_SD10 _has;

}

@property (assign,nonatomic) char hasTimestamp; 
@property (assign,nonatomic) unsigned long long timestamp;              //@synthesize timestamp=_timestamp - In the implementation block
@property (assign,nonatomic) char hasHttpStatusCode; 
@property (assign,nonatomic) unsigned httpStatusCode;                   //@synthesize httpStatusCode=_httpStatusCode - In the implementation block
@property (assign,nonatomic) char hasErrorCode; 
@property (assign,nonatomic) int errorCode;                             //@synthesize errorCode=_errorCode - In the implementation block
@property (assign,nonatomic) char hasType; 
@property (assign,nonatomic) unsigned type;                             //@synthesize type=_type - In the implementation block
@property (assign,nonatomic) char hasIdmsEnv; 
@property (assign,nonatomic) unsigned idmsEnv;                          //@synthesize idmsEnv=_idmsEnv - In the implementation block
-(id)copyWithZone:(NSZone*)arg1 ;
-(char)isEqual:(id)arg1 ;
-(unsigned long long)hash;
-(id)description;
-(void)setType:(unsigned)arg1 ;
-(unsigned)type;
-(id)dictionaryRepresentation;
-(unsigned long long)timestamp;
-(void)mergeFrom:(id)arg1 ;
-(char)readFrom:(id)arg1 ;
-(void)writeTo:(id)arg1 ;
-(void)copyTo:(id)arg1 ;
-(void)setTimestamp:(unsigned long long)arg1 ;
-(char)hasTimestamp;
-(void)setHasType:(char)arg1 ;
-(char)hasType;
-(int)errorCode;
-(void)setHasTimestamp:(char)arg1 ;
-(void)setErrorCode:(int)arg1 ;
-(void)setHasErrorCode:(char)arg1 ;
-(char)hasErrorCode;
-(void)setHttpStatusCode:(unsigned)arg1 ;
-(unsigned)httpStatusCode;
-(void)setHasHttpStatusCode:(char)arg1 ;
-(char)hasHttpStatusCode;
-(void)setIdmsEnv:(unsigned)arg1 ;
-(void)setHasIdmsEnv:(char)arg1 ;
-(char)hasIdmsEnv;
-(unsigned)idmsEnv;
@end

