/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, March 1, 2023 at 11:00:07 PM Israel Standard Time
* Operating System: Version 11.2.3 (Build 20D91)
* Image Source: /usr/libexec/sharingd
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <sharingd/sharingd-Structs.h>
#import <ProtocolBuffer/PBCodable.h>
#import <libobjc.A.dylib/NSCopying.h>

@class NSString;

@interface AWDSharingProximityStatusTriggered : PBCodable <NSCopying> {

	unsigned long long _timestamp;
	unsigned _audioSourceCount;
	unsigned _audioState;
	unsigned _caseBatteryLevel;
	unsigned _caseBatteryPercent;
	unsigned _deviceRole;
	unsigned _deviceSide;
	NSString* _model;
	unsigned _myBatteryLevel;
	unsigned _myBatteryPercent;
	unsigned _otherBatteryLevel;
	unsigned _otherBatteryPercent;
	unsigned _primaryLocation;
	int _rssi;
	unsigned _secondaryLocation;
	NSString* _sessionUUID;
	int _smoothedRSSI;
	char _caseBatteryCharging;
	char _myBatteryCharging;
	char _otherBatteryCharging;
	char _otherDeviceInCase;
	char _outOfBoxMode;
	char _paired;
	SCD_Struct_AW29 _has;

}

@property (assign,nonatomic) char hasTimestamp; 
@property (assign,nonatomic) unsigned long long timestamp;              //@synthesize timestamp=_timestamp - In the implementation block
@property (nonatomic,readonly) char hasSessionUUID; 
@property (nonatomic,retain) NSString * sessionUUID;                    //@synthesize sessionUUID=_sessionUUID - In the implementation block
@property (assign,nonatomic) char hasRssi; 
@property (assign,nonatomic) int rssi;                                  //@synthesize rssi=_rssi - In the implementation block
@property (assign,nonatomic) char hasSmoothedRSSI; 
@property (assign,nonatomic) int smoothedRSSI;                          //@synthesize smoothedRSSI=_smoothedRSSI - In the implementation block
@property (nonatomic,readonly) char hasModel; 
@property (nonatomic,retain) NSString * model;                          //@synthesize model=_model - In the implementation block
@property (assign,nonatomic) char hasPrimaryLocation; 
@property (assign,nonatomic) unsigned primaryLocation;                  //@synthesize primaryLocation=_primaryLocation - In the implementation block
@property (assign,nonatomic) char hasSecondaryLocation; 
@property (assign,nonatomic) unsigned secondaryLocation;                //@synthesize secondaryLocation=_secondaryLocation - In the implementation block
@property (assign,nonatomic) char hasDeviceSide; 
@property (assign,nonatomic) unsigned deviceSide;                       //@synthesize deviceSide=_deviceSide - In the implementation block
@property (assign,nonatomic) char hasDeviceRole; 
@property (assign,nonatomic) unsigned deviceRole;                       //@synthesize deviceRole=_deviceRole - In the implementation block
@property (assign,nonatomic) char hasOutOfBoxMode; 
@property (assign,nonatomic) char outOfBoxMode;                         //@synthesize outOfBoxMode=_outOfBoxMode - In the implementation block
@property (assign,nonatomic) char hasMyBatteryPercent; 
@property (assign,nonatomic) unsigned myBatteryPercent;                 //@synthesize myBatteryPercent=_myBatteryPercent - In the implementation block
@property (assign,nonatomic) char hasOtherBatteryPercent; 
@property (assign,nonatomic) unsigned otherBatteryPercent;              //@synthesize otherBatteryPercent=_otherBatteryPercent - In the implementation block
@property (assign,nonatomic) char hasCaseBatteryPercent; 
@property (assign,nonatomic) unsigned caseBatteryPercent;               //@synthesize caseBatteryPercent=_caseBatteryPercent - In the implementation block
@property (assign,nonatomic) char hasAudioState; 
@property (assign,nonatomic) unsigned audioState;                       //@synthesize audioState=_audioState - In the implementation block
@property (assign,nonatomic) char hasAudioSourceCount; 
@property (assign,nonatomic) unsigned audioSourceCount;                 //@synthesize audioSourceCount=_audioSourceCount - In the implementation block
@property (assign,nonatomic) char hasOtherDeviceInCase; 
@property (assign,nonatomic) char otherDeviceInCase;                    //@synthesize otherDeviceInCase=_otherDeviceInCase - In the implementation block
@property (assign,nonatomic) char hasMyBatteryLevel; 
@property (assign,nonatomic) unsigned myBatteryLevel;                   //@synthesize myBatteryLevel=_myBatteryLevel - In the implementation block
@property (assign,nonatomic) char hasMyBatteryCharging; 
@property (assign,nonatomic) char myBatteryCharging;                    //@synthesize myBatteryCharging=_myBatteryCharging - In the implementation block
@property (assign,nonatomic) char hasOtherBatteryLevel; 
@property (assign,nonatomic) unsigned otherBatteryLevel;                //@synthesize otherBatteryLevel=_otherBatteryLevel - In the implementation block
@property (assign,nonatomic) char hasOtherBatteryCharging; 
@property (assign,nonatomic) char otherBatteryCharging;                 //@synthesize otherBatteryCharging=_otherBatteryCharging - In the implementation block
@property (assign,nonatomic) char hasCaseBatteryLevel; 
@property (assign,nonatomic) unsigned caseBatteryLevel;                 //@synthesize caseBatteryLevel=_caseBatteryLevel - In the implementation block
@property (assign,nonatomic) char hasCaseBatteryCharging; 
@property (assign,nonatomic) char caseBatteryCharging;                  //@synthesize caseBatteryCharging=_caseBatteryCharging - In the implementation block
@property (assign,nonatomic) char hasPaired; 
@property (assign,nonatomic) char paired;                               //@synthesize paired=_paired - In the implementation block
-(id)copyWithZone:(NSZone*)arg1 ;
-(char)isEqual:(id)arg1 ;
-(unsigned long long)hash;
-(id)description;
-(id)dictionaryRepresentation;
-(unsigned long long)timestamp;
-(void)mergeFrom:(id)arg1 ;
-(char)readFrom:(id)arg1 ;
-(void)writeTo:(id)arg1 ;
-(void)copyTo:(id)arg1 ;
-(NSString *)model;
-(void)setModel:(NSString *)arg1 ;
-(void)setTimestamp:(unsigned long long)arg1 ;
-(char)hasTimestamp;
-(char)paired;
-(void)setPaired:(char)arg1 ;
-(int)rssi;
-(void)setRssi:(int)arg1 ;
-(void)setHasTimestamp:(char)arg1 ;
-(void)setHasRssi:(char)arg1 ;
-(char)hasRssi;
-(char)hasModel;
-(unsigned)caseBatteryLevel;
-(int)smoothedRSSI;
-(void)setSessionUUID:(NSString *)arg1 ;
-(char)hasSessionUUID;
-(NSString *)sessionUUID;
-(unsigned)deviceRole;
-(void)setDeviceRole:(unsigned)arg1 ;
-(void)setSmoothedRSSI:(int)arg1 ;
-(void)setHasSmoothedRSSI:(char)arg1 ;
-(char)hasSmoothedRSSI;
-(void)setPrimaryLocation:(unsigned)arg1 ;
-(void)setHasPrimaryLocation:(char)arg1 ;
-(char)hasPrimaryLocation;
-(void)setSecondaryLocation:(unsigned)arg1 ;
-(void)setHasSecondaryLocation:(char)arg1 ;
-(char)hasSecondaryLocation;
-(void)setDeviceSide:(unsigned)arg1 ;
-(void)setHasDeviceSide:(char)arg1 ;
-(char)hasDeviceSide;
-(void)setHasDeviceRole:(char)arg1 ;
-(char)hasDeviceRole;
-(void)setOutOfBoxMode:(char)arg1 ;
-(void)setHasOutOfBoxMode:(char)arg1 ;
-(char)hasOutOfBoxMode;
-(unsigned)primaryLocation;
-(unsigned)secondaryLocation;
-(unsigned)deviceSide;
-(char)outOfBoxMode;
-(void)setMyBatteryPercent:(unsigned)arg1 ;
-(void)setHasMyBatteryPercent:(char)arg1 ;
-(char)hasMyBatteryPercent;
-(void)setOtherBatteryPercent:(unsigned)arg1 ;
-(void)setHasOtherBatteryPercent:(char)arg1 ;
-(char)hasOtherBatteryPercent;
-(void)setCaseBatteryPercent:(unsigned)arg1 ;
-(void)setHasCaseBatteryPercent:(char)arg1 ;
-(char)hasCaseBatteryPercent;
-(void)setAudioState:(unsigned)arg1 ;
-(void)setHasAudioState:(char)arg1 ;
-(char)hasAudioState;
-(void)setAudioSourceCount:(unsigned)arg1 ;
-(void)setHasAudioSourceCount:(char)arg1 ;
-(char)hasAudioSourceCount;
-(void)setOtherDeviceInCase:(char)arg1 ;
-(void)setHasOtherDeviceInCase:(char)arg1 ;
-(char)hasOtherDeviceInCase;
-(void)setMyBatteryLevel:(unsigned)arg1 ;
-(void)setHasMyBatteryLevel:(char)arg1 ;
-(char)hasMyBatteryLevel;
-(void)setMyBatteryCharging:(char)arg1 ;
-(void)setHasMyBatteryCharging:(char)arg1 ;
-(char)hasMyBatteryCharging;
-(void)setOtherBatteryLevel:(unsigned)arg1 ;
-(void)setHasOtherBatteryLevel:(char)arg1 ;
-(char)hasOtherBatteryLevel;
-(void)setOtherBatteryCharging:(char)arg1 ;
-(void)setHasOtherBatteryCharging:(char)arg1 ;
-(char)hasOtherBatteryCharging;
-(void)setCaseBatteryLevel:(unsigned)arg1 ;
-(void)setHasCaseBatteryLevel:(char)arg1 ;
-(char)hasCaseBatteryLevel;
-(void)setCaseBatteryCharging:(char)arg1 ;
-(void)setHasCaseBatteryCharging:(char)arg1 ;
-(char)hasCaseBatteryCharging;
-(void)setHasPaired:(char)arg1 ;
-(char)hasPaired;
-(unsigned)myBatteryPercent;
-(unsigned)otherBatteryPercent;
-(unsigned)caseBatteryPercent;
-(unsigned)audioState;
-(unsigned)audioSourceCount;
-(char)otherDeviceInCase;
-(unsigned)myBatteryLevel;
-(char)myBatteryCharging;
-(unsigned)otherBatteryLevel;
-(char)otherBatteryCharging;
-(char)caseBatteryCharging;
@end

