/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, March 1, 2023 at 11:00:07 PM Israel Standard Time
* Operating System: Version 11.2.3 (Build 20D91)
* Image Source: /usr/libexec/sharingd
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <sharingd/sharingd-Structs.h>
#import <ProtocolBuffer/PBCodable.h>
#import <libobjc.A.dylib/NSCopying.h>

@class NSString;

@interface AWDSharingAirDropPeerDiscoveredInfo : PBCodable <NSCopying> {

	unsigned long long _timestamp;
	unsigned _awdlVersion;
	unsigned _bluetoothDiscovery;
	unsigned _bonjourDiscovery;
	unsigned _bonjourResolveComplete;
	unsigned _bonjourTXTRecordDiscovery;
	NSString* _browserID;
	int _errorCode;
	NSString* _errorDomain;
	unsigned _identityQueryComplete;
	NSString* _modelCode;
	NSString* _modelName;
	unsigned _platform;
	int _rssi;
	NSString* _sessionID;
	unsigned _tcpConnectionComplete;
	unsigned _tlsHandshakeComplete;
	unsigned _totalDiscovery;
	char _verifiableIdentity;
	SCD_Struct_AW28 _has;

}

@property (assign,nonatomic) char hasTimestamp; 
@property (assign,nonatomic) unsigned long long timestamp;                    //@synthesize timestamp=_timestamp - In the implementation block
@property (nonatomic,readonly) char hasSessionID; 
@property (nonatomic,retain) NSString * sessionID;                            //@synthesize sessionID=_sessionID - In the implementation block
@property (nonatomic,readonly) char hasModelName; 
@property (nonatomic,retain) NSString * modelName;                            //@synthesize modelName=_modelName - In the implementation block
@property (nonatomic,readonly) char hasModelCode; 
@property (nonatomic,retain) NSString * modelCode;                            //@synthesize modelCode=_modelCode - In the implementation block
@property (assign,nonatomic) char hasBluetoothDiscovery; 
@property (assign,nonatomic) unsigned bluetoothDiscovery;                     //@synthesize bluetoothDiscovery=_bluetoothDiscovery - In the implementation block
@property (assign,nonatomic) char hasBonjourDiscovery; 
@property (assign,nonatomic) unsigned bonjourDiscovery;                       //@synthesize bonjourDiscovery=_bonjourDiscovery - In the implementation block
@property (assign,nonatomic) char hasBonjourTXTRecordDiscovery; 
@property (assign,nonatomic) unsigned bonjourTXTRecordDiscovery;              //@synthesize bonjourTXTRecordDiscovery=_bonjourTXTRecordDiscovery - In the implementation block
@property (assign,nonatomic) char hasBonjourResolveComplete; 
@property (assign,nonatomic) unsigned bonjourResolveComplete;                 //@synthesize bonjourResolveComplete=_bonjourResolveComplete - In the implementation block
@property (assign,nonatomic) char hasTcpConnectionComplete; 
@property (assign,nonatomic) unsigned tcpConnectionComplete;                  //@synthesize tcpConnectionComplete=_tcpConnectionComplete - In the implementation block
@property (assign,nonatomic) char hasTlsHandshakeComplete; 
@property (assign,nonatomic) unsigned tlsHandshakeComplete;                   //@synthesize tlsHandshakeComplete=_tlsHandshakeComplete - In the implementation block
@property (assign,nonatomic) char hasIdentityQueryComplete; 
@property (assign,nonatomic) unsigned identityQueryComplete;                  //@synthesize identityQueryComplete=_identityQueryComplete - In the implementation block
@property (assign,nonatomic) char hasTotalDiscovery; 
@property (assign,nonatomic) unsigned totalDiscovery;                         //@synthesize totalDiscovery=_totalDiscovery - In the implementation block
@property (assign,nonatomic) char hasVerifiableIdentity; 
@property (assign,nonatomic) char verifiableIdentity;                         //@synthesize verifiableIdentity=_verifiableIdentity - In the implementation block
@property (assign,nonatomic) char hasRssi; 
@property (assign,nonatomic) int rssi;                                        //@synthesize rssi=_rssi - In the implementation block
@property (nonatomic,readonly) char hasErrorDomain; 
@property (nonatomic,retain) NSString * errorDomain;                          //@synthesize errorDomain=_errorDomain - In the implementation block
@property (assign,nonatomic) char hasErrorCode; 
@property (assign,nonatomic) int errorCode;                                   //@synthesize errorCode=_errorCode - In the implementation block
@property (assign,nonatomic) char hasAwdlVersion; 
@property (assign,nonatomic) unsigned awdlVersion;                            //@synthesize awdlVersion=_awdlVersion - In the implementation block
@property (assign,nonatomic) char hasPlatform; 
@property (assign,nonatomic) unsigned platform;                               //@synthesize platform=_platform - In the implementation block
@property (nonatomic,readonly) char hasBrowserID; 
@property (nonatomic,retain) NSString * browserID;                            //@synthesize browserID=_browserID - In the implementation block
-(id)copyWithZone:(NSZone*)arg1 ;
-(char)isEqual:(id)arg1 ;
-(unsigned long long)hash;
-(id)description;
-(unsigned)platform;
-(id)dictionaryRepresentation;
-(unsigned long long)timestamp;
-(void)setPlatform:(unsigned)arg1 ;
-(void)mergeFrom:(id)arg1 ;
-(char)readFrom:(id)arg1 ;
-(void)writeTo:(id)arg1 ;
-(void)copyTo:(id)arg1 ;
-(void)setTimestamp:(unsigned long long)arg1 ;
-(NSString *)sessionID;
-(void)setSessionID:(NSString *)arg1 ;
-(char)hasTimestamp;
-(int)errorCode;
-(NSString *)modelName;
-(void)setModelName:(NSString *)arg1 ;
-(int)rssi;
-(void)setRssi:(int)arg1 ;
-(char)hasSessionID;
-(void)setHasTimestamp:(char)arg1 ;
-(void)setHasRssi:(char)arg1 ;
-(char)hasRssi;
-(void)setErrorDomain:(NSString *)arg1 ;
-(void)setErrorCode:(int)arg1 ;
-(NSString *)errorDomain;
-(char)hasErrorDomain;
-(void)setHasErrorCode:(char)arg1 ;
-(char)hasErrorCode;
-(void)setAwdlVersion:(unsigned)arg1 ;
-(void)setHasAwdlVersion:(char)arg1 ;
-(char)hasAwdlVersion;
-(unsigned)awdlVersion;
-(char)hasPlatform;
-(void)setHasPlatform:(char)arg1 ;
-(char)hasModelName;
-(void)setBonjourDiscovery:(unsigned)arg1 ;
-(void)setBonjourTXTRecordDiscovery:(unsigned)arg1 ;
-(unsigned)bonjourDiscovery;
-(char)verifiableIdentity;
-(unsigned)bluetoothDiscovery;
-(unsigned)bonjourTXTRecordDiscovery;
-(unsigned)bonjourResolveComplete;
-(unsigned)tcpConnectionComplete;
-(unsigned)tlsHandshakeComplete;
-(unsigned)identityQueryComplete;
-(void)setVerifiableIdentity:(char)arg1 ;
-(NSString *)modelCode;
-(void)setModelCode:(NSString *)arg1 ;
-(void)setBrowserID:(NSString *)arg1 ;
-(char)hasModelCode;
-(void)setBluetoothDiscovery:(unsigned)arg1 ;
-(void)setHasBluetoothDiscovery:(char)arg1 ;
-(char)hasBluetoothDiscovery;
-(void)setHasBonjourDiscovery:(char)arg1 ;
-(char)hasBonjourDiscovery;
-(void)setHasBonjourTXTRecordDiscovery:(char)arg1 ;
-(char)hasBonjourTXTRecordDiscovery;
-(void)setBonjourResolveComplete:(unsigned)arg1 ;
-(void)setHasBonjourResolveComplete:(char)arg1 ;
-(char)hasBonjourResolveComplete;
-(void)setTcpConnectionComplete:(unsigned)arg1 ;
-(void)setHasTcpConnectionComplete:(char)arg1 ;
-(char)hasTcpConnectionComplete;
-(void)setTlsHandshakeComplete:(unsigned)arg1 ;
-(void)setHasTlsHandshakeComplete:(char)arg1 ;
-(char)hasTlsHandshakeComplete;
-(void)setIdentityQueryComplete:(unsigned)arg1 ;
-(void)setHasIdentityQueryComplete:(char)arg1 ;
-(char)hasIdentityQueryComplete;
-(void)setTotalDiscovery:(unsigned)arg1 ;
-(void)setHasTotalDiscovery:(char)arg1 ;
-(char)hasTotalDiscovery;
-(void)setHasVerifiableIdentity:(char)arg1 ;
-(char)hasVerifiableIdentity;
-(char)hasBrowserID;
-(unsigned)totalDiscovery;
-(NSString *)browserID;
@end

