/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, March 1, 2023 at 11:00:06 PM Israel Standard Time
* Operating System: Version 11.2.3 (Build 20D91)
* Image Source: /usr/libexec/sharingd
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <sharingd/sharingd-Structs.h>
#import <ProtocolBuffer/PBCodable.h>
#import <libobjc.A.dylib/NSCopying.h>

@class NSString;

@interface AWDSharingProximityPairingTriggered : PBCodable <NSCopying> {

	unsigned long long _timestamp;
	int _deviceRole;
	int _deviceSide;
	NSString* _model;
	int _primaryLocation;
	int _rssi;
	int _secondaryLocation;
	NSString* _sessionUUID;
	int _smoothedRSSI;
	char _outOfBoxMode;
	SCD_Struct_AW19 _has;

}

@property (assign,nonatomic) char hasTimestamp; 
@property (assign,nonatomic) unsigned long long timestamp;              //@synthesize timestamp=_timestamp - In the implementation block
@property (nonatomic,readonly) char hasSessionUUID; 
@property (nonatomic,retain) NSString * sessionUUID;                    //@synthesize sessionUUID=_sessionUUID - In the implementation block
@property (assign,nonatomic) char hasRssi; 
@property (assign,nonatomic) int rssi;                                  //@synthesize rssi=_rssi - In the implementation block
@property (assign,nonatomic) char hasSmoothedRSSI; 
@property (assign,nonatomic) int smoothedRSSI;                          //@synthesize smoothedRSSI=_smoothedRSSI - In the implementation block
@property (nonatomic,readonly) char hasModel; 
@property (nonatomic,retain) NSString * model;                          //@synthesize model=_model - In the implementation block
@property (assign,nonatomic) char hasPrimaryLocation; 
@property (assign,nonatomic) int primaryLocation;                       //@synthesize primaryLocation=_primaryLocation - In the implementation block
@property (assign,nonatomic) char hasSecondaryLocation; 
@property (assign,nonatomic) int secondaryLocation;                     //@synthesize secondaryLocation=_secondaryLocation - In the implementation block
@property (assign,nonatomic) char hasDeviceSide; 
@property (assign,nonatomic) int deviceSide;                            //@synthesize deviceSide=_deviceSide - In the implementation block
@property (assign,nonatomic) char hasDeviceRole; 
@property (assign,nonatomic) int deviceRole;                            //@synthesize deviceRole=_deviceRole - In the implementation block
@property (assign,nonatomic) char hasOutOfBoxMode; 
@property (assign,nonatomic) char outOfBoxMode;                         //@synthesize outOfBoxMode=_outOfBoxMode - In the implementation block
-(id)copyWithZone:(NSZone*)arg1 ;
-(char)isEqual:(id)arg1 ;
-(unsigned long long)hash;
-(id)description;
-(id)dictionaryRepresentation;
-(unsigned long long)timestamp;
-(void)mergeFrom:(id)arg1 ;
-(char)readFrom:(id)arg1 ;
-(void)writeTo:(id)arg1 ;
-(void)copyTo:(id)arg1 ;
-(NSString *)model;
-(void)setModel:(NSString *)arg1 ;
-(void)setTimestamp:(unsigned long long)arg1 ;
-(char)hasTimestamp;
-(int)rssi;
-(void)setRssi:(int)arg1 ;
-(void)setHasTimestamp:(char)arg1 ;
-(void)setHasRssi:(char)arg1 ;
-(char)hasRssi;
-(char)hasModel;
-(int)smoothedRSSI;
-(void)setSessionUUID:(NSString *)arg1 ;
-(char)hasSessionUUID;
-(NSString *)sessionUUID;
-(int)deviceRole;
-(void)setDeviceRole:(int)arg1 ;
-(void)setSmoothedRSSI:(int)arg1 ;
-(void)setHasSmoothedRSSI:(char)arg1 ;
-(char)hasSmoothedRSSI;
-(void)setPrimaryLocation:(int)arg1 ;
-(void)setHasPrimaryLocation:(char)arg1 ;
-(char)hasPrimaryLocation;
-(void)setSecondaryLocation:(int)arg1 ;
-(void)setHasSecondaryLocation:(char)arg1 ;
-(char)hasSecondaryLocation;
-(void)setDeviceSide:(int)arg1 ;
-(void)setHasDeviceSide:(char)arg1 ;
-(char)hasDeviceSide;
-(void)setHasDeviceRole:(char)arg1 ;
-(char)hasDeviceRole;
-(void)setOutOfBoxMode:(char)arg1 ;
-(void)setHasOutOfBoxMode:(char)arg1 ;
-(char)hasOutOfBoxMode;
-(int)primaryLocation;
-(int)secondaryLocation;
-(int)deviceSide;
-(char)outOfBoxMode;
@end

