/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, March 1, 2023 at 11:00:14 PM Israel Standard Time
* Operating System: Version 11.2.3 (Build 20D91)
* Image Source: /usr/libexec/sharingd
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <sharingd/sharingd-Structs.h>
#import <ProtocolBuffer/PBCodable.h>
#import <libobjc.A.dylib/NSCopying.h>

@class NSString;

@interface AWDSharingAutoUnlockAttempt : PBCodable <NSCopying> {

	long long _timeIntervalSinceLastDarkWake;
	unsigned long long _timestamp;
	unsigned _attemptType;
	unsigned _awdlBringUpTime;
	unsigned _awdlPeerDiscoveryTime;
	unsigned _awdlRangingTime;
	unsigned _bleAWDLInfoExchangeTime;
	unsigned _bleAuthTokenExchangeTime;
	unsigned _bleConfirmationTime;
	unsigned _bleKeyConnectionTime;
	unsigned _bleKeyDiscoveryTime;
	unsigned _bleKeyRequestExchangeTime;
	unsigned _bleProxyConnectionTime;
	unsigned _bleProxyDiscoveryTime;
	unsigned _bluetoothConnectedDevices;
	int _cancelReason;
	unsigned _cancelTime;
	unsigned _clamshellWaitTime;
	unsigned _displayWaitTime;
	unsigned _distance;
	unsigned _errorCode;
	NSString* _errorDomain;
	unsigned _errorType;
	unsigned _flags;
	int _keyBluetoothRSSI;
	NSString* _keyDeviceModel;
	int _lastSleepType;
	int _proxyBluetoothRSSI;
	NSString* _proxyDeviceModel;
	int _timeIntervalSinceLastWake;
	unsigned _totalUnlockTime;
	NSString* _watchBuildVersion;
	NSString* _watchOSVersion;
	char _clamshellClosed;
	char _externalDisplay;
	char _unlockSucceeded;
	char _usingProxy;
	char _usingTool;
	char _withinRange;
	SCD_Struct_AW51 _has;

}

@property (assign,nonatomic) char hasTimestamp; 
@property (assign,nonatomic) unsigned long long timestamp;                         //@synthesize timestamp=_timestamp - In the implementation block
@property (nonatomic,readonly) char hasKeyDeviceModel; 
@property (nonatomic,retain) NSString * keyDeviceModel;                            //@synthesize keyDeviceModel=_keyDeviceModel - In the implementation block
@property (nonatomic,readonly) char hasProxyDeviceModel; 
@property (nonatomic,retain) NSString * proxyDeviceModel;                          //@synthesize proxyDeviceModel=_proxyDeviceModel - In the implementation block
@property (assign,nonatomic) char hasUsingProxy; 
@property (assign,nonatomic) char usingProxy;                                      //@synthesize usingProxy=_usingProxy - In the implementation block
@property (assign,nonatomic) char hasBleKeyDiscoveryTime; 
@property (assign,nonatomic) unsigned bleKeyDiscoveryTime;                         //@synthesize bleKeyDiscoveryTime=_bleKeyDiscoveryTime - In the implementation block
@property (assign,nonatomic) char hasBleProxyDiscoveryTime; 
@property (assign,nonatomic) unsigned bleProxyDiscoveryTime;                       //@synthesize bleProxyDiscoveryTime=_bleProxyDiscoveryTime - In the implementation block
@property (assign,nonatomic) char hasBleAWDLInfoExchangeTime; 
@property (assign,nonatomic) unsigned bleAWDLInfoExchangeTime;                     //@synthesize bleAWDLInfoExchangeTime=_bleAWDLInfoExchangeTime - In the implementation block
@property (assign,nonatomic) char hasBleKeyRequestExchangeTime; 
@property (assign,nonatomic) unsigned bleKeyRequestExchangeTime;                   //@synthesize bleKeyRequestExchangeTime=_bleKeyRequestExchangeTime - In the implementation block
@property (assign,nonatomic) char hasBleAuthTokenExchangeTime; 
@property (assign,nonatomic) unsigned bleAuthTokenExchangeTime;                    //@synthesize bleAuthTokenExchangeTime=_bleAuthTokenExchangeTime - In the implementation block
@property (assign,nonatomic) char hasAwdlBringUpTime; 
@property (assign,nonatomic) unsigned awdlBringUpTime;                             //@synthesize awdlBringUpTime=_awdlBringUpTime - In the implementation block
@property (assign,nonatomic) char hasAwdlPeerDiscoveryTime; 
@property (assign,nonatomic) unsigned awdlPeerDiscoveryTime;                       //@synthesize awdlPeerDiscoveryTime=_awdlPeerDiscoveryTime - In the implementation block
@property (assign,nonatomic) char hasAwdlRangingTime; 
@property (assign,nonatomic) unsigned awdlRangingTime;                             //@synthesize awdlRangingTime=_awdlRangingTime - In the implementation block
@property (assign,nonatomic) char hasBleConfirmationTime; 
@property (assign,nonatomic) unsigned bleConfirmationTime;                         //@synthesize bleConfirmationTime=_bleConfirmationTime - In the implementation block
@property (assign,nonatomic) char hasTotalUnlockTime; 
@property (assign,nonatomic) unsigned totalUnlockTime;                             //@synthesize totalUnlockTime=_totalUnlockTime - In the implementation block
@property (assign,nonatomic) char hasUnlockSucceeded; 
@property (assign,nonatomic) char unlockSucceeded;                                 //@synthesize unlockSucceeded=_unlockSucceeded - In the implementation block
@property (assign,nonatomic) char hasErrorType; 
@property (assign,nonatomic) unsigned errorType;                                   //@synthesize errorType=_errorType - In the implementation block
@property (nonatomic,readonly) char hasErrorDomain; 
@property (nonatomic,retain) NSString * errorDomain;                               //@synthesize errorDomain=_errorDomain - In the implementation block
@property (assign,nonatomic) char hasErrorCode; 
@property (assign,nonatomic) unsigned errorCode;                                   //@synthesize errorCode=_errorCode - In the implementation block
@property (assign,nonatomic) char hasFlags; 
@property (assign,nonatomic) unsigned flags;                                       //@synthesize flags=_flags - In the implementation block
@property (assign,nonatomic) char hasDistance; 
@property (assign,nonatomic) unsigned distance;                                    //@synthesize distance=_distance - In the implementation block
@property (assign,nonatomic) char hasKeyBluetoothRSSI; 
@property (assign,nonatomic) int keyBluetoothRSSI;                                 //@synthesize keyBluetoothRSSI=_keyBluetoothRSSI - In the implementation block
@property (assign,nonatomic) char hasProxyBluetoothRSSI; 
@property (assign,nonatomic) int proxyBluetoothRSSI;                               //@synthesize proxyBluetoothRSSI=_proxyBluetoothRSSI - In the implementation block
@property (assign,nonatomic) char hasWithinRange; 
@property (assign,nonatomic) char withinRange;                                     //@synthesize withinRange=_withinRange - In the implementation block
@property (assign,nonatomic) char hasBleProxyConnectionTime; 
@property (assign,nonatomic) unsigned bleProxyConnectionTime;                      //@synthesize bleProxyConnectionTime=_bleProxyConnectionTime - In the implementation block
@property (assign,nonatomic) char hasBleKeyConnectionTime; 
@property (assign,nonatomic) unsigned bleKeyConnectionTime;                        //@synthesize bleKeyConnectionTime=_bleKeyConnectionTime - In the implementation block
@property (assign,nonatomic) char hasUsingTool; 
@property (assign,nonatomic) char usingTool;                                       //@synthesize usingTool=_usingTool - In the implementation block
@property (assign,nonatomic) char hasCancelTime; 
@property (assign,nonatomic) unsigned cancelTime;                                  //@synthesize cancelTime=_cancelTime - In the implementation block
@property (assign,nonatomic) char hasClamshellClosed; 
@property (assign,nonatomic) char clamshellClosed;                                 //@synthesize clamshellClosed=_clamshellClosed - In the implementation block
@property (assign,nonatomic) char hasBluetoothConnectedDevices; 
@property (assign,nonatomic) unsigned bluetoothConnectedDevices;                   //@synthesize bluetoothConnectedDevices=_bluetoothConnectedDevices - In the implementation block
@property (assign,nonatomic) char hasTimeIntervalSinceLastWake; 
@property (assign,nonatomic) int timeIntervalSinceLastWake;                        //@synthesize timeIntervalSinceLastWake=_timeIntervalSinceLastWake - In the implementation block
@property (assign,nonatomic) char hasLastSleepType; 
@property (assign,nonatomic) int lastSleepType;                                    //@synthesize lastSleepType=_lastSleepType - In the implementation block
@property (assign,nonatomic) char hasExternalDisplay; 
@property (assign,nonatomic) char externalDisplay;                                 //@synthesize externalDisplay=_externalDisplay - In the implementation block
@property (assign,nonatomic) char hasDisplayWaitTime; 
@property (assign,nonatomic) unsigned displayWaitTime;                             //@synthesize displayWaitTime=_displayWaitTime - In the implementation block
@property (assign,nonatomic) char hasClamshellWaitTime; 
@property (assign,nonatomic) unsigned clamshellWaitTime;                           //@synthesize clamshellWaitTime=_clamshellWaitTime - In the implementation block
@property (assign,nonatomic) char hasTimeIntervalSinceLastDarkWake; 
@property (assign,nonatomic) long long timeIntervalSinceLastDarkWake;              //@synthesize timeIntervalSinceLastDarkWake=_timeIntervalSinceLastDarkWake - In the implementation block
@property (assign,nonatomic) char hasCancelReason; 
@property (assign,nonatomic) int cancelReason;                                     //@synthesize cancelReason=_cancelReason - In the implementation block
@property (assign,nonatomic) char hasAttemptType; 
@property (assign,nonatomic) unsigned attemptType;                                 //@synthesize attemptType=_attemptType - In the implementation block
@property (nonatomic,readonly) char hasWatchBuildVersion; 
@property (nonatomic,retain) NSString * watchBuildVersion;                         //@synthesize watchBuildVersion=_watchBuildVersion - In the implementation block
@property (nonatomic,readonly) char hasWatchOSVersion; 
@property (nonatomic,retain) NSString * watchOSVersion;                            //@synthesize watchOSVersion=_watchOSVersion - In the implementation block
-(id)copyWithZone:(NSZone*)arg1 ;
-(unsigned)flags;
-(char)isEqual:(id)arg1 ;
-(unsigned long long)hash;
-(id)description;
-(id)dictionaryRepresentation;
-(unsigned long long)timestamp;
-(void)setFlags:(unsigned)arg1 ;
-(void)mergeFrom:(id)arg1 ;
-(char)readFrom:(id)arg1 ;
-(void)writeTo:(id)arg1 ;
-(void)copyTo:(id)arg1 ;
-(void)setTimestamp:(unsigned long long)arg1 ;
-(char)hasTimestamp;
-(unsigned)errorCode;
-(unsigned)distance;
-(unsigned)attemptType;
-(int)cancelReason;
-(void)setHasTimestamp:(char)arg1 ;
-(void)setDistance:(unsigned)arg1 ;
-(void)setHasDistance:(char)arg1 ;
-(char)hasDistance;
-(void)setErrorDomain:(NSString *)arg1 ;
-(void)setErrorCode:(unsigned)arg1 ;
-(NSString *)errorDomain;
-(char)hasErrorDomain;
-(void)setHasErrorCode:(char)arg1 ;
-(char)hasErrorCode;
-(void)setClamshellClosed:(char)arg1 ;
-(unsigned)errorType;
-(void)setHasFlags:(char)arg1 ;
-(char)hasFlags;
-(void)setHasClamshellClosed:(char)arg1 ;
-(char)hasClamshellClosed;
-(char)clamshellClosed;
-(void)setErrorType:(unsigned)arg1 ;
-(void)setHasErrorType:(char)arg1 ;
-(char)hasErrorType;
-(void)setCancelTime:(unsigned)arg1 ;
-(unsigned)cancelTime;
-(char)externalDisplay;
-(NSString *)watchOSVersion;
-(void)setAttemptType:(unsigned)arg1 ;
-(void)setLastSleepType:(int)arg1 ;
-(int)lastSleepType;
-(void)setProxyDeviceModel:(NSString *)arg1 ;
-(NSString *)proxyDeviceModel;
-(void)setKeyDeviceModel:(NSString *)arg1 ;
-(void)setWatchBuildVersion:(NSString *)arg1 ;
-(void)setWatchOSVersion:(NSString *)arg1 ;
-(void)setUsingProxy:(char)arg1 ;
-(void)setBleKeyDiscoveryTime:(unsigned)arg1 ;
-(void)setBleProxyDiscoveryTime:(unsigned)arg1 ;
-(void)setBleProxyConnectionTime:(unsigned)arg1 ;
-(void)setBleKeyConnectionTime:(unsigned)arg1 ;
-(void)setBleAWDLInfoExchangeTime:(unsigned)arg1 ;
-(void)setBleKeyRequestExchangeTime:(unsigned)arg1 ;
-(void)setBleAuthTokenExchangeTime:(unsigned)arg1 ;
-(void)setAwdlBringUpTime:(unsigned)arg1 ;
-(void)setAwdlPeerDiscoveryTime:(unsigned)arg1 ;
-(void)setAwdlRangingTime:(unsigned)arg1 ;
-(void)setBleConfirmationTime:(unsigned)arg1 ;
-(void)setTotalUnlockTime:(unsigned)arg1 ;
-(void)setUnlockSucceeded:(char)arg1 ;
-(void)setKeyBluetoothRSSI:(int)arg1 ;
-(void)setProxyBluetoothRSSI:(int)arg1 ;
-(void)setWithinRange:(char)arg1 ;
-(void)setUsingTool:(char)arg1 ;
-(void)setBluetoothConnectedDevices:(unsigned)arg1 ;
-(void)setTimeIntervalSinceLastWake:(int)arg1 ;
-(void)setExternalDisplay:(char)arg1 ;
-(void)setDisplayWaitTime:(unsigned)arg1 ;
-(void)setClamshellWaitTime:(unsigned)arg1 ;
-(void)setTimeIntervalSinceLastDarkWake:(long long)arg1 ;
-(void)setCancelReason:(int)arg1 ;
-(char)hasKeyDeviceModel;
-(char)hasWatchBuildVersion;
-(char)hasWatchOSVersion;
-(NSString *)keyDeviceModel;
-(NSString *)watchBuildVersion;
-(char)unlockSucceeded;
-(char)usingProxy;
-(char)usingTool;
-(char)hasProxyDeviceModel;
-(void)setHasUsingProxy:(char)arg1 ;
-(char)hasUsingProxy;
-(void)setHasBleKeyDiscoveryTime:(char)arg1 ;
-(char)hasBleKeyDiscoveryTime;
-(void)setHasBleProxyDiscoveryTime:(char)arg1 ;
-(char)hasBleProxyDiscoveryTime;
-(void)setHasBleAWDLInfoExchangeTime:(char)arg1 ;
-(char)hasBleAWDLInfoExchangeTime;
-(void)setHasBleKeyRequestExchangeTime:(char)arg1 ;
-(char)hasBleKeyRequestExchangeTime;
-(void)setHasBleAuthTokenExchangeTime:(char)arg1 ;
-(char)hasBleAuthTokenExchangeTime;
-(void)setHasAwdlBringUpTime:(char)arg1 ;
-(char)hasAwdlBringUpTime;
-(void)setHasAwdlPeerDiscoveryTime:(char)arg1 ;
-(char)hasAwdlPeerDiscoveryTime;
-(void)setHasAwdlRangingTime:(char)arg1 ;
-(char)hasAwdlRangingTime;
-(void)setHasBleConfirmationTime:(char)arg1 ;
-(char)hasBleConfirmationTime;
-(void)setHasTotalUnlockTime:(char)arg1 ;
-(char)hasTotalUnlockTime;
-(void)setHasUnlockSucceeded:(char)arg1 ;
-(char)hasUnlockSucceeded;
-(void)setHasKeyBluetoothRSSI:(char)arg1 ;
-(char)hasKeyBluetoothRSSI;
-(void)setHasProxyBluetoothRSSI:(char)arg1 ;
-(char)hasProxyBluetoothRSSI;
-(void)setHasWithinRange:(char)arg1 ;
-(char)hasWithinRange;
-(void)setHasBleProxyConnectionTime:(char)arg1 ;
-(char)hasBleProxyConnectionTime;
-(void)setHasBleKeyConnectionTime:(char)arg1 ;
-(char)hasBleKeyConnectionTime;
-(void)setHasUsingTool:(char)arg1 ;
-(char)hasUsingTool;
-(void)setHasCancelTime:(char)arg1 ;
-(char)hasCancelTime;
-(void)setHasBluetoothConnectedDevices:(char)arg1 ;
-(char)hasBluetoothConnectedDevices;
-(void)setHasTimeIntervalSinceLastWake:(char)arg1 ;
-(char)hasTimeIntervalSinceLastWake;
-(void)setHasLastSleepType:(char)arg1 ;
-(char)hasLastSleepType;
-(void)setHasExternalDisplay:(char)arg1 ;
-(char)hasExternalDisplay;
-(void)setHasDisplayWaitTime:(char)arg1 ;
-(char)hasDisplayWaitTime;
-(void)setHasClamshellWaitTime:(char)arg1 ;
-(char)hasClamshellWaitTime;
-(void)setHasTimeIntervalSinceLastDarkWake:(char)arg1 ;
-(char)hasTimeIntervalSinceLastDarkWake;
-(void)setHasCancelReason:(char)arg1 ;
-(char)hasCancelReason;
-(void)setHasAttemptType:(char)arg1 ;
-(char)hasAttemptType;
-(unsigned)bleKeyDiscoveryTime;
-(unsigned)bleProxyDiscoveryTime;
-(unsigned)bleAWDLInfoExchangeTime;
-(unsigned)bleKeyRequestExchangeTime;
-(unsigned)bleAuthTokenExchangeTime;
-(unsigned)awdlBringUpTime;
-(unsigned)awdlPeerDiscoveryTime;
-(unsigned)awdlRangingTime;
-(unsigned)bleConfirmationTime;
-(unsigned)totalUnlockTime;
-(int)keyBluetoothRSSI;
-(int)proxyBluetoothRSSI;
-(char)withinRange;
-(unsigned)bleProxyConnectionTime;
-(unsigned)bleKeyConnectionTime;
-(unsigned)bluetoothConnectedDevices;
-(int)timeIntervalSinceLastWake;
-(unsigned)displayWaitTime;
-(unsigned)clamshellWaitTime;
-(long long)timeIntervalSinceLastDarkWake;
@end

