/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, March 1, 2023 at 11:00:12 PM Israel Standard Time
* Operating System: Version 11.2.3 (Build 20D91)
* Image Source: /usr/libexec/sharingd
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <sharingd/sharingd-Structs.h>
#import <ProtocolBuffer/PBCodable.h>
#import <libobjc.A.dylib/NSCopying.h>

@interface AWDSharingCoordinatedAlertResult : PBCodable <NSCopying> {

	unsigned long long _timestamp;
	unsigned _activityLevel;
	unsigned _eventType;
	int _otherDevices;
	char _bestIsMe;
	char _skipScanPhoneCall;
	char _skipScanVeryActive;
	SCD_Struct_SD4 _has;

}

@property (assign,nonatomic) char hasTimestamp; 
@property (assign,nonatomic) unsigned long long timestamp;              //@synthesize timestamp=_timestamp - In the implementation block
@property (assign,nonatomic) char hasEventType; 
@property (assign,nonatomic) unsigned eventType;                        //@synthesize eventType=_eventType - In the implementation block
@property (assign,nonatomic) char hasActivityLevel; 
@property (assign,nonatomic) unsigned activityLevel;                    //@synthesize activityLevel=_activityLevel - In the implementation block
@property (assign,nonatomic) char hasOtherDevices; 
@property (assign,nonatomic) int otherDevices;                          //@synthesize otherDevices=_otherDevices - In the implementation block
@property (assign,nonatomic) char hasBestIsMe; 
@property (assign,nonatomic) char bestIsMe;                             //@synthesize bestIsMe=_bestIsMe - In the implementation block
@property (assign,nonatomic) char hasSkipScanPhoneCall; 
@property (assign,nonatomic) char skipScanPhoneCall;                    //@synthesize skipScanPhoneCall=_skipScanPhoneCall - In the implementation block
@property (assign,nonatomic) char hasSkipScanVeryActive; 
@property (assign,nonatomic) char skipScanVeryActive;                   //@synthesize skipScanVeryActive=_skipScanVeryActive - In the implementation block
-(id)copyWithZone:(NSZone*)arg1 ;
-(char)isEqual:(id)arg1 ;
-(unsigned long long)hash;
-(id)description;
-(id)dictionaryRepresentation;
-(unsigned long long)timestamp;
-(void)mergeFrom:(id)arg1 ;
-(char)readFrom:(id)arg1 ;
-(void)writeTo:(id)arg1 ;
-(void)copyTo:(id)arg1 ;
-(unsigned)eventType;
-(void)setTimestamp:(unsigned long long)arg1 ;
-(char)hasTimestamp;
-(void)setEventType:(unsigned)arg1 ;
-(void)setHasTimestamp:(char)arg1 ;
-(void)setHasEventType:(char)arg1 ;
-(char)hasEventType;
-(int)otherDevices;
-(unsigned)activityLevel;
-(void)setActivityLevel:(unsigned)arg1 ;
-(void)setHasActivityLevel:(char)arg1 ;
-(char)hasActivityLevel;
-(void)setOtherDevices:(int)arg1 ;
-(void)setHasOtherDevices:(char)arg1 ;
-(char)hasOtherDevices;
-(void)setBestIsMe:(char)arg1 ;
-(void)setHasBestIsMe:(char)arg1 ;
-(char)hasBestIsMe;
-(void)setSkipScanPhoneCall:(char)arg1 ;
-(void)setHasSkipScanPhoneCall:(char)arg1 ;
-(char)hasSkipScanPhoneCall;
-(void)setSkipScanVeryActive:(char)arg1 ;
-(void)setHasSkipScanVeryActive:(char)arg1 ;
-(char)hasSkipScanVeryActive;
-(char)bestIsMe;
-(char)skipScanPhoneCall;
-(char)skipScanVeryActive;
@end

