/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, March 1, 2023 at 11:00:14 PM Israel Standard Time
* Operating System: Version 11.2.3 (Build 20D91)
* Image Source: /usr/libexec/sharingd
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <sharingd/sharingd-Structs.h>
#import <ProtocolBuffer/PBCodable.h>
#import <libobjc.A.dylib/NSCopying.h>

@class NSString;

@interface AWDSharingAirDropTransferResult : PBCodable <NSCopying> {

	unsigned long long _bytesPerSec;
	unsigned long long _timestamp;
	NSString* _bundleID;
	int _errorCode;
	NSString* _errorDomain;
	NSString* _model;
	char _legacy;
	char _sender;
	char _success;
	SCD_Struct_AW52 _has;

}

@property (assign,nonatomic) char hasTimestamp; 
@property (assign,nonatomic) unsigned long long timestamp;                //@synthesize timestamp=_timestamp - In the implementation block
@property (assign,nonatomic) char hasSender; 
@property (assign,nonatomic) char sender;                                 //@synthesize sender=_sender - In the implementation block
@property (assign,nonatomic) char hasSuccess; 
@property (assign,nonatomic) char success;                                //@synthesize success=_success - In the implementation block
@property (assign,nonatomic) char hasBytesPerSec; 
@property (assign,nonatomic) unsigned long long bytesPerSec;              //@synthesize bytesPerSec=_bytesPerSec - In the implementation block
@property (nonatomic,readonly) char hasModel; 
@property (nonatomic,retain) NSString * model;                            //@synthesize model=_model - In the implementation block
@property (nonatomic,readonly) char hasBundleID; 
@property (nonatomic,retain) NSString * bundleID;                         //@synthesize bundleID=_bundleID - In the implementation block
@property (assign,nonatomic) char hasErrorCode; 
@property (assign,nonatomic) int errorCode;                               //@synthesize errorCode=_errorCode - In the implementation block
@property (nonatomic,readonly) char hasErrorDomain; 
@property (nonatomic,retain) NSString * errorDomain;                      //@synthesize errorDomain=_errorDomain - In the implementation block
@property (assign,nonatomic) char hasLegacy; 
@property (assign,nonatomic) char legacy;                                 //@synthesize legacy=_legacy - In the implementation block
-(id)copyWithZone:(NSZone*)arg1 ;
-(char)isEqual:(id)arg1 ;
-(unsigned long long)hash;
-(id)description;
-(void)setBundleID:(NSString *)arg1 ;
-(NSString *)bundleID;
-(void)setLegacy:(char)arg1 ;
-(id)dictionaryRepresentation;
-(unsigned long long)timestamp;
-(char)sender;
-(void)mergeFrom:(id)arg1 ;
-(char)readFrom:(id)arg1 ;
-(void)writeTo:(id)arg1 ;
-(void)copyTo:(id)arg1 ;
-(NSString *)model;
-(void)setSender:(char)arg1 ;
-(void)setModel:(NSString *)arg1 ;
-(char)success;
-(void)setTimestamp:(unsigned long long)arg1 ;
-(char)hasTimestamp;
-(int)errorCode;
-(char)legacy;
-(void)setHasTimestamp:(char)arg1 ;
-(void)setErrorDomain:(NSString *)arg1 ;
-(void)setErrorCode:(int)arg1 ;
-(NSString *)errorDomain;
-(char)hasErrorDomain;
-(void)setHasErrorCode:(char)arg1 ;
-(char)hasErrorCode;
-(char)hasModel;
-(void)setSuccess:(char)arg1 ;
-(char)hasSender;
-(char)hasSuccess;
-(void)setHasSuccess:(char)arg1 ;
-(char)hasBundleID;
-(void)setHasSender:(char)arg1 ;
-(void)setBytesPerSec:(unsigned long long)arg1 ;
-(void)setHasBytesPerSec:(char)arg1 ;
-(char)hasBytesPerSec;
-(void)setHasLegacy:(char)arg1 ;
-(char)hasLegacy;
-(unsigned long long)bytesPerSec;
@end

