/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, March 1, 2023 at 11:00:07 PM Israel Standard Time
* Operating System: Version 11.2.3 (Build 20D91)
* Image Source: /usr/libexec/sharingd
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <sharingd/sharingd-Structs.h>
#import <ProtocolBuffer/PBCodable.h>
#import <libobjc.A.dylib/NSCopying.h>

@class NSString;

@interface AWDSharingContinuityKeyboardResult : PBCodable <NSCopying> {

	unsigned long long _timestamp;
	unsigned _bannerVisibleMs;
	unsigned _beginEditingCount;
	unsigned _closeAction;
	unsigned _endEditingCount;
	unsigned _mainUIVisibleMs;
	unsigned _openAction;
	NSString* _sessionUUID;
	char _directInput;
	char _externalInput;
	char _secureInput;
	SCD_Struct_AW20 _has;

}

@property (assign,nonatomic) char hasTimestamp; 
@property (assign,nonatomic) unsigned long long timestamp;              //@synthesize timestamp=_timestamp - In the implementation block
@property (nonatomic,readonly) char hasSessionUUID; 
@property (nonatomic,retain) NSString * sessionUUID;                    //@synthesize sessionUUID=_sessionUUID - In the implementation block
@property (assign,nonatomic) char hasOpenAction; 
@property (assign,nonatomic) unsigned openAction;                       //@synthesize openAction=_openAction - In the implementation block
@property (assign,nonatomic) char hasCloseAction; 
@property (assign,nonatomic) unsigned closeAction;                      //@synthesize closeAction=_closeAction - In the implementation block
@property (assign,nonatomic) char hasBeginEditingCount; 
@property (assign,nonatomic) unsigned beginEditingCount;                //@synthesize beginEditingCount=_beginEditingCount - In the implementation block
@property (assign,nonatomic) char hasEndEditingCount; 
@property (assign,nonatomic) unsigned endEditingCount;                  //@synthesize endEditingCount=_endEditingCount - In the implementation block
@property (assign,nonatomic) char hasSecureInput; 
@property (assign,nonatomic) char secureInput;                          //@synthesize secureInput=_secureInput - In the implementation block
@property (assign,nonatomic) char hasDirectInput; 
@property (assign,nonatomic) char directInput;                          //@synthesize directInput=_directInput - In the implementation block
@property (assign,nonatomic) char hasExternalInput; 
@property (assign,nonatomic) char externalInput;                        //@synthesize externalInput=_externalInput - In the implementation block
@property (assign,nonatomic) char hasBannerVisibleMs; 
@property (assign,nonatomic) unsigned bannerVisibleMs;                  //@synthesize bannerVisibleMs=_bannerVisibleMs - In the implementation block
@property (assign,nonatomic) char hasMainUIVisibleMs; 
@property (assign,nonatomic) unsigned mainUIVisibleMs;                  //@synthesize mainUIVisibleMs=_mainUIVisibleMs - In the implementation block
-(id)copyWithZone:(NSZone*)arg1 ;
-(char)isEqual:(id)arg1 ;
-(unsigned long long)hash;
-(id)description;
-(id)dictionaryRepresentation;
-(unsigned long long)timestamp;
-(void)setCloseAction:(unsigned)arg1 ;
-(void)mergeFrom:(id)arg1 ;
-(char)readFrom:(id)arg1 ;
-(void)writeTo:(id)arg1 ;
-(void)copyTo:(id)arg1 ;
-(void)setTimestamp:(unsigned long long)arg1 ;
-(char)hasTimestamp;
-(void)setHasTimestamp:(char)arg1 ;
-(void)setSessionUUID:(NSString *)arg1 ;
-(char)hasSessionUUID;
-(NSString *)sessionUUID;
-(void)setOpenAction:(unsigned)arg1 ;
-(void)setHasOpenAction:(char)arg1 ;
-(char)hasOpenAction;
-(void)setHasCloseAction:(char)arg1 ;
-(char)hasCloseAction;
-(void)setBeginEditingCount:(unsigned)arg1 ;
-(void)setHasBeginEditingCount:(char)arg1 ;
-(char)hasBeginEditingCount;
-(void)setEndEditingCount:(unsigned)arg1 ;
-(void)setHasEndEditingCount:(char)arg1 ;
-(char)hasEndEditingCount;
-(void)setSecureInput:(char)arg1 ;
-(void)setHasSecureInput:(char)arg1 ;
-(char)hasSecureInput;
-(void)setDirectInput:(char)arg1 ;
-(void)setHasDirectInput:(char)arg1 ;
-(char)hasDirectInput;
-(void)setExternalInput:(char)arg1 ;
-(void)setHasExternalInput:(char)arg1 ;
-(char)hasExternalInput;
-(void)setBannerVisibleMs:(unsigned)arg1 ;
-(void)setHasBannerVisibleMs:(char)arg1 ;
-(char)hasBannerVisibleMs;
-(void)setMainUIVisibleMs:(unsigned)arg1 ;
-(void)setHasMainUIVisibleMs:(char)arg1 ;
-(char)hasMainUIVisibleMs;
-(unsigned)openAction;
-(unsigned)closeAction;
-(unsigned)beginEditingCount;
-(unsigned)endEditingCount;
-(char)secureInput;
-(char)directInput;
-(char)externalInput;
-(unsigned)bannerVisibleMs;
-(unsigned)mainUIVisibleMs;
@end

