/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, March 1, 2023 at 11:00:11 PM Israel Standard Time
* Operating System: Version 11.2.3 (Build 20D91)
* Image Source: /usr/libexec/sharingd
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol CRKShareTargetBrowserDelegate <NSObject>
@required
-(void)shareTargetBrowser:(id)arg1 didInterruptWithError:(id)arg2;
-(void)shareTargetBrowser:(id)arg1 didFindTargets:(id)arg2;
-(void)shareTargetBrowser:(id)arg1 didRemoveTargets:(id)arg2;

@end

