/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, March 1, 2023 at 11:00:02 PM Israel Standard Time
* Operating System: Version 11.2.3 (Build 20D91)
* Image Source: /usr/libexec/sharingd
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <sharingd/SDActivityRequestRecord.h>

@class NSData, NSString, RPCompanionLinkClient;

@interface SDActivityPayloadRequestRecord : SDActivityRequestRecord {

	NSData* _advertisementPayload;
	NSString* _command;
	RPCompanionLinkClient* _linkClient;

}

@property (nonatomic,copy) NSData * advertisementPayload;                     //@synthesize advertisementPayload=_advertisementPayload - In the implementation block
@property (nonatomic,copy) NSString * command;                                //@synthesize command=_command - In the implementation block
@property (nonatomic,retain) RPCompanionLinkClient * linkClient;              //@synthesize linkClient=_linkClient - In the implementation block
-(void)dealloc;
-(id)description;
-(NSString *)command;
-(void)setCommand:(NSString *)arg1 ;
-(NSData *)advertisementPayload;
-(RPCompanionLinkClient *)linkClient;
-(void)setLinkClient:(RPCompanionLinkClient *)arg1 ;
-(void)setAdvertisementPayload:(NSData *)arg1 ;
@end

