/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, March 1, 2023 at 11:00:08 PM Israel Standard Time
* Operating System: Version 11.2.3 (Build 20D91)
* Image Source: /usr/libexec/sharingd
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


#import <sharingd/sharingd-Structs.h>
@class NSDate, IDSDevice, NSData, NSUUID, SDActivityDecryptionKey, NSDictionary, SFActivityAdvertisement;

@interface SDActivityDeviceRecord : NSObject {

	NSDate* _lastReceivedAdvertisementDate;
	char _deviceTracked;
	char _disableDuplicateFilterOnce;
	IDSDevice* _idsDevice;
	NSData* _lastRawAdvertisementData;
	NSUUID* _lastUsedKeyIdentifier;
	NSData* _lastAdvertisementData;

}

@property (nonatomic,retain) NSUUID * lastUsedKeyIdentifier;                               //@synthesize lastUsedKeyIdentifier=_lastUsedKeyIdentifier - In the implementation block
@property (nonatomic,readonly) SDActivityDecryptionKey * decryptionKey; 
@property (nonatomic,copy,readonly) NSData * lastAdvertisementData;                        //@synthesize lastAdvertisementData=_lastAdvertisementData - In the implementation block
@property (nonatomic,readonly) SCD_Struct_SD30 lastActivityAdvertisement; 
@property (nonatomic,readonly) unsigned short lastCounter; 
@property (nonatomic,copy,readonly) NSData * lastAdvertisementPayload; 
@property (nonatomic,copy,readonly) NSDictionary * lastAdvertisementOptions; 
@property (nonatomic,retain) IDSDevice * idsDevice;                                        //@synthesize idsDevice=_idsDevice - In the implementation block
@property (assign,nonatomic) char deviceTracked;                                           //@synthesize deviceTracked=_deviceTracked - In the implementation block
@property (assign,nonatomic) char disableDuplicateFilterOnce;                              //@synthesize disableDuplicateFilterOnce=_disableDuplicateFilterOnce - In the implementation block
@property (nonatomic,copy,readonly) NSData * lastRawAdvertisementData;                     //@synthesize lastRawAdvertisementData=_lastRawAdvertisementData - In the implementation block
@property (nonatomic,readonly) SFActivityAdvertisement * clientAdvertisement; 
-(id)description;
-(id)initWithDevice:(id)arg1 ;
-(IDSDevice *)idsDevice;
-(void)setIdsDevice:(IDSDevice *)arg1 ;
-(SDActivityDecryptionKey *)decryptionKey;
-(char)deviceTracked;
-(SFActivityAdvertisement *)clientAdvertisement;
-(void)setDeviceTracked:(char)arg1 ;
-(void)updateWithRawAdvertisementData:(id)arg1 receivedViaScanning:(char)arg2 newAdvertisementHandler:(/*^block*/id)arg3 ;
-(void)updateWithRawAdvertisementData:(id)arg1 receivedViaScanning:(char)arg2 isReplay:(char)arg3 newAdvertisementHandler:(/*^block*/id)arg4 ;
-(unsigned short)lastCounter;
-(SCD_Struct_SD30)lastActivityAdvertisement;
-(NSData *)lastAdvertisementPayload;
-(NSDictionary *)lastAdvertisementOptions;
-(char)disableDuplicateFilterOnce;
-(void)setDisableDuplicateFilterOnce:(char)arg1 ;
-(NSData *)lastRawAdvertisementData;
-(NSUUID *)lastUsedKeyIdentifier;
-(void)setLastUsedKeyIdentifier:(NSUUID *)arg1 ;
-(NSData *)lastAdvertisementData;
@end

