/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, March 1, 2023 at 11:00:13 PM Israel Standard Time
* Operating System: Version 11.2.3 (Build 20D91)
* Image Source: /usr/libexec/sharingd
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class NSUUID, NSDate, NSMutableData, NSDictionary;

@interface SDActivityKey : NSObject {

	char _validKey;
	unsigned short _lastUsedCounter;
	NSUUID* _keyIdentifier;
	NSDate* _dateCreated;
	NSMutableData* _keyData;

}

@property (nonatomic,retain) NSUUID * keyIdentifier;                           //@synthesize keyIdentifier=_keyIdentifier - In the implementation block
@property (nonatomic,retain) NSDate * dateCreated;                             //@synthesize dateCreated=_dateCreated - In the implementation block
@property (nonatomic,retain) NSMutableData * keyData;                          //@synthesize keyData=_keyData - In the implementation block
@property (assign,nonatomic) unsigned short lastUsedCounter;                   //@synthesize lastUsedCounter=_lastUsedCounter - In the implementation block
@property (assign,getter=isValidKey,nonatomic) char validKey;                  //@synthesize validKey=_validKey - In the implementation block
@property (nonatomic,readonly) NSDictionary * dictRepresentation; 
-(void)dealloc;
-(char)isEqual:(id)arg1 ;
-(unsigned long long)hash;
-(id)description;
-(NSDictionary *)dictRepresentation;
-(NSUUID *)keyIdentifier;
-(void)setKeyIdentifier:(NSUUID *)arg1 ;
-(NSDate *)dateCreated;
-(NSMutableData *)keyData;
-(void)setDateCreated:(NSDate *)arg1 ;
-(void)setKeyData:(NSMutableData *)arg1 ;
-(id)initWithDictRepresentation:(id)arg1 ;
-(char)isValidKey;
-(void)setValidKey:(char)arg1 ;
-(unsigned short)lastUsedCounter;
-(void)setLastUsedCounter:(unsigned short)arg1 ;
@end

