/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, March 1, 2023 at 11:00:10 PM Israel Standard Time
* Operating System: Version 11.2.3 (Build 20D91)
* Image Source: /usr/libexec/sharingd
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol SDAirDropAlertManager <NSObject>
@property (assign,nonatomic,__weak) NSObject*<SDAirDropAlertManagerDelegate> delegate; 
@required
-(NSObject*<SDAirDropAlertManagerDelegate>)delegate;
-(void)setDelegate:(id)arg1;
-(void)askEventForRecordID:(id)arg1 withResults:(id)arg2;
-(void)progressEventForRecordID:(id)arg1 withResults:(id)arg2;
-(void)cancelEventForRecordID:(id)arg1 withResults:(id)arg2;
-(void)errorEventForRecordID:(id)arg1 withResults:(id)arg2;
-(void)finishedEventForRecordID:(id)arg1 withResults:(id)arg2;

@end

