/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, March 1, 2023 at 11:00:12 PM Israel Standard Time
* Operating System: Version 11.2.3 (Build 20D91)
* Image Source: /usr/libexec/sharingd
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <libobjc.A.dylib/SDAirDropListenerDelegate.h>
#import <libobjc.A.dylib/SDNetworkOperationDelegate.h>
#import <libobjc.A.dylib/SDAirDropAlertManagerDelegate.h>

@class SDAirDropListener, NSMutableDictionary, SDAirDropTransferManager, SDAirDropNCNotificationManager, SDAirDropClassroomTransferManager, NSString;

@interface SDAirDropReceiveManager : NSObject <SDAirDropListenerDelegate, SDNetworkOperationDelegate, SDAirDropAlertManagerDelegate> {

	SDAirDropListener* _listener;
	NSMutableDictionary* _transferIdentifierToNetworkOperation;
	SDAirDropTransferManager* _transferManager;
	SDAirDropNCNotificationManager* _notificationManager;
	SDAirDropClassroomTransferManager* _classroomTransferManager;

}

@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(NSString *)description;
-(id)init;
-(void)start;
-(void)stop;
-(void)listener:(id)arg1 didReceiveNewRequest:(id)arg2 ;
-(void)listener:(id)arg1 informationDidChange:(id)arg2 ;
-(void)listener:(id)arg1 didReceiveError:(id)arg2 ;
-(void)networkOperation:(id)arg1 event:(long long)arg2 withResults:(id)arg3 ;
-(void)alertManager:(id)arg1 cancelingTransferWithRecordID:(id)arg2 withFailureReason:(unsigned long long)arg3 ;
-(void)alertManager:(id)arg1 acceptingTransferWithRecordID:(id)arg2 withDestinationURL:(id)arg3 shouldExtractMediaFromPhotosBundlesForRecordID:(char)arg4 ;
@end

