/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, March 1, 2023 at 11:00:11 PM Israel Standard Time
* Operating System: Version 11.2.3 (Build 20D91)
* Image Source: /usr/libexec/sharingd
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol SDAirDropStatusDelegate;
@class NSMutableDictionary;

@interface SDAirDropStatus : NSObject {

	char _started;
	NSMutableDictionary* _properties;
	id<SDAirDropStatusDelegate> _delegate;

}

@property (__weak) id<SDAirDropStatusDelegate> delegate;              //@synthesize delegate=_delegate - In the implementation block
-(void)dealloc;
-(id)init;
-(id<SDAirDropStatusDelegate>)delegate;
-(void)setDelegate:(id<SDAirDropStatusDelegate>)arg1 ;
-(void)start;
-(void)stop;
-(void)somethingChanged:(id)arg1 ;
-(void)setStatusAndNotify;
@end

