/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, March 1, 2023 at 11:00:04 PM Israel Standard Time
* Operating System: Version 11.2.3 (Build 20D91)
* Image Source: /usr/libexec/sharingd
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class SFAirDropTransfer, NSURL, SDXPCHelperConnection, LSBundleProxy, NSString;

@interface SDAirDropHandler : NSObject {

	char _hasFiles;
	char _hasLinks;
	char _isActivated;
	char _handlingAppInstalled;
	SFAirDropTransfer* _transfer;
	/*^block*/id _completionHandler;
	NSURL* _downloadsURL;
	SDXPCHelperConnection* _xpcHelperConnection;
	LSBundleProxy* _bundleProxy;
	NSString* _handlingAppBundleID;

}

@property (nonatomic,retain) SFAirDropTransfer * transfer;                             //@synthesize transfer=_transfer - In the implementation block
@property (nonatomic,readonly) char hasFiles;                                          //@synthesize hasFiles=_hasFiles - In the implementation block
@property (nonatomic,readonly) char hasLinks;                                          //@synthesize hasLinks=_hasLinks - In the implementation block
@property (assign,nonatomic) char isActivated;                                         //@synthesize isActivated=_isActivated - In the implementation block
@property (nonatomic,retain) NSURL * downloadsURL;                                     //@synthesize downloadsURL=_downloadsURL - In the implementation block
@property (nonatomic,retain) SDXPCHelperConnection * xpcHelperConnection;              //@synthesize xpcHelperConnection=_xpcHelperConnection - In the implementation block
@property (nonatomic,retain) LSBundleProxy * bundleProxy;                              //@synthesize bundleProxy=_bundleProxy - In the implementation block
@property (nonatomic,readonly) char isJustFiles; 
@property (nonatomic,readonly) char isJustLinks; 
@property (nonatomic,readonly) unsigned long long totalSharedItemsCount; 
@property (nonatomic,copy,readonly) NSString * senderName; 
@property (nonatomic,copy,readonly) NSString * singleItemActionTitle; 
@property (assign,nonatomic) char handlingAppInstalled;                                //@synthesize handlingAppInstalled=_handlingAppInstalled - In the implementation block
@property (nonatomic,retain) NSString * handlingAppBundleID;                           //@synthesize handlingAppBundleID=_handlingAppBundleID - In the implementation block
@property (nonatomic,copy) id completionHandler;                                       //@synthesize completionHandler=_completionHandler - In the implementation block
@property (nonatomic,readonly) char canHandleTransfer; 
@property (nonatomic,readonly) NSString * suitableContentsTitle; 
@property (nonatomic,readonly) NSString * suitableContentsDescription; 
-(void)dealloc;
-(id)description;
-(id)init;
-(void)activate;
-(void)setCompletionHandler:(id)arg1 ;
-(id)completionHandler;
-(char)isActivated;
-(NSString *)senderName;
-(void)actionSelected:(id)arg1 ;
-(SFAirDropTransfer *)transfer;
-(void)setTransfer:(SFAirDropTransfer *)arg1 ;
-(long long)transferTypes;
-(void)setIsActivated:(char)arg1 ;
-(id)initWithTransfer:(id)arg1 bundleIdentifier:(id)arg2 ;
-(void)setBundleProxy:(LSBundleProxy *)arg1 ;
-(LSBundleProxy *)bundleProxy;
-(char)isJustLinks;
-(id)bundleProxyFromCandidateIdentifiers:(id)arg1 handlesURL:(id)arg2 ;
-(id)alertMessageLocalizedKeyForTypeDicts:(id)arg1 ;
-(id)initWithTransfer:(id)arg1 ;
-(char)canHandleTransfer;
-(NSString *)suitableContentsDescription;
-(char)isJustFiles;
-(unsigned long long)totalSharedItemsCount;
-(void)updatePossibleActions;
-(id)defaultActionForBundleProxy:(id)arg1 ;
-(NSString *)suitableContentsTitle;
-(NSString *)singleItemActionTitle;
-(id)cancelActionTitleToAccompanyActions:(id)arg1 ;
-(void)removeStatusMonitorObservers;
-(NSURL *)downloadsURL;
-(SDXPCHelperConnection *)xpcHelperConnection;
-(void)addStatusMonitorObservers;
-(void)triggerSelectedActionIfAppropriate;
-(void)prepareOrPerformOpenAction;
-(void)prepareForAccept;
-(char)openURLs:(id)arg1 ;
-(char)handlingAppInstalled;
-(NSString *)handlingAppBundleID;
-(void)setDownloadsURL:(NSURL *)arg1 ;
-(char)openURLs:(id)arg1 bundleIdentifier:(id)arg2 ;
-(void)transferUpdated;
-(void)lockStatusChanged:(id)arg1 ;
-(id)applicationProxyForBundleProxy:(id)arg1 ;
-(void)logReceiverBundleID:(id)arg1 forAppProxy:(id)arg2 andURL:(id)arg3 ;
-(void)removeItemAtURLToFreeUpSpace:(id)arg1 ;
-(char)hasFiles;
-(char)hasLinks;
-(void)setXpcHelperConnection:(SDXPCHelperConnection *)arg1 ;
-(void)setHandlingAppInstalled:(char)arg1 ;
-(void)setHandlingAppBundleID:(NSString *)arg1 ;
@end

