/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, March 1, 2023 at 11:00:07 PM Israel Standard Time
* Operating System: Version 11.2.3 (Build 20D91)
* Image Source: /usr/libexec/sharingd
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol OS_dispatch_source, SDAirDropFileZipperDelegate;
#import <sharingd/sharingd-Structs.h>
@class NSURL, NSString, SDStatusMonitor, NSMutableArray, NSMutableDictionary, NSObject, SDAirDropCompressor, NSArray, NSSet;

@interface SDAirDropFileZipper : NSObject {

	char _usePKZip;
	long long _fileCount;
	long long _totalBytes;
	BOMBomRef _bomArchive;
	NSURL* _tempFolder;
	NSString* _bomPath;
	NSURL* _destination;
	BOMCopierRef _bomCopier;
	long long _lastBytesCopied;
	long long _totalBytesCopied;
	SDStatusMonitor* _monitor;
	qtn_fileRef _quarantineData;
	CFReadStreamRef _readStream;
	CFWriteStreamRef _writeStream;
	double _timeStarted;
	double _lastProgress;
	NSMutableArray* _topLevelFiles;
	NSMutableArray* _placeholderFiles;
	NSMutableArray* _orderedRelativePaths;
	NSMutableDictionary* _relativePathToFile;
	NSObject*<OS_dispatch_source> _progressTimer;
	NSMutableDictionary* _alternateNames;
	SDAirDropCompressor* _compressionEngine;
	/*^block*/id _creationCompletionHandler;
	char _shouldExtractMediaFromPhotosBundles;
	int _clientPid;
	NSArray* _sourceFiles;
	NSString* _senderName;
	NSString* _compressionType;
	NSSet* _skipReadableCheckFiles;
	id<SDAirDropFileZipperDelegate> _delegate;
	SCD_Struct_SD24 _auditToken;

}

@property (assign) SCD_Struct_SD24 auditToken;                            //@synthesize auditToken=_auditToken - In the implementation block
@property (assign) int clientPid;                                         //@synthesize clientPid=_clientPid - In the implementation block
@property (copy) NSURL * destination; 
@property (copy) NSArray * sourceFiles;                                   //@synthesize sourceFiles=_sourceFiles - In the implementation block
@property (copy) NSString * senderName;                                   //@synthesize senderName=_senderName - In the implementation block
@property (copy) NSString * compressionType;                              //@synthesize compressionType=_compressionType - In the implementation block
@property (copy) NSSet * skipReadableCheckFiles;                          //@synthesize skipReadableCheckFiles=_skipReadableCheckFiles - In the implementation block
@property (assign) char shouldExtractMediaFromPhotosBundles;              //@synthesize shouldExtractMediaFromPhotosBundles=_shouldExtractMediaFromPhotosBundles - In the implementation block
@property (__weak) id<SDAirDropFileZipperDelegate> delegate;              //@synthesize delegate=_delegate - In the implementation block
-(void)dealloc;
-(id)init;
-(id<SDAirDropFileZipperDelegate>)delegate;
-(void)setDelegate:(id<SDAirDropFileZipperDelegate>)arg1 ;
-(SCD_Struct_SD24)auditToken;
-(void)setAuditToken:(SCD_Struct_SD24)arg1 ;
-(void)stop;
-(NSURL *)destination;
-(void)setDestination:(NSURL *)arg1 ;
-(int)clientPid;
-(void)setTotalBytes:(id)arg1 ;
-(NSString *)compressionType;
-(void)setCompressionType:(NSString *)arg1 ;
-(void)zip;
-(void)setSenderName:(NSString *)arg1 ;
-(NSString *)senderName;
-(CFReadStreamRef)copyReadStream;
-(char)isCompressor;
-(id)timeRemaining:(long long)arg1 timeNow:(double)arg2 ;
-(void)notifyClientForEvent:(long long)arg1 withProperty:(void*)arg2 ;
-(id)absoluteURLIfTopLevelFile:(const char*)arg1 isDirectory:(char)arg2 base:(CFURLRef)arg3 ;
-(void)notifyProgress:(long long)arg1 force:(char)arg2 ;
-(id)fixedRelativePath:(const char*)arg1 ;
-(void)quarantineFile:(id)arg1 ;
-(char)pathExistsInPlaceholderInfo:(id)arg1 ;
-(char)validFileName:(id)arg1 ;
-(void)removeFileFromPlaceholderList:(id)arg1 ;
-(CFArrayRef)copyReverseParentChain:(CFURLRef)arg1 base:(CFURLRef)arg2 ;
-(char)addFile:(CFURLRef)arg1 withBase:(CFURLRef)arg2 toBom:(BOMBomRef)arg3 ;
-(void)addParentChain:(BOMBomRef)arg1 file:(CFURLRef)arg2 base:(CFURLRef)arg3 ;
-(char)addFileURLToBom:(BOMBomRef)arg1 file:(CFURLRef)arg2 base:(CFURLRef)arg3 propertyKeys:(id)arg4 topLevel:(char)arg5 ;
-(long long)totalFileSize:(CFURLRef)arg1 ;
-(id)prettyNameBasedOnUUID:(id)arg1 ;
-(id)URLFromFileInfo:(id)arg1 ;
-(id)conflictResolvedURL:(id)arg1 ;
-(void)moveFile:(CFURLRef)arg1 toDestination:(CFURLRef)arg2 ;
-(char)isDecompressor;
-(char)createPlaceholderFiles;
-(int)bomCopierCopy:(id)arg1 destination:(id)arg2 options:(id)arg3 ;
-(void)moveFilesToDestination;
-(void)removeUnusedPlaceholderFiles;
-(void)allowProgressCircleToComplete;
-(id)temporaryBomPath;
-(char)initBomWithFiles;
-(void)startBomCopy:(id)arg1 destination:(id)arg2 options:(id)arg3 ;
-(void)setPlaceholderFiles:(id)arg1 withCreationCompletionHandler:(/*^block*/id)arg2 ;
-(void)setReadStream:(CFReadStreamRef)arg1 ;
-(void)bomCopierCopyFileFinished:(const char*)arg1 type:(int)arg2 size:(long long)arg3 operation:(int)arg4 ;
-(void)bomCopierFatalFileError:(int)arg1 ;
-(void)bomCopierFatalError:(const char*)arg1 ;
-(void)unzip;
-(void)setClientPid:(int)arg1 ;
-(NSArray *)sourceFiles;
-(void)setSourceFiles:(NSArray *)arg1 ;
-(NSSet *)skipReadableCheckFiles;
-(void)setSkipReadableCheckFiles:(NSSet *)arg1 ;
-(char)shouldExtractMediaFromPhotosBundles;
-(void)setShouldExtractMediaFromPhotosBundles:(char)arg1 ;
@end

