/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, March 1, 2023 at 11:00:04 PM Israel Standard Time
* Operating System: Version 11.2.3 (Build 20D91)
* Image Source: /usr/libexec/sharingd
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <libobjc.A.dylib/SDNetworkOperationDelegate.h>

@protocol SDAirDropListenerDelegate;
@class SDNetworkOperation, NSString;

@interface SDAirDropListener : NSObject <SDNetworkOperationDelegate> {

	SDNetworkOperation* _listener;
	char _contactsOnly;
	id<SDAirDropListenerDelegate> _delegate;

}

@property (assign) char contactsOnly;                                   //@synthesize contactsOnly=_contactsOnly - In the implementation block
@property (__weak) id<SDAirDropListenerDelegate> delegate;              //@synthesize delegate=_delegate - In the implementation block
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(void)dealloc;
-(NSString *)description;
-(id)init;
-(id<SDAirDropListenerDelegate>)delegate;
-(void)setDelegate:(id<SDAirDropListenerDelegate>)arg1 ;
-(void)start;
-(void)stop;
-(void)networkOperation:(id)arg1 event:(long long)arg2 withResults:(id)arg3 ;
-(char)contactsOnly;
-(void)setContactsOnly:(char)arg1 ;
@end

