/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, March 1, 2023 at 11:00:15 PM Israel Standard Time
* Operating System: Version 11.2.3 (Build 20D91)
* Image Source: /usr/libexec/sharingd
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <libobjc.A.dylib/_NSUserNotificationCenterDelegatePrivate.h>
#import <libobjc.A.dylib/SFAirDropTransferObserverDelegate.h>
#import <libobjc.A.dylib/SDAirDropNCProgressNotificationDelegate.h>

@class NSSound, NSMutableDictionary, NSUserNotificationCenter, SFAirDropTransferObserver, NSString;

@interface SDAirDropNCNotificationManager : NSObject <_NSUserNotificationCenterDelegatePrivate, SFAirDropTransferObserverDelegate, SDAirDropNCProgressNotificationDelegate> {

	NSSound* _incomingTransferSound;
	NSMutableDictionary* _transferIDToAirDropNotifications;
	NSUserNotificationCenter* _userNotificationCenter;
	SFAirDropTransferObserver* _transferObserver;

}

@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(void)dealloc;
-(id)init;
-(void)userNotificationCenter:(id)arg1 didActivateNotification:(id)arg2 ;
-(void)userNotificationCenter:(id)arg1 didDismissAlert:(id)arg2 ;
-(void)presentNotification:(id)arg1 ;
-(void)setProgress:(double)arg1 forNotification:(id)arg2 ;
-(void)updatedTransfer:(id)arg1 ;
-(void)removeNotification:(id)arg1 ;
-(char)transferIsReadyForOpen:(id)arg1 ;
@end

