/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, March 1, 2023 at 11:00:09 PM Israel Standard Time
* Operating System: Version 11.2.3 (Build 20D91)
* Image Source: /usr/libexec/sharingd
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class SFAirDropTransfer, NSUserNotification, NSString;

@interface SDAirDropNCNotification : NSObject {

	char _offerCancelAction;
	char _shouldShowNotification;
	SFAirDropTransfer* _transfer;
	NSUserNotification* _notification;

}

@property (nonatomic,retain) NSUserNotification * notification;                //@synthesize notification=_notification - In the implementation block
@property (nonatomic,copy,readonly) NSString * cancelActionTitle; 
@property (assign,nonatomic) char shouldShowNotification;                      //@synthesize shouldShowNotification=_shouldShowNotification - In the implementation block
@property (nonatomic,readonly) SFAirDropTransfer * transfer;                   //@synthesize transfer=_transfer - In the implementation block
@property (nonatomic,readonly) char offerCancelAction;                         //@synthesize offerCancelAction=_offerCancelAction - In the implementation block
+(id)incomingTransferSound;
-(NSUserNotification *)notification;
-(void)setNotification:(NSUserNotification *)arg1 ;
-(SFAirDropTransfer *)transfer;
-(char)shouldShowNotification;
-(void)createActionsForNotification:(id)arg1 ;
-(char)offerCancelAction;
-(NSString *)cancelActionTitle;
-(id)initWithTransfer:(id)arg1 offerCancelAction:(char)arg2 ;
-(void)triggerDismissAction;
-(void)triggerActivateActionWithIdentifier:(id)arg1 ;
-(void)setShouldShowNotification:(char)arg1 ;
@end

