/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, March 1, 2023 at 11:00:05 PM Israel Standard Time
* Operating System: Version 11.2.3 (Build 20D91)
* Image Source: /usr/libexec/sharingd
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <sharingd/SDXPCDaemon.h>
#import <libobjc.A.dylib/SDAirDropClassroomTransferManagerProtocol.h>
#import <libobjc.A.dylib/SDAirDropAlertManagerDelegate.h>

@class NSMutableDictionary, NSURL, SDXPCHelperConnection, SDAirDropTransferManager, NSString;

@interface SDAirDropClassroomTransferManager : SDXPCDaemon <SDAirDropClassroomTransferManagerProtocol, SDAirDropAlertManagerDelegate> {

	NSMutableDictionary* _transferIDToProgress;
	NSURL* _downloadsURL;
	SDXPCHelperConnection* _xpcHelperConnection;
	SDAirDropTransferManager* _transferManager;

}

@property (nonatomic,retain) SDAirDropTransferManager * transferManager;              //@synthesize transferManager=_transferManager - In the implementation block
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(id)init;
-(void)invalidate;
-(void)activate;
-(id)exportedInterface;
-(id)remoteObjectInterface;
-(id)machServiceName;
-(void)connectionInvalidated:(id)arg1 ;
-(char)shouldAcceptNewConnection:(id)arg1 ;
-(void)updateTransferWithIdentifier:(id)arg1 withState:(long long)arg2 information:(id)arg3 completionHandler:(/*^block*/id)arg4 ;
-(void)replaceIconValue:(id)arg1 forKey:(id)arg2 ;
-(id)makeDestinationDirectoryWithIdentifier:(id)arg1 error:(id*)arg2 ;
-(void)alertManager:(id)arg1 cancelingTransferWithRecordID:(id)arg2 withFailureReason:(unsigned long long)arg3 ;
-(SDAirDropTransferManager *)transferManager;
-(void)_enumerateRemoteObjectProxiesUsingBlock:(/*^block*/id)arg1 ;
-(void)alertManager:(id)arg1 acceptingTransferWithRecordID:(id)arg2 withDestinationURL:(id)arg3 shouldExtractMediaFromPhotosBundlesForRecordID:(char)arg4 ;
-(void)connectionEstablished:(id)arg1 ;
-(void)setTransferManager:(SDAirDropTransferManager *)arg1 ;
@end

