/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, March 1, 2023 at 11:00:04 PM Israel Standard Time
* Operating System: Version 11.2.3 (Build 20D91)
* Image Source: /usr/libexec/sharingd
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol SDAirDropClientDelegate <NSObject>
@optional
-(void)startProgress;
-(void)handleConversionProgress:(id)arg1;

@required
-(void)airDropClient:(id)arg1 event:(long long)arg2 withResults:(id)arg3;

@end

