/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, March 1, 2023 at 11:00:08 PM Israel Standard Time
* Operating System: Version 11.2.3 (Build 20D91)
* Image Source: /usr/libexec/sharingd
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <sharingd/SDAirDropHandlerGenericLinks.h>

@class SDAirDropHandlerWebLinks;

@interface SDAirDropHandlerKeynoteLiveLinks : SDAirDropHandlerGenericLinks {

	SDAirDropHandlerWebLinks* _webLinksHandler;

}
-(long long)transferTypes;
-(id)initWithTransfer:(id)arg1 ;
-(char)canHandleTransfer;
-(id)suitableContentsDescription;
-(void)updatePossibleActions;
@end

