/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, March 1, 2023 at 11:00:15 PM Israel Standard Time
* Operating System: Version 11.2.3 (Build 20D91)
* Image Source: /usr/libexec/sharingd
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <sharingd/SDAirDropHandler.h>

@class NSURL, SFAirDropAction;

@interface SDAirDropHandleriCloudDrive : SDAirDropHandler {

	NSURL* _iCloudDriveURL;
	SFAirDropAction* _action;
	char _useOpenWithText;

}

@property (nonatomic,readonly) SFAirDropAction * action; 
@property (assign,nonatomic) char useOpenWithText;                    //@synthesize useOpenWithText=_useOpenWithText - In the implementation block
-(SFAirDropAction *)action;
-(long long)transferTypes;
-(id)initWithTransfer:(id)arg1 ;
-(char)canHandleTransfer;
-(id)suitableContentsDescription;
-(void)updatePossibleActions;
-(id)cancelActionTitleToAccompanyActions:(id)arg1 ;
-(void)openCompletedItemsWithFilesApp;
-(void)saveCompletedItemsToiCloudDrive;
-(char)useOpenWithText;
-(void)setUseOpenWithText:(char)arg1 ;
@end

