/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, March 1, 2023 at 11:00:15 PM Israel Standard Time
* Operating System: Version 11.2.3 (Build 20D91)
* Image Source: /usr/libexec/sharingd
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <sharingd/sharingd-Structs.h>
#import <libobjc.A.dylib/APSConnectionDelegate.h>

@protocol OS_dispatch_queue, OS_dispatch_source;
@class NSMutableDictionary, NSString, NSDate, SDAppleIDDatabaseManager, NSObject, NSMutableArray, SDAppleIDIdentityRequest, SDAppleIDServerTask, APSConnection;

@interface SDAppleIDAgent : NSObject <APSConnectionDelegate> {

	char _agentEnabled;
	NSMutableDictionary* _agentMetaInfo;
	NSString* _appleID;
	NSDate* _creationDate;
	SDAppleIDDatabaseManager* _dbManager;
	NSObject*<OS_dispatch_queue> _dispatchQueue;
	NSMutableArray* _findPersonRequests;
	SDAppleIDIdentityRequest* _identityRequest;
	SDAppleIDServerTask* _infoRequest;
	char _linkIdentityEnabled;
	NSObject*<OS_dispatch_source> _periodicVerifyTimer;
	APSConnection* _pushConnection;
	NSString* _pushEnvironment;
	SDAppleIDServerTask* _task;
	SDAppleIDIdentityRequest* _testIdentityRequest;
	NSObject*<OS_dispatch_source> _throttledRetryTimer;
	char _updatePush;
	char _updatePeriodicVerifyTimer;

}

@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
+(id)sharedAgent;
-(void)dealloc;
-(id)init;
-(void)_activate;
-(void)invalidate;
-(void)_invalidate;
-(void)_update;
-(void)activate;
-(void)_removeObservers;
-(void)connection:(id)arg1 didReceivePublicToken:(id)arg2 ;
-(void)connection:(id)arg1 didReceiveIncomingMessage:(id)arg2 ;
-(void)connection:(id)arg1 didReceiveToken:(id)arg2 forTopic:(id)arg3 identifier:(id)arg4 ;
-(long long)_accountState;
-(id)detailedDescription;
-(id)_detailedDescription;
-(void)_prefsChanged;
-(void)_addObservers;
-(void)prefsChanged;
-(void)verifiedIdentityForEmailOrPhone:(id)arg1 completion:(/*^block*/id)arg2 ;
-(id)myAccount;
-(id)_accountForAppleID:(id)arg1 ;
-(id)_statusInfo;
-(id)accountForAppleID:(id)arg1 ;
-(id)statusInfo;
-(char)eduModeEnabled;
-(id)accountStatusForAppleID:(id)arg1 ;
-(SecIdentityRef)copyIdentityForAppleID:(id)arg1 ;
-(id)validationRecordInfoForAppleID:(id)arg1 ;
-(id)verifiedIdentityForCertificateChain:(id)arg1 emailOrPhone:(id)arg2 error:(id*)arg3 ;
-(void)_ensurePushStarted;
-(void)_ensurePeriodicVerifyTimerStarted;
-(int)_ensureEduModeDevicesAreCleanedUp;
-(void)handleAppleIDSignedInNotification;
-(void)handleAppleIDSignedOutNotification;
-(void)handleAppleIDChangedNotification;
-(void)handleUILockStatusChangedNotification;
-(void)handleKeyBagFirstUnlockNotification;
-(void)_ensurePushStopped;
-(void)_ensurePeriodicVerifyTimerStopped;
-(void)_ensureThrottledRetryTimerStopped;
-(int)_unlinkAppleIDIdentityFromCurrentUser;
-(char)_wasOldAgentIdentityQueried;
-(id)_metaInfoValueForKey:(id)arg1 ;
-(char)_wasIdentityLinkedOnce;
-(int)_linkAppleIDIdentityToCurrentUser;
-(void)_setMetaInfoValue:(id)arg1 forKey:(id)arg2 ;
-(unsigned long long)_keychainCleanupTag;
-(unsigned long long)_linkedIdentityVersion;
-(void)_handlePeriodicVerifyTimerFired;
-(void)_handleThrottledRetryTimerFired;
-(void)_setCurrentAppleIDIdentity:(id)arg1 ;
-(void)_setCurrentAppleIDContactInfo:(id)arg1 validationRecord:(id)arg2 ;
-(void)_verifyStateWithDelay:(double)arg1 ;
-(void)_updateAppleID;
-(void)_clearAccount;
-(void)_verifyState;
-(void)_handleCertificateStatusUpdate:(long long)arg1 forAppleID:(id)arg2 ;
-(void)_handleUILockStatusChange;
-(void)_ensureThrottledRetryTimerStartedWithSuggestedDelay:(unsigned long long)arg1 ;
-(void)_handleFindPersonResponse:(id)arg1 forRequest:(id)arg2 emailOrPhone:(id)arg3 withError:(id)arg4 queue:(id)arg5 completion:(/*^block*/id)arg6 ;
-(void)_handleInfoResponse:(id)arg1 forAppleID:(id)arg2 infoRequest:(id)arg3 certificateSerialNumber:(id)arg4 withError:(id)arg5 completion:(/*^block*/id)arg6 ;
-(void)_handleReceivedCertificateToken:(id)arg1 privateKeyPersistentReference:(id)arg2 forAppleID:(id)arg3 ;
-(void)_handleReceivedIdentity:(id)arg1 forAppleID:(id)arg2 identityRequest:(id)arg3 withError:(id)arg4 completion:(/*^block*/id)arg5 ;
-(void)_cleanUpAccount:(id)arg1 ;
-(void)_handleServerTaskCompletionWithError:(id)arg1 ;
-(void)_requestIdentityForAppleID:(id)arg1 certificateToken:(id)arg2 privateKeyPersistentReference:(id)arg3 withCompletion:(/*^block*/id)arg4 ;
-(char)_isOldAgentIdentityUsedForAccount:(id)arg1 ;
-(void)_handleOldAgentIdentityInUse;
-(int)_performKeyVerificationForIdentity:(id)arg1 ;
-(void)_handleKeyVerificationFailure;
-(int)_performKeychainCount;
-(void)_requestInfoForAppleID:(id)arg1 completion:(/*^block*/id)arg2 ;
-(void)_handleAccountIdentifierValidationRecordMismatch;
-(int)_ensureAppleIDLinkedToCurrentUser;
-(int)_ensureLinkedIdentityHasLatestVersion;
-(void)_handleUntrustedAppleIDCertificateChainForIdentity:(id)arg1 ;
-(void)_checkIfAppleIDCertificateChainIsValidForIdentity:(id)arg1 completion:(/*^block*/id)arg2 ;
-(void)queryVerifiedIdentityForEmailOrPhone:(id)arg1 queue:(id)arg2 completion:(/*^block*/id)arg3 ;
-(void)verifiedIdentityForEmailOrPhone:(id)arg1 queue:(id)arg2 completion:(/*^block*/id)arg3 ;
-(SecIdentityRef)_copyIdentityForAppleID:(id)arg1 ;
-(void)personInfoWithEmailOrPhone:(id)arg1 queue:(id)arg2 completion:(/*^block*/id)arg3 ;
-(void)_personInfoWithEmailOrPhone:(id)arg1 queue:(id)arg2 completion:(/*^block*/id)arg3 ;
-(void)_performServerTaskWithInfo:(id)arg1 completion:(/*^block*/id)arg2 ;
-(void)_performOtherTaskWithInfo:(id)arg1 completion:(/*^block*/id)arg2 ;
-(void)_handleAppleIDChangedNotification;
-(void)_handleAppleIDSignedInNotification;
-(void)_handleAppleIDSignedOutNotification;
-(void)_handleKeyBagFirstUnlockNotification;
-(void)_handleUILockStatusChangedNotification;
-(void)_updateMyInfo;
-(id)verifiedIdentityForEmailOrPhone:(id)arg1 ;
-(void)personInfoWithEmailOrPhone:(id)arg1 completion:(/*^block*/id)arg2 ;
-(void)requestWithInfo:(id)arg1 completion:(/*^block*/id)arg2 ;
@end

