/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, March 1, 2023 at 11:00:15 PM Israel Standard Time
* Operating System: Version 11.2.3 (Build 20D91)
* Image Source: /usr/libexec/sharingd
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class NSString;

@interface SDAppleIDVerifiedIdentity : NSObject {

	NSString* _accountIdentifier;
	NSString* _emailOrPhone;

}

@property (nonatomic,readonly) NSString * accountIdentifier;              //@synthesize accountIdentifier=_accountIdentifier - In the implementation block
@property (nonatomic,readonly) NSString * emailOrPhone;                   //@synthesize emailOrPhone=_emailOrPhone - In the implementation block
-(NSString *)accountIdentifier;
-(NSString *)emailOrPhone;
-(id)initWithAccountIdentifier:(id)arg1 emailOrPhone:(id)arg2 ;
@end

