/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, March 1, 2023 at 11:00:15 PM Israel Standard Time
* Operating System: Version 11.2.3 (Build 20D91)
* Image Source: /usr/libexec/sharingd
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <sharingd/sharingd-Structs.h>
#import <ProtocolBuffer/PBCodable.h>
#import <libobjc.A.dylib/NSCopying.h>

@class NSData;

@interface SDAutoUnlockKeyDataCache : PBCodable <NSCopying> {

	NSData* _escrowFirstStep;
	unsigned _escrowSessionID;
	NSData* _tokenFirstStep;
	unsigned _tokenSessionID;
	unsigned _version;
	SCD_Struct_SD3 _has;

}

@property (assign,nonatomic) char hasVersion; 
@property (assign,nonatomic) unsigned version;                       //@synthesize version=_version - In the implementation block
@property (nonatomic,readonly) char hasEscrowFirstStep; 
@property (nonatomic,retain) NSData * escrowFirstStep;               //@synthesize escrowFirstStep=_escrowFirstStep - In the implementation block
@property (nonatomic,readonly) char hasTokenFirstStep; 
@property (nonatomic,retain) NSData * tokenFirstStep;                //@synthesize tokenFirstStep=_tokenFirstStep - In the implementation block
@property (assign,nonatomic) char hasEscrowSessionID; 
@property (assign,nonatomic) unsigned escrowSessionID;               //@synthesize escrowSessionID=_escrowSessionID - In the implementation block
@property (assign,nonatomic) char hasTokenSessionID; 
@property (assign,nonatomic) unsigned tokenSessionID;                //@synthesize tokenSessionID=_tokenSessionID - In the implementation block
-(id)copyWithZone:(NSZone*)arg1 ;
-(char)isEqual:(id)arg1 ;
-(unsigned long long)hash;
-(id)description;
-(unsigned)version;
-(id)dictionaryRepresentation;
-(void)setVersion:(unsigned)arg1 ;
-(void)mergeFrom:(id)arg1 ;
-(char)readFrom:(id)arg1 ;
-(void)writeTo:(id)arg1 ;
-(void)copyTo:(id)arg1 ;
-(char)hasVersion;
-(void)setHasVersion:(char)arg1 ;
-(void)setEscrowFirstStep:(NSData *)arg1 ;
-(void)setTokenFirstStep:(NSData *)arg1 ;
-(char)hasEscrowFirstStep;
-(char)hasTokenFirstStep;
-(void)setEscrowSessionID:(unsigned)arg1 ;
-(void)setHasEscrowSessionID:(char)arg1 ;
-(char)hasEscrowSessionID;
-(void)setTokenSessionID:(unsigned)arg1 ;
-(void)setHasTokenSessionID:(char)arg1 ;
-(char)hasTokenSessionID;
-(NSData *)escrowFirstStep;
-(NSData *)tokenFirstStep;
-(unsigned)escrowSessionID;
-(unsigned)tokenSessionID;
@end

