/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, March 1, 2023 at 11:00:07 PM Israel Standard Time
* Operating System: Version 11.2.3 (Build 20D91)
* Image Source: /usr/libexec/sharingd
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <sharingd/SDAutoUnlockPairingSession.h>

@protocol OS_dispatch_source;
@class NSString, NSError, NSObject, SDUnlockSetupSessionCreated, NSDate, NSData;

@interface SDAutoUnlockPairingLockSession : SDAutoUnlockPairingSession {

	char _canceled;
	char _upsellDevice;
	char _setupRetryDevice;
	char _placeholder;
	char _waitingForCloudPairing;
	char _keyDeviceLocked;
	char _unlockEnabled;
	char _receivedSetupACK;
	char _receivedTokenACK;
	unsigned _errorType;
	int _watchOldLTKSyncStatus;
	int _watchNewLTKSyncStatus;
	NSString* _passcode;
	long long _sendState;
	NSString* _keyDeviceModel;
	NSString* _watchBuildVersion;
	NSString* _watchOSVersion;
	NSString* _companionDeviceModel;
	NSError* _setupError;
	NSObject*<OS_dispatch_source> _ltkTimer;
	SDUnlockSetupSessionCreated* _sessionCreatedMessage;
	long long _responseTimeout;
	long long _responseTimeoutFromServer;
	long long _messageTimeout;
	long long _messageTimeoutFromServer;
	long long _ltkTimerRetryCount;
	NSDate* _keyExchangeDate;
	NSDate* _tokenExchangeDate;
	double _keyExchangeInterval;
	double _tokenExchangeInterval;
	NSData* _remoteLTKHash;
	NSString* _setupMessageIdentifier;
	NSString* _tokenMessageIdentifier;

}

@property (assign,nonatomic) long long sendState;                                              //@synthesize sendState=_sendState - In the implementation block
@property (nonatomic,retain) NSString * keyDeviceModel;                                        //@synthesize keyDeviceModel=_keyDeviceModel - In the implementation block
@property (nonatomic,retain) NSString * watchBuildVersion;                                     //@synthesize watchBuildVersion=_watchBuildVersion - In the implementation block
@property (nonatomic,retain) NSString * watchOSVersion;                                        //@synthesize watchOSVersion=_watchOSVersion - In the implementation block
@property (nonatomic,retain) NSString * companionDeviceModel;                                  //@synthesize companionDeviceModel=_companionDeviceModel - In the implementation block
@property (nonatomic,retain) NSError * setupError;                                             //@synthesize setupError=_setupError - In the implementation block
@property (assign,nonatomic) char keyDeviceLocked;                                             //@synthesize keyDeviceLocked=_keyDeviceLocked - In the implementation block
@property (assign,nonatomic) char canceled;                                                    //@synthesize canceled=_canceled - In the implementation block
@property (assign,nonatomic) char unlockEnabled;                                               //@synthesize unlockEnabled=_unlockEnabled - In the implementation block
@property (nonatomic,retain) NSObject*<OS_dispatch_source> ltkTimer;                           //@synthesize ltkTimer=_ltkTimer - In the implementation block
@property (assign,nonatomic) char waitingForCloudPairing;                                      //@synthesize waitingForCloudPairing=_waitingForCloudPairing - In the implementation block
@property (assign,nonatomic) unsigned errorType;                                               //@synthesize errorType=_errorType - In the implementation block
@property (nonatomic,retain) SDUnlockSetupSessionCreated * sessionCreatedMessage;              //@synthesize sessionCreatedMessage=_sessionCreatedMessage - In the implementation block
@property (assign,nonatomic) long long responseTimeout;                                        //@synthesize responseTimeout=_responseTimeout - In the implementation block
@property (assign,nonatomic) long long responseTimeoutFromServer;                              //@synthesize responseTimeoutFromServer=_responseTimeoutFromServer - In the implementation block
@property (assign,nonatomic) long long messageTimeout;                                         //@synthesize messageTimeout=_messageTimeout - In the implementation block
@property (assign,nonatomic) long long messageTimeoutFromServer;                               //@synthesize messageTimeoutFromServer=_messageTimeoutFromServer - In the implementation block
@property (assign,nonatomic) long long ltkTimerRetryCount;                                     //@synthesize ltkTimerRetryCount=_ltkTimerRetryCount - In the implementation block
@property (nonatomic,retain) NSDate * keyExchangeDate;                                         //@synthesize keyExchangeDate=_keyExchangeDate - In the implementation block
@property (nonatomic,retain) NSDate * tokenExchangeDate;                                       //@synthesize tokenExchangeDate=_tokenExchangeDate - In the implementation block
@property (assign,nonatomic) double keyExchangeInterval;                                       //@synthesize keyExchangeInterval=_keyExchangeInterval - In the implementation block
@property (assign,nonatomic) double tokenExchangeInterval;                                     //@synthesize tokenExchangeInterval=_tokenExchangeInterval - In the implementation block
@property (nonatomic,retain) NSData * remoteLTKHash;                                           //@synthesize remoteLTKHash=_remoteLTKHash - In the implementation block
@property (assign,nonatomic) int watchOldLTKSyncStatus;                                        //@synthesize watchOldLTKSyncStatus=_watchOldLTKSyncStatus - In the implementation block
@property (assign,nonatomic) int watchNewLTKSyncStatus;                                        //@synthesize watchNewLTKSyncStatus=_watchNewLTKSyncStatus - In the implementation block
@property (assign,nonatomic) char receivedSetupACK;                                            //@synthesize receivedSetupACK=_receivedSetupACK - In the implementation block
@property (assign,nonatomic) char receivedTokenACK;                                            //@synthesize receivedTokenACK=_receivedTokenACK - In the implementation block
@property (nonatomic,retain) NSString * setupMessageIdentifier;                                //@synthesize setupMessageIdentifier=_setupMessageIdentifier - In the implementation block
@property (nonatomic,retain) NSString * tokenMessageIdentifier;                                //@synthesize tokenMessageIdentifier=_tokenMessageIdentifier - In the implementation block
@property (nonatomic,copy) NSString * passcode;                                                //@synthesize passcode=_passcode - In the implementation block
@property (assign,nonatomic) char upsellDevice;                                                //@synthesize upsellDevice=_upsellDevice - In the implementation block
@property (assign,nonatomic) char setupRetryDevice;                                            //@synthesize setupRetryDevice=_setupRetryDevice - In the implementation block
@property (assign,nonatomic) char placeholder;                                                 //@synthesize placeholder=_placeholder - In the implementation block
-(void)invalidate;
-(void)start;
-(void)cancel;
-(char)placeholder;
-(void)setPlaceholder:(char)arg1 ;
-(char)canceled;
-(void)setCanceled:(char)arg1 ;
-(void)setSetupError:(NSError *)arg1 ;
-(NSError *)setupError;
-(NSString *)passcode;
-(void)setPasscode:(NSString *)arg1 ;
-(unsigned)errorType;
-(char)unlockEnabled;
-(void)setUnlockEnabled:(char)arg1 ;
-(void)setErrorType:(unsigned)arg1 ;
-(NSString *)watchOSVersion;
-(long long)responseTimeout;
-(void)setWatchOldLTKSyncStatus:(int)arg1 ;
-(void)setWatchNewLTKSyncStatus:(int)arg1 ;
-(int)watchOldLTKSyncStatus;
-(int)watchNewLTKSyncStatus;
-(void)transport:(id)arg1 didReceivePayload:(id)arg2 type:(unsigned short)arg3 deviceID:(id)arg4 ;
-(void)transport:(id)arg1 didReceiveMessageACKForIdentifier:(id)arg2 ;
-(void)onqueue_start;
-(id)initWithDevice:(id)arg1 sessionID:(id)arg2 ;
-(void)setSetupRetryDevice:(char)arg1 ;
-(void)setUpsellDevice:(char)arg1 ;
-(char)waitingForCloudPairing;
-(void)updateForCloudPairing;
-(void)handleTimerFired;
-(void)notifyDelegateWithError:(id)arg1 ;
-(void)setKeyDeviceModel:(NSString *)arg1 ;
-(void)setCompanionDeviceModel:(NSString *)arg1 ;
-(void)setKeyDeviceLocked:(char)arg1 ;
-(void)setResponseTimeout:(long long)arg1 ;
-(void)setResponseTimeoutFromServer:(long long)arg1 ;
-(void)setMessageTimeout:(long long)arg1 ;
-(void)setMessageTimeoutFromServer:(long long)arg1 ;
-(void)setWatchBuildVersion:(NSString *)arg1 ;
-(void)setWatchOSVersion:(NSString *)arg1 ;
-(void)setReceivedSetupACK:(char)arg1 ;
-(void)setReceivedTokenACK:(char)arg1 ;
-(char)setupRetryDevice;
-(NSString *)keyDeviceModel;
-(NSString *)companionDeviceModel;
-(char)keyDeviceLocked;
-(long long)responseTimeoutFromServer;
-(long long)messageTimeout;
-(long long)messageTimeoutFromServer;
-(NSString *)watchBuildVersion;
-(char)receivedSetupACK;
-(char)receivedTokenACK;
-(id)generatedError;
-(char)validatePasscode:(id)arg1 ;
-(void)sendSetupRequest;
-(id)userInfoForKeychainMismatch;
-(id)userInfoForInternetSharing;
-(id)userInfoForWatchNotSignedIn;
-(id)userInfoForMacNotSignedIn;
-(void)onqueue_cancel;
-(void)onqueue_updateForCloudPairing;
-(void)handleSuccessfulPairing;
-(id)userInfoForNoWristDetectionNoPasscode;
-(id)userInfoForNoWristDetection;
-(id)userInfoForNoPasscode;
-(id)userInfoForNoCommunincation;
-(long long)sendState;
-(id)userInfoForNotCloudPaired;
-(NSData *)remoteLTKHash;
-(double)keyExchangeInterval;
-(double)tokenExchangeInterval;
-(char)upsellDevice;
-(NSObject*<OS_dispatch_source>)ltkTimer;
-(void)handleLTKTimerFired;
-(void)setLtkTimer:(NSObject*<OS_dispatch_source>)arg1 ;
-(char)ltkHashMatches;
-(void)handleEscrowSessionRequest;
-(long long)ltkTimerRetryCount;
-(void)setLtkTimerRetryCount:(long long)arg1 ;
-(void)restartLTKTimer;
-(id)userInfoForMissingLTK;
-(id)userInfoForWatchLocked;
-(void)setSessionCreatedMessage:(SDUnlockSetupSessionCreated *)arg1 ;
-(SDUnlockSetupSessionCreated *)sessionCreatedMessage;
-(void)setRemoteLTKHash:(NSData *)arg1 ;
-(id)userInfoCompanionViewNotSyncing;
-(id)userInfoForiPhoneNeedsUnlock;
-(id)userInfoForOldProtocol;
-(id)userInfoForNewProtocol;
-(void)sendCreateEscrowSecretWithStepData:(id)arg1 sessionID:(unsigned)arg2 ;
-(void)setWaitingForCloudPairing:(char)arg1 ;
-(void)setSendState:(long long)arg1 ;
-(void)setKeyExchangeDate:(NSDate *)arg1 ;
-(void)setSetupMessageIdentifier:(NSString *)arg1 ;
-(void)setTokenExchangeDate:(NSDate *)arg1 ;
-(void)setTokenMessageIdentifier:(NSString *)arg1 ;
-(void)handleKeyDeviceLocked;
-(NSDate *)keyExchangeDate;
-(void)setKeyExchangeInterval:(double)arg1 ;
-(void)handleSetupSessionCreated:(id)arg1 ;
-(NSDate *)tokenExchangeDate;
-(void)setTokenExchangeInterval:(double)arg1 ;
-(void)handleSetupCreateRecord:(id)arg1 ;
-(NSString *)setupMessageIdentifier;
-(NSString *)tokenMessageIdentifier;
-(void)notifyDelegateKeyDeviceIsLocked;
-(void)invalidateLTKTimer;
@end

