/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, March 1, 2023 at 11:00:08 PM Israel Standard Time
* Operating System: Version 11.2.3 (Build 20D91)
* Image Source: /usr/libexec/sharingd
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <libobjc.A.dylib/SDAutoUnlockTransportClient.h>

@protocol OS_dispatch_source;
@class NSString, NSData, NSObject, NSMutableDictionary, NSMutableArray;

@interface SDAutoUnlockAKSManager : NSObject <SDAutoUnlockTransportClient> {

	char _wristDetectDisabled;
	char _autoUnlockDisabledDueToManagement;
	char _waitingForUnlock;
	char _t208Machine;
	NSString* _localDeviceID;
	NSString* _state;
	NSData* _localLTK;
	NSString* _altDSID;
	NSObject*<OS_dispatch_source> _keybagAssertionTimer;
	NSObject*<OS_dispatch_source> _waitingForUnlockTimer;
	NSMutableDictionary* _remoteLTKs;
	NSMutableDictionary* _cachedSessions;
	NSMutableDictionary* _cachedSessionKeys;
	NSMutableDictionary* _watchIDsToPairingRecords;
	NSMutableDictionary* _preferredRemoteLTKForDeviceID;
	NSMutableArray* _watchIDsMissingSessionKey;
	NSString* _remoteLTKStorageFilePath;
	NSString* _watchIDsToPairingRecordsStorageFilePath;
	id _keybagAssertion;
	NSString* _companionIDStorageFilePath;
	NSString* _watchIDToCompanionIDStorageFilePath;

}

@property (assign,nonatomic) char autoUnlockDisabledDueToManagement;                           //@synthesize autoUnlockDisabledDueToManagement=_autoUnlockDisabledDueToManagement - In the implementation block
@property (assign,nonatomic) char waitingForUnlock;                                            //@synthesize waitingForUnlock=_waitingForUnlock - In the implementation block
@property (assign,nonatomic) char t208Machine;                                                 //@synthesize t208Machine=_t208Machine - In the implementation block
@property (nonatomic,copy) NSData * localLTK;                                                  //@synthesize localLTK=_localLTK - In the implementation block
@property (nonatomic,copy) NSString * altDSID;                                                 //@synthesize altDSID=_altDSID - In the implementation block
@property (retain) NSObject*<OS_dispatch_source> keybagAssertionTimer;                         //@synthesize keybagAssertionTimer=_keybagAssertionTimer - In the implementation block
@property (retain) NSObject*<OS_dispatch_source> waitingForUnlockTimer;                        //@synthesize waitingForUnlockTimer=_waitingForUnlockTimer - In the implementation block
@property (nonatomic,retain) NSMutableDictionary * remoteLTKs;                                 //@synthesize remoteLTKs=_remoteLTKs - In the implementation block
@property (nonatomic,retain) NSMutableDictionary * cachedSessions;                             //@synthesize cachedSessions=_cachedSessions - In the implementation block
@property (nonatomic,retain) NSMutableDictionary * cachedSessionKeys;                          //@synthesize cachedSessionKeys=_cachedSessionKeys - In the implementation block
@property (nonatomic,retain) NSMutableDictionary * watchIDsToPairingRecords;                   //@synthesize watchIDsToPairingRecords=_watchIDsToPairingRecords - In the implementation block
@property (nonatomic,retain) NSMutableDictionary * preferredRemoteLTKForDeviceID;              //@synthesize preferredRemoteLTKForDeviceID=_preferredRemoteLTKForDeviceID - In the implementation block
@property (nonatomic,retain) NSMutableArray * watchIDsMissingSessionKey;                       //@synthesize watchIDsMissingSessionKey=_watchIDsMissingSessionKey - In the implementation block
@property (assign,nonatomic) char wristDetectDisabled;                                         //@synthesize wristDetectDisabled=_wristDetectDisabled - In the implementation block
@property (nonatomic,copy) NSString * remoteLTKStorageFilePath;                                //@synthesize remoteLTKStorageFilePath=_remoteLTKStorageFilePath - In the implementation block
@property (nonatomic,copy) NSString * watchIDsToPairingRecordsStorageFilePath;                 //@synthesize watchIDsToPairingRecordsStorageFilePath=_watchIDsToPairingRecordsStorageFilePath - In the implementation block
@property (retain) id keybagAssertion;                                                         //@synthesize keybagAssertion=_keybagAssertion - In the implementation block
@property (nonatomic,copy) NSString * companionIDStorageFilePath;                              //@synthesize companionIDStorageFilePath=_companionIDStorageFilePath - In the implementation block
@property (nonatomic,copy) NSString * watchIDToCompanionIDStorageFilePath;                     //@synthesize watchIDToCompanionIDStorageFilePath=_watchIDToCompanionIDStorageFilePath - In the implementation block
@property (nonatomic,copy) NSString * localDeviceID;                                           //@synthesize localDeviceID=_localDeviceID - In the implementation block
@property (nonatomic,copy) NSString * state;                                                   //@synthesize state=_state - In the implementation block
@property (nonatomic,readonly) char viewSyncing; 
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
+(id)sharedManager;
-(id)init;
-(NSString *)state;
-(void)setState:(NSString *)arg1 ;
-(void)start;
-(NSString *)altDSID;
-(void)setAltDSID:(NSString *)arg1 ;
-(NSString *)localDeviceID;
-(void)setLocalDeviceID:(NSString *)arg1 ;
-(id)baseDictionary;
-(void)addObservers;
-(char)ltkExistsForKeyDevice:(id)arg1 ;
-(char)ltkExistsForKeyDevice:(id)arg1 updateLTKs:(char)arg2 ;
-(char)sessionKeyExistsForDeviceID:(id)arg1 ;
-(id)deviceIDsMissingSessionKey;
-(char)deviceEnabledAsKey:(id)arg1 ;
-(id)companionIDForWatchID:(id)arg1 ;
-(void)transport:(id)arg1 didReceivePayload:(id)arg2 type:(unsigned short)arg3 deviceID:(id)arg4 ;
-(id)escrowSecretCreationDateForDeviceID:(id)arg1 ;
-(void)consoleUserChanged:(id)arg1 ;
-(void)screenLockUnlocked:(id)arg1 ;
-(id)pairingIDForWatchID:(id)arg1 ;
-(char)disablePairingWithKeyDevice:(id)arg1 ;
-(void)updateDynamicStoreEnabled;
-(id)keyPairingIDForDeviceID:(id)arg1 ;
-(void)deleteEscrowSecretForDeviceID:(id)arg1 ;
-(void)deleteRangingKeyForDeviceID:(id)arg1 ;
-(void)updateLocalLTK;
-(void)addDeviceIDMissingSessionKey:(id)arg1 ;
-(id)decryptMessage:(id)arg1 authTag:(id)arg2 nonce:(id)arg3 bluetoothID:(id)arg4 cachedDevices:(char)arg5 errorCode:(long long*)arg6 ;
-(void)handleKeyBagLockStateChanged;
-(void)updateLTKs;
-(char)viewSyncing;
-(void)reloadPairingRecordsIfNeeded;
-(int)ltkSyncStatusForDeviceID:(id)arg1 hash:(id)arg2 modern:(char)arg3 ;
-(void)checkRemoteLTKForDeviceID:(id)arg1 ;
-(void)updatePreferredRemoteLTKForDeviceID:(id)arg1 ;
-(id)remoteLTKForDeviceID:(id)arg1 ;
-(char)hashMatchesAnyRemoteLTKForDeviceID:(id)arg1 ltkHash:(id)arg2 isPreferred:(char*)arg3 ;
-(id)aksPairingSessionForDeviceID:(id)arg1 originator:(char)arg2 errorCode:(long long*)arg3 ;
-(void)setCompanionID:(id)arg1 forWatchID:(id)arg2 ;
-(void)setPairingID:(id)arg1 forWatchID:(id)arg2 ;
-(char)storeRangingKey:(id)arg1 forDeviceID:(id)arg2 ;
-(id)ltkHashForLocalLTK;
-(void)loadWatchIDsToPairingRecords;
-(void)updateSessionKeys;
-(void)setAutoUnlockDisabledDueToManagement:(char)arg1 ;
-(void)handleRequiredStateDisabled;
-(void)updateRangingKeysIfNeccesary;
-(char)loadLocalLTK;
-(void)updateRemoteLTKs;
-(void)checkLocalLTK;
-(id)ltkInfoForDeviceID:(id)arg1 ;
-(NSData *)localLTK;
-(id)allKeychainDevices;
-(NSString *)remoteLTKStorageFilePath;
-(id)remoteLTKList;
-(NSString *)watchIDToCompanionIDStorageFilePath;
-(NSMutableDictionary *)watchIDsToPairingRecords;
-(id)rangingKeyForDeviceID:(id)arg1 ;
-(void)appleAccountSignedIn:(id)arg1 ;
-(void)appleAccountSignedOut:(id)arg1 ;
-(void)deviceFirstUnlocked:(id)arg1 ;
-(void)handleManagementChanged:(id)arg1 ;
-(char)autoUnlockDisabledDueToManagement;
-(char)storeLongTermKey:(id)arg1 forDeviceID:(id)arg2 name:(id)arg3 ;
-(void)generateLocalLTK;
-(void)updateLocalLTKForSignout;
-(void)removeAllRemoteLTKsOnSignOut;
-(void)loadLocalUniqueIDIfNeeded;
-(void)checkRemoteLTKs;
-(id)aksAuthSessionForDeviceID:(id)arg1 originator:(char)arg2 usingEscrow:(char)arg3 ;
-(id)escrowSecretForDevice:(id)arg1 ;
-(id)aksAuthorizationSessionForDeviceID:(id)arg1 originator:(char)arg2 externalACMContext:(id)arg3 ;
-(id)sessionKeyForDeviceID:(id)arg1 ;
-(NSMutableDictionary *)cachedSessionKeys;
-(NSMutableArray *)watchIDsMissingSessionKey;
-(void)setWatchIDsMissingSessionKey:(NSMutableArray *)arg1 ;
-(id)ltkInfoForDeviceID:(id)arg1 modern:(char)arg2 ;
-(void)setLocalLTK:(NSData *)arg1 ;
-(long long)ltkKeyClass;
-(void)disablePairingForAllKeyDevices;
-(void)clearRemoteLTKs;
-(char)t208Machine;
-(id)remoteLTKEntryForDeviceID:(id)arg1 ;
-(void)loadRemoteLTKsIfNeeded;
-(id)keychainDevices:(char)arg1 ;
-(id)modernSignedDevices;
-(id)signedDevices;
-(void)removeRemoteLTKForDeviceID:(id)arg1 ;
-(char)signLTKsForDeviceID:(id)arg1 ;
-(NSMutableDictionary *)remoteLTKs;
-(void)updateLTKsForDeviceID:(id)arg1 staleRemoteLTK:(char)arg2 ;
-(id)longTermKeyForDevice:(id)arg1 modern:(char)arg2 ;
-(id)remoteLTKHashForDeviceID:(id)arg1 modern:(char)arg2 ;
-(char)signLTK:(id)arg1 modernLTK:(id)arg2 forDeviceID:(id)arg3 ;
-(char)signLTK:(id)arg1 ltkModDate:(id)arg2 modernLTK:(id)arg3 modernLTKModDate:(id)arg4 deviceID:(id)arg5 ;
-(long long)keyClassForDeviceID:(id)arg1 ;
-(id)modificationDataForDeviceID:(id)arg1 modern:(char)arg2 ;
-(void)addRemoteLTK:(id)arg1 ltkHash:(id)arg2 ltkModDate:(id)arg3 modernLTK:(id)arg4 modernLTKHash:(id)arg5 modernLTKModeDate:(id)arg6 deviceID:(id)arg7 ;
-(id)baseModernSyncedDictionary;
-(id)baseSyncedDictionary;
-(char)deviceIsLocalDevice:(id)arg1 ;
-(id)modernSyncedDictionaryForDevice:(id)arg1 ;
-(id)syncedDictionaryForDevice:(id)arg1 ;
-(NSMutableDictionary *)preferredRemoteLTKForDeviceID;
-(void)fetchLTKsFromCompanionForDeviceID:(id)arg1 needsLTK:(char)arg2 remoteNeedsLTK:(char)arg3 checkViewState:(char)arg4 ;
-(char)pendingReceiveForPeer:(id)arg1 ;
-(char)pendingSendForPeer:(id)arg1 ;
-(void)restartKeybagAssertionTimer;
-(NSObject*<OS_dispatch_source>)keybagAssertionTimer;
-(void)releaseKeybagAssertion;
-(void)setKeybagAssertionTimer:(NSObject*<OS_dispatch_source>)arg1 ;
-(NSObject*<OS_dispatch_source>)waitingForUnlockTimer;
-(void)setWaitingForUnlock:(char)arg1 ;
-(void)setWaitingForUnlockTimer:(NSObject*<OS_dispatch_source>)arg1 ;
-(void)handleLTKRequest:(id)arg1 ;
-(void)handleLTKResponse:(id)arg1 ;
-(char)deviceEnabledAsKeyForAnyDevice;
-(char)deviceEnabledAsKeyForAnyIDSDevice;
-(char)escrowSecretExistsForDevice:(id)arg1 ;
-(void)resignRemoteLTKForDeviceID:(id)arg1 ;
-(void)deleteAllEscrowSecrets;
-(void)deleteAllRangingKeys;
-(id)allPairedWatchDeviceIDs;
-(void)deleteRemoteLongTermKeyForDeviceID:(id)arg1 modern:(char)arg2 tombstone:(char)arg3 ;
-(id)anyLongTermKeyForDeviceID:(id)arg1 ;
-(void)removePairingRecordForWatchID:(id)arg1 ;
-(void)saveRemoteLTKs;
-(void)setRemoteLTKs:(NSMutableDictionary *)arg1 ;
-(void)loadRemoteLTKs;
-(id)autoUnlockFolderPath;
-(void)saveWatchIDsToPairingRecords;
-(NSString *)watchIDsToPairingRecordsStorageFilePath;
-(void)setWatchIDsToPairingRecords:(NSMutableDictionary *)arg1 ;
-(void)migrateLegacyWatchIDToCompanionIDs;
-(id)loadLegacyWatchIDToCompanionIDMapping;
-(void)deleteLegacyWatchToCompanionIDs;
-(id)migrateLegacyCompanionIDs:(id)arg1 ;
-(id)loadCompanionIDs;
-(void)deleteLegacyCompanionIDs;
-(NSString *)companionIDStorageFilePath;
-(id)baseLocalKeysDictionaryForDevice:(id)arg1 type:(id)arg2 ;
-(id)keychainDataForQuery:(id)arg1 ;
-(char)storeKeychainItemWithAttributeDictionary:(id)arg1 updateDictionary:(id)arg2 addDictionary:(id)arg3 ;
-(id)baseLocalKeysDictionary;
-(char)storeLongTermKey:(id)arg1 forDeviceID:(id)arg2 name:(id)arg3 modern:(char)arg4 ;
-(id)baseRangingDictionary;
-(void)setCachedSessionKeys:(NSMutableDictionary *)arg1 ;
-(id)deriveKeyFromSharedSecret:(id)arg1 ;
-(id)baseRangingDictionaryForDevice:(id)arg1 ;
-(void)removeDeviceIDMissingSessionKey:(id)arg1 ;
-(void)clearAllDeviceIDsMissingSessionKeys;
-(id)aksAuthSessionForDeviceID:(id)arg1 originator:(char)arg2 ;
-(id)aksAuthorizationSessionForDeviceID:(id)arg1 originator:(char)arg2 ;
-(char)canCreateTokenSessionForDeviceID:(id)arg1 ;
-(char)encryptMessageData:(id)arg1 deviceID:(id)arg2 encryptedMessage:(id*)arg3 authTag:(id*)arg4 nonce:(id*)arg5 ;
-(id)allRemoteLTKData;
-(void)fetchLTKsFromCompanion:(char)arg1 ;
-(void)sendLTKResponseWithPayload:(id)arg1 viewState:(id)arg2 needsUnlock:(id)arg3 currentlySyncing:(id)arg4 ;
-(id)ltksForRequest:(id)arg1 ;
-(char)keychainNeedsSyncingForRequest:(id)arg1 ;
-(void)takeMobileKeybagAssertion;
-(void)restartWaitingForUnlockTimer;
-(void)invalidateWaitingForUnlockTimer;
-(char)localDeviceEnabledAsKey;
-(void)deleteEscrowSecretForAllDevices;
-(void)removeCompanionIDForWatchID:(id)arg1 ;
-(void)removePairingIDForWatchID:(id)arg1 ;
-(char)storeEscrowSecret:(id)arg1 pairingID:(id)arg2 deviceID:(id)arg3 ;
-(id)longTermKeyIDForDeviceID:(id)arg1 ;
-(char)wristDetectDisabled;
-(void)setWristDetectDisabled:(char)arg1 ;
-(char)waitingForUnlock;
-(void)setT208Machine:(char)arg1 ;
-(NSMutableDictionary *)cachedSessions;
-(void)setCachedSessions:(NSMutableDictionary *)arg1 ;
-(void)setPreferredRemoteLTKForDeviceID:(NSMutableDictionary *)arg1 ;
-(void)setRemoteLTKStorageFilePath:(NSString *)arg1 ;
-(void)setWatchIDsToPairingRecordsStorageFilePath:(NSString *)arg1 ;
-(id)keybagAssertion;
-(void)setKeybagAssertion:(id)arg1 ;
-(void)setCompanionIDStorageFilePath:(NSString *)arg1 ;
-(void)setWatchIDToCompanionIDStorageFilePath:(NSString *)arg1 ;
@end

