/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, March 1, 2023 at 11:00:09 PM Israel Standard Time
* Operating System: Version 11.2.3 (Build 20D91)
* Image Source: /usr/libexec/sharingd
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <sharingd/sharingd-Structs.h>
#import <ProtocolBuffer/PBCodable.h>
#import <libobjc.A.dylib/NSCopying.h>

@class NSString, NSData;

@interface SDAutoUnlockEscrowSecretInfo : PBCodable <NSCopying> {

	NSString* _pairingID;
	NSData* _secret;

}

@property (nonatomic,readonly) char hasSecret; 
@property (nonatomic,retain) NSData * secret;                   //@synthesize secret=_secret - In the implementation block
@property (nonatomic,readonly) char hasPairingID; 
@property (nonatomic,retain) NSString * pairingID;              //@synthesize pairingID=_pairingID - In the implementation block
-(id)copyWithZone:(NSZone*)arg1 ;
-(char)isEqual:(id)arg1 ;
-(unsigned long long)hash;
-(id)description;
-(NSData *)secret;
-(id)dictionaryRepresentation;
-(void)mergeFrom:(id)arg1 ;
-(char)readFrom:(id)arg1 ;
-(void)writeTo:(id)arg1 ;
-(void)copyTo:(id)arg1 ;
-(void)setSecret:(NSData *)arg1 ;
-(NSString *)pairingID;
-(void)setPairingID:(NSString *)arg1 ;
-(char)hasPairingID;
-(char)hasSecret;
@end

