/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, March 1, 2023 at 11:00:14 PM Israel Standard Time
* Operating System: Version 11.2.3 (Build 20D91)
* Image Source: /usr/libexec/sharingd
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <libobjc.A.dylib/_NSUserNotificationCenterDelegatePrivate.h>

@protocol OS_dispatch_source;
@class NSUserNotificationCenter, NSUserNotification, NSHashTable, NSDictionary, NSObject, NSString;

@interface SDAutoUnlockNotificationsManager : NSObject <_NSUserNotificationCenterDelegatePrivate> {

	NSUserNotificationCenter* _userNotificationCenter;
	NSUserNotification* _suggestionNotification;
	NSUserNotification* _setupRetryNotification;
	NSUserNotification* _radarNotification;
	id _doubleClickListener;
	id _cancelListener;
	NSHashTable* _observers;
	NSDictionary* _promptInfo;
	NSObject*<OS_dispatch_source> _notificationTimer;
	/*^block*/id _radarNotificationCompletion;

}

@property (retain) NSHashTable * observers;                                      //@synthesize observers=_observers - In the implementation block
@property (retain) NSDictionary * promptInfo;                                    //@synthesize promptInfo=_promptInfo - In the implementation block
@property (retain) NSObject*<OS_dispatch_source> notificationTimer;              //@synthesize notificationTimer=_notificationTimer - In the implementation block
@property (copy) id radarNotificationCompletion;                                 //@synthesize radarNotificationCompletion=_radarNotificationCompletion - In the implementation block
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
+(id)sharedManager;
-(void)dealloc;
-(id)init;
-(void)addObserver:(id)arg1 ;
-(void)removeObserver:(id)arg1 ;
-(void)userNotificationCenter:(id)arg1 didActivateNotification:(id)arg2 ;
-(void)userNotificationCenter:(id)arg1 didDismissAlert:(id)arg2 ;
-(NSHashTable *)observers;
-(void)setObservers:(NSHashTable *)arg1 ;
-(void)notifyObservers:(SEL)arg1 ;
-(NSObject*<OS_dispatch_source>)notificationTimer;
-(void)setNotificationTimer:(NSObject*<OS_dispatch_source>)arg1 ;
-(id)authPromptInfo;
-(void)showSetupRetryNotificationWithDevice:(id)arg1 ;
-(void)showSuggestionNotificationWithDevice:(id)arg1 ;
-(void)showFileRadarNotificationWithCompletion:(/*^block*/id)arg1 ;
-(void)showMacUnlockedNotificationWithDuration:(id)arg1 ;
-(NSDictionary *)promptInfo;
-(void)restartNotificationTimer:(unsigned long long)arg1 ;
-(void)setRadarNotificationCompletion:(id)arg1 ;
-(void)dismissNotification;
-(void)invalidateNotificationTimer;
-(id)radarNotificationCompletion;
-(void)showAuthorizationRequestNotificationWithDeviceID:(id)arg1 appName:(id)arg2 appIcon:(id)arg3 completion:(/*^block*/id)arg4 ;
-(void)removeAuthorizationRequestNotification;
-(void)showUnlockedByDeviceNotificationWithDeviceID:(id)arg1 ;
-(void)setPromptInfo:(NSDictionary *)arg1 ;
@end

