/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, March 1, 2023 at 11:00:05 PM Israel Standard Time
* Operating System: Version 11.2.3 (Build 20D91)
* Image Source: /usr/libexec/sharingd
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol SDAutoUnlockSessionDelegate <NSObject>
@optional
-(void)sessionDidReceiveKeyDeviceLocked:(id)arg1;
-(void)session:(id)arg1 didCompleteWithError:(id)arg2;
-(void)sessionDidStartConnection:(id)arg1;
-(void)sessionDidSendInitialData:(id)arg1;

@end

