/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, March 1, 2023 at 11:00:15 PM Israel Standard Time
* Operating System: Version 11.2.3 (Build 20D91)
* Image Source: /usr/libexec/sharingd
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@interface SDAutoUnlockMacIconCache : NSObject
-(id)iconImageDataForHash:(id)arg1 ;
-(void)cacheIconImageData:(id)arg1 hash:(id)arg2 appName:(id)arg3 ;
-(id)_userDefaultsKeyForHash:(id)arg1 ;
@end

