/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, March 1, 2023 at 11:00:04 PM Israel Standard Time
* Operating System: Version 11.2.3 (Build 20D91)
* Image Source: /usr/libexec/sharingd
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <sharingd/sharingd-Structs.h>
#import <ProtocolBuffer/PBCodable.h>
#import <libobjc.A.dylib/NSCopying.h>

@class NSData;

@interface SDAutoUnlockWiFiAWDLInfo : PBCodable <NSCopying> {

	unsigned _channelFlags;
	unsigned _discoveryMetric;
	NSData* _extraInfoData;
	NSData* _macAddress;
	unsigned _masterChannel;
	unsigned _preferredChannel;
	SCD_Struct_SD2 _has;

}

@property (nonatomic,readonly) char hasMacAddress; 
@property (nonatomic,retain) NSData * macAddress;                    //@synthesize macAddress=_macAddress - In the implementation block
@property (assign,nonatomic) char hasDiscoveryMetric; 
@property (assign,nonatomic) unsigned discoveryMetric;               //@synthesize discoveryMetric=_discoveryMetric - In the implementation block
@property (assign,nonatomic) char hasMasterChannel; 
@property (assign,nonatomic) unsigned masterChannel;                 //@synthesize masterChannel=_masterChannel - In the implementation block
@property (assign,nonatomic) char hasPreferredChannel; 
@property (assign,nonatomic) unsigned preferredChannel;              //@synthesize preferredChannel=_preferredChannel - In the implementation block
@property (assign,nonatomic) char hasChannelFlags; 
@property (assign,nonatomic) unsigned channelFlags;                  //@synthesize channelFlags=_channelFlags - In the implementation block
@property (nonatomic,readonly) char hasExtraInfoData; 
@property (nonatomic,retain) NSData * extraInfoData;                 //@synthesize extraInfoData=_extraInfoData - In the implementation block
-(id)copyWithZone:(NSZone*)arg1 ;
-(char)isEqual:(id)arg1 ;
-(unsigned long long)hash;
-(id)description;
-(id)dictionaryRepresentation;
-(void)mergeFrom:(id)arg1 ;
-(char)readFrom:(id)arg1 ;
-(void)writeTo:(id)arg1 ;
-(void)copyTo:(id)arg1 ;
-(void)setMacAddress:(NSData *)arg1 ;
-(NSData *)macAddress;
-(unsigned)preferredChannel;
-(void)setPreferredChannel:(unsigned)arg1 ;
-(char)hasMacAddress;
-(char)hasMasterChannel;
-(void)setExtraInfoData:(NSData *)arg1 ;
-(void)setDiscoveryMetric:(unsigned)arg1 ;
-(void)setHasDiscoveryMetric:(char)arg1 ;
-(char)hasDiscoveryMetric;
-(void)setMasterChannel:(unsigned)arg1 ;
-(void)setHasMasterChannel:(char)arg1 ;
-(void)setHasPreferredChannel:(char)arg1 ;
-(char)hasPreferredChannel;
-(void)setChannelFlags:(unsigned)arg1 ;
-(void)setHasChannelFlags:(char)arg1 ;
-(char)hasChannelFlags;
-(char)hasExtraInfoData;
-(unsigned)discoveryMetric;
-(unsigned)masterChannel;
-(unsigned)channelFlags;
-(NSData *)extraInfoData;
@end

