/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, March 1, 2023 at 11:00:09 PM Israel Standard Time
* Operating System: Version 11.2.3 (Build 20D91)
* Image Source: /usr/libexec/sharingd
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


#import <sharingd/sharingd-Structs.h>
@class NSData, NSString;

@interface SDAutoUnlockAKSSession : NSObject {

	ACMHandleRef _acmContext;
	char _ltkNeedsFixing;
	char _originator;
	char _usingEscrow;
	long long _aksSessionID;
	NSData* _localLTK;
	NSData* _remoteLTK;
	long long _sessionType;
	NSData* _escrowSecret;
	NSString* _deviceID;
	NSData* _externalACMContext;

}

@property (nonatomic,copy) NSData * localLTK;                        //@synthesize localLTK=_localLTK - In the implementation block
@property (nonatomic,copy) NSData * remoteLTK;                       //@synthesize remoteLTK=_remoteLTK - In the implementation block
@property (assign,nonatomic) long long sessionType;                  //@synthesize sessionType=_sessionType - In the implementation block
@property (assign,nonatomic) char originator;                        //@synthesize originator=_originator - In the implementation block
@property (nonatomic,copy) NSData * escrowSecret;                    //@synthesize escrowSecret=_escrowSecret - In the implementation block
@property (assign,nonatomic) char usingEscrow;                       //@synthesize usingEscrow=_usingEscrow - In the implementation block
@property (nonatomic,retain) NSString * deviceID;                    //@synthesize deviceID=_deviceID - In the implementation block
@property (nonatomic,copy) NSData * externalACMContext;              //@synthesize externalACMContext=_externalACMContext - In the implementation block
@property (assign,nonatomic) long long aksSessionID;                 //@synthesize aksSessionID=_aksSessionID - In the implementation block
@property (assign,nonatomic) char ltkNeedsFixing;                    //@synthesize ltkNeedsFixing=_ltkNeedsFixing - In the implementation block
-(NSString *)deviceID;
-(void)setDeviceID:(NSString *)arg1 ;
-(long long)sessionType;
-(void)setSessionType:(long long)arg1 ;
-(void)setOriginator:(char)arg1 ;
-(char)originator;
-(void)setupSession;
-(char)resetSession;
-(void)setExternalACMContext:(NSData *)arg1 ;
-(void)setAksSessionID:(long long)arg1 ;
-(long long)aksSessionID;
-(char)sessionIsValid;
-(char)stepSessionWithData:(id)arg1 outputData:(id*)arg2 ;
-(long long)finalizeEscrowPairing:(id)arg1 ;
-(id)generateSessionToken;
-(NSData *)localLTK;
-(id)initWithLocalLTK:(id)arg1 remoteLTK:(id)arg2 sessionType:(long long)arg3 originator:(char)arg4 deviceID:(id)arg5 ;
-(id)initWithLocalLTK:(id)arg1 remoteLTK:(id)arg2 sessionType:(long long)arg3 originator:(char)arg4 deviceID:(id)arg5 usingEscrow:(char)arg6 ;
-(id)initWithLocalLTK:(id)arg1 remoteLTK:(id)arg2 sessionType:(long long)arg3 originator:(char)arg4 deviceID:(id)arg5 escrowSecret:(id)arg6 ;
-(id)initWithLocalLTK:(id)arg1 remoteLTK:(id)arg2 sessionType:(long long)arg3 originator:(char)arg4 deviceID:(id)arg5 externalACMContext:(id)arg6 ;
-(void)setLocalLTK:(NSData *)arg1 ;
-(id)generateACMContextData;
-(NSData *)externalACMContext;
-(id)initWithLocalLTK:(id)arg1 remoteLTK:(id)arg2 sessionType:(long long)arg3 originator:(char)arg4 deviceID:(id)arg5 escrowSecret:(id)arg6 usingEscrow:(char)arg7 externalACMContext:(id)arg8 ;
-(NSData *)remoteLTK;
-(void)fixRemoteLTKWithStatus:(long long)arg1 retryBlock:(/*^block*/id)arg2 ;
-(char)usingEscrow;
-(NSData *)escrowSecret;
-(void)setupAuthorizationSession;
-(void)setRemoteLTK:(NSData *)arg1 ;
-(void)fixRemoteLTK;
-(id)generateEscrowSecret;
-(char)confirmSession;
-(char)ltkNeedsFixing;
-(void)setLtkNeedsFixing:(char)arg1 ;
-(void)setEscrowSecret:(NSData *)arg1 ;
-(void)setUsingEscrow:(char)arg1 ;
@end

