/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, March 1, 2023 at 11:00:06 PM Israel Standard Time
* Operating System: Version 11.2.3 (Build 20D91)
* Image Source: /usr/libexec/sharingd
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <libobjc.A.dylib/SDAutoUnlockTransportClient.h>
#import <libobjc.A.dylib/SDAutoUnlockNotificationsObserver.h>

@protocol OS_dispatch_source, OS_dispatch_queue;
@class NSString, SFAutoUnlockDevice, SFBLEScanner, NSMutableArray, NSObject, NSArray, NSUUID;

@interface SDAutoUnlockSuggestionManager : NSObject <SDAutoUnlockTransportClient, SDAutoUnlockNotificationsObserver> {

	char _foundFirstPeer;
	NSString* _suggestedDeviceID;
	NSString* _setupRetryDeviceID;
	SFAutoUnlockDevice* _lastSuccessfulDevice;
	SFBLEScanner* _scanner;
	NSMutableArray* _foundPeers;
	NSObject*<OS_dispatch_source> _scanTimer;
	NSArray* _currentBluetoothIDs;
	NSObject*<OS_dispatch_source> _serviceTimer;
	NSObject*<OS_dispatch_source> _deviceTimer;
	NSObject*<OS_dispatch_source> _setupRetryDeviceTimer;
	NSMutableArray* _suggestedPeers;
	SFAutoUnlockDevice* _suggestedPeer;
	NSUUID* _suggestionManagerSessionID;
	SFAutoUnlockDevice* _setupRetryDevice;
	NSObject*<OS_dispatch_queue> _suggestionManagerQueue;

}

@property (assign,nonatomic) char foundFirstPeer;                                              //@synthesize foundFirstPeer=_foundFirstPeer - In the implementation block
@property (nonatomic,retain) SFBLEScanner * scanner;                                           //@synthesize scanner=_scanner - In the implementation block
@property (nonatomic,retain) NSMutableArray * foundPeers;                                      //@synthesize foundPeers=_foundPeers - In the implementation block
@property (nonatomic,retain) NSObject*<OS_dispatch_source> scanTimer;                          //@synthesize scanTimer=_scanTimer - In the implementation block
@property (nonatomic,retain) NSArray * currentBluetoothIDs;                                    //@synthesize currentBluetoothIDs=_currentBluetoothIDs - In the implementation block
@property (nonatomic,retain) NSObject*<OS_dispatch_source> serviceTimer;                       //@synthesize serviceTimer=_serviceTimer - In the implementation block
@property (nonatomic,retain) NSObject*<OS_dispatch_source> deviceTimer;                        //@synthesize deviceTimer=_deviceTimer - In the implementation block
@property (nonatomic,retain) NSObject*<OS_dispatch_source> setupRetryDeviceTimer;              //@synthesize setupRetryDeviceTimer=_setupRetryDeviceTimer - In the implementation block
@property (nonatomic,retain) NSMutableArray * suggestedPeers;                                  //@synthesize suggestedPeers=_suggestedPeers - In the implementation block
@property (nonatomic,retain) SFAutoUnlockDevice * suggestedPeer;                               //@synthesize suggestedPeer=_suggestedPeer - In the implementation block
@property (nonatomic,retain) NSUUID * suggestionManagerSessionID;                              //@synthesize suggestionManagerSessionID=_suggestionManagerSessionID - In the implementation block
@property (nonatomic,retain) SFAutoUnlockDevice * setupRetryDevice;                            //@synthesize setupRetryDevice=_setupRetryDevice - In the implementation block
@property (nonatomic,retain) NSObject*<OS_dispatch_queue> suggestionManagerQueue;              //@synthesize suggestionManagerQueue=_suggestionManagerQueue - In the implementation block
@property (nonatomic,copy) NSString * suggestedDeviceID;                                       //@synthesize suggestedDeviceID=_suggestedDeviceID - In the implementation block
@property (nonatomic,copy) NSString * setupRetryDeviceID;                                      //@synthesize setupRetryDeviceID=_setupRetryDeviceID - In the implementation block
@property (nonatomic,retain) SFAutoUnlockDevice * lastSuccessfulDevice;                        //@synthesize lastSuccessfulDevice=_lastSuccessfulDevice - In the implementation block
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(id)init;
-(void)_systemWillSleep;
-(void)setScanTimer:(NSObject*<OS_dispatch_source>)arg1 ;
-(NSObject*<OS_dispatch_source>)scanTimer;
-(char)suggestionsEnabled;
-(void)setScanner:(SFBLEScanner *)arg1 ;
-(SFBLEScanner *)scanner;
-(void)addObservers;
-(NSMutableArray *)foundPeers;
-(void)setFoundPeers:(NSMutableArray *)arg1 ;
-(void)transport:(id)arg1 didReceivePayload:(id)arg2 type:(unsigned short)arg3 deviceID:(id)arg4 ;
-(void)screenLockUnlocked:(id)arg1 ;
-(void)restartScanTimer:(unsigned long long)arg1 ;
-(void)invalidateScanner;
-(NSString *)suggestedDeviceID;
-(void)setSuggestedDeviceID:(NSString *)arg1 ;
-(NSString *)setupRetryDeviceID;
-(void)setSetupRetryDeviceID:(NSString *)arg1 ;
-(void)setSetupRetryDevice:(SFAutoUnlockDevice *)arg1 ;
-(void)setFeatureSuggestedForDeviceID:(id)arg1 ;
-(void)setRetriedSetup;
-(void)setLastSuccessfulDevice:(SFAutoUnlockDevice *)arg1 ;
-(void)handleFoundPeer:(id)arg1 ;
-(void)invalidateScanTimer;
-(void)loadSuggestedPeers;
-(NSObject*<OS_dispatch_queue>)suggestionManagerQueue;
-(void)handleTestSuggestion;
-(void)_systemHasPoweredOn;
-(id)testDeviceID;
-(void)postSuggestionNotification;
-(NSMutableArray *)suggestedPeers;
-(char)featureSuggestedForDeviceID:(id)arg1 ;
-(char)ignoreBackOff;
-(char)shouldSendRequestsForDeviceID:(id)arg1 ;
-(void)sendStartAdvertisingToDeviceID:(id)arg1 ;
-(void)updateDefaultsForDeviceID:(id)arg1 ;
-(void)startScanningForIDSDeviceIDs:(id)arg1 ;
-(void)triggerDevicesIfNeeded;
-(void)setupRetryIfNeeded;
-(char)retriedSetup;
-(char)alwaysShowSetupRetry;
-(SFAutoUnlockDevice *)lastSuccessfulDevice;
-(SFAutoUnlockDevice *)setupRetryDevice;
-(void)openPreferencePaneWithDevice:(id)arg1 ;
-(void)restartSetupRetryDeviceTimer:(long long)arg1 ;
-(void)invalidateSuggestedDeviceTimer;
-(NSObject*<OS_dispatch_source>)setupRetryDeviceTimer;
-(void)setSetupRetryDeviceTimer:(NSObject*<OS_dispatch_source>)arg1 ;
-(void)setSuggestedPeer:(SFAutoUnlockDevice *)arg1 ;
-(SFAutoUnlockDevice *)suggestedPeer;
-(void)restartSuggestedDeviceTimer:(long long)arg1 ;
-(NSObject*<OS_dispatch_source>)deviceTimer;
-(void)setDeviceTimer:(NSObject*<OS_dispatch_source>)arg1 ;
-(void)restartServiceTimer:(unsigned long long)arg1 ;
-(void)invalidateServiceTimer;
-(NSObject*<OS_dispatch_source>)serviceTimer;
-(void)invalidateSuggestionService;
-(void)setServiceTimer:(NSObject*<OS_dispatch_source>)arg1 ;
-(void)setCurrentBluetoothIDs:(NSArray *)arg1 ;
-(NSArray *)currentBluetoothIDs;
-(char)foundFirstPeer;
-(void)setFoundFirstPeer:(char)arg1 ;
-(void)postNotificationIfNeeded;
-(NSUUID *)suggestionManagerSessionID;
-(void)updateSuggestionService;
-(void)watchAvailableForUnlockWithCompletionHandler:(/*^block*/id)arg1 ;
-(char)canSuggestForDeviceID:(id)arg1 ;
-(void)setSuggestedPeers:(NSMutableArray *)arg1 ;
-(void)suggestionNotificationSetUpSelected;
-(void)suggestionNotificationDismissed;
-(void)suggestionNotificationTimedOut;
-(void)setupRetryNotificationSetUpSelected;
-(void)setupRetryNotificationDismissed;
-(void)invalidateSetupRetryDeviceTimer;
-(void)setSuggestionManagerSessionID:(NSUUID *)arg1 ;
-(void)setSuggestionManagerQueue:(NSObject*<OS_dispatch_queue>)arg1 ;
@end

