/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, March 1, 2023 at 11:00:10 PM Israel Standard Time
* Operating System: Version 11.2.3 (Build 20D91)
* Image Source: /usr/libexec/sharingd
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <sharingd/SDAutoUnlockPairingSession.h>

@class SFBLEDevice, NSData, NSDate, NSNumber, NSString, NSError, NSDictionary, NSArray, SDAutoUnlockWiFiRequest, CWWiFiClient;

@interface SDAutoUnlockAuthSession : SDAutoUnlockPairingSession {

	char _useAKSToken;
	char _inRange;
	char _shouldUnlock;
	char _acceptor;
	char _rangingTimedOut;
	char _aksSuccess;
	char _legacyProtocol;
	char _useEncryption;
	SFBLEDevice* _bleDevice;
	long long _attemptType;
	NSData* _awdlInfoData;
	NSDate* _awdlStart;
	double _awdlInterval;
	NSNumber* _distance;
	NSData* _rangingKey;
	NSString* _rangingErrorString;
	NSDate* _rangingStart;
	double _rangingInterval;
	NSError* _attemptError;
	NSDictionary* _remoteAWDLInfo;
	NSDictionary* _localAWDLInfo;
	NSData* _sessionRangingKey;
	NSString* _wifiErrorDomain;
	long long _wifiRangingErrorCode;
	NSArray* _wifiRangingResults;
	NSError* _coreLocationError;
	NSError* _startAWDLError;
	long long _errorType;
	SDAutoUnlockWiFiRequest* _wifiRequest;
	NSString* _appName;
	NSData* _appIcon;
	CWWiFiClient* _wifiClient;

}

@property (nonatomic,readonly) char useRealRangingKey; 
@property (assign,nonatomic) char useAKSToken;                                   //@synthesize useAKSToken=_useAKSToken - In the implementation block
@property (assign,nonatomic) char inRange;                                       //@synthesize inRange=_inRange - In the implementation block
@property (assign,nonatomic) char shouldUnlock;                                  //@synthesize shouldUnlock=_shouldUnlock - In the implementation block
@property (nonatomic,retain) SFBLEDevice * bleDevice;                            //@synthesize bleDevice=_bleDevice - In the implementation block
@property (assign,nonatomic) long long attemptType;                              //@synthesize attemptType=_attemptType - In the implementation block
@property (nonatomic,copy) NSData * awdlInfoData;                                //@synthesize awdlInfoData=_awdlInfoData - In the implementation block
@property (assign,getter=isAcceptor,nonatomic) char acceptor;                    //@synthesize acceptor=_acceptor - In the implementation block
@property (nonatomic,retain) NSDate * awdlStart;                                 //@synthesize awdlStart=_awdlStart - In the implementation block
@property (assign,nonatomic) double awdlInterval;                                //@synthesize awdlInterval=_awdlInterval - In the implementation block
@property (nonatomic,retain) NSNumber * distance;                                //@synthesize distance=_distance - In the implementation block
@property (nonatomic,retain) NSData * rangingKey;                                //@synthesize rangingKey=_rangingKey - In the implementation block
@property (assign,nonatomic) char rangingTimedOut;                               //@synthesize rangingTimedOut=_rangingTimedOut - In the implementation block
@property (nonatomic,retain) NSString * rangingErrorString;                      //@synthesize rangingErrorString=_rangingErrorString - In the implementation block
@property (assign,nonatomic) char aksSuccess;                                    //@synthesize aksSuccess=_aksSuccess - In the implementation block
@property (nonatomic,readonly) char rangingDisabled; 
@property (nonatomic,readonly) char useCoreLocation; 
@property (nonatomic,retain) NSDate * rangingStart;                              //@synthesize rangingStart=_rangingStart - In the implementation block
@property (assign,nonatomic) double rangingInterval;                             //@synthesize rangingInterval=_rangingInterval - In the implementation block
@property (nonatomic,retain) NSError * attemptError;                             //@synthesize attemptError=_attemptError - In the implementation block
@property (nonatomic,retain) NSDictionary * remoteAWDLInfo;                      //@synthesize remoteAWDLInfo=_remoteAWDLInfo - In the implementation block
@property (nonatomic,retain) NSDictionary * localAWDLInfo;                       //@synthesize localAWDLInfo=_localAWDLInfo - In the implementation block
@property (nonatomic,retain) NSData * sessionRangingKey;                         //@synthesize sessionRangingKey=_sessionRangingKey - In the implementation block
@property (assign,nonatomic) char legacyProtocol;                                //@synthesize legacyProtocol=_legacyProtocol - In the implementation block
@property (assign,nonatomic) char useEncryption;                                 //@synthesize useEncryption=_useEncryption - In the implementation block
@property (nonatomic,retain) NSString * wifiErrorDomain;                         //@synthesize wifiErrorDomain=_wifiErrorDomain - In the implementation block
@property (assign,nonatomic) long long wifiRangingErrorCode;                     //@synthesize wifiRangingErrorCode=_wifiRangingErrorCode - In the implementation block
@property (nonatomic,retain) NSArray * wifiRangingResults;                       //@synthesize wifiRangingResults=_wifiRangingResults - In the implementation block
@property (nonatomic,retain) NSError * coreLocationError;                        //@synthesize coreLocationError=_coreLocationError - In the implementation block
@property (nonatomic,retain) NSError * startAWDLError;                           //@synthesize startAWDLError=_startAWDLError - In the implementation block
@property (assign,nonatomic) long long errorType;                                //@synthesize errorType=_errorType - In the implementation block
@property (nonatomic,retain) SDAutoUnlockWiFiRequest * wifiRequest;              //@synthesize wifiRequest=_wifiRequest - In the implementation block
@property (nonatomic,retain) NSString * appName;                                 //@synthesize appName=_appName - In the implementation block
@property (nonatomic,retain) NSData * appIcon;                                   //@synthesize appIcon=_appIcon - In the implementation block
@property (retain) CWWiFiClient * wifiClient;                                    //@synthesize wifiClient=_wifiClient - In the implementation block
-(void)invalidate;
-(void)start;
-(void)_start;
-(void)setUseEncryption:(char)arg1 ;
-(char)useEncryption;
-(void)setAppName:(NSString *)arg1 ;
-(NSString *)appName;
-(NSNumber *)distance;
-(long long)attemptType;
-(void)setDistance:(NSNumber *)arg1 ;
-(NSData *)appIcon;
-(void)setAppIcon:(NSData *)arg1 ;
-(SFBLEDevice *)bleDevice;
-(void)setBleDevice:(SFBLEDevice *)arg1 ;
-(long long)errorType;
-(void)setErrorType:(long long)arg1 ;
-(void)setAttemptType:(long long)arg1 ;
-(void)setUseAKSToken:(char)arg1 ;
-(void)handleMessageWithWrapper:(id)arg1 ;
-(id)initWithDevice:(id)arg1 sessionID:(id)arg2 bleDevice:(id)arg3 ;
-(NSArray *)wifiRangingResults;
-(void)setWifiRangingResults:(NSArray *)arg1 ;
-(SDAutoUnlockWiFiRequest *)wifiRequest;
-(void)setWifiRequest:(SDAutoUnlockWiFiRequest *)arg1 ;
-(char)aksSuccess;
-(double)awdlInterval;
-(double)rangingInterval;
-(char)shouldUnlock;
-(NSError *)attemptError;
-(char)useAKSToken;
-(void)sendAWDLInfo;
-(NSError *)startAWDLError;
-(NSDate *)rangingStart;
-(char)rangingDisabled;
-(void)setWifiErrorDomain:(NSString *)arg1 ;
-(void)setWifiRangingErrorCode:(long long)arg1 ;
-(void)setRangingInterval:(double)arg1 ;
-(void)setInRange:(char)arg1 ;
-(void)setRangingTimedOut:(char)arg1 ;
-(void)setRangingErrorString:(NSString *)arg1 ;
-(long long)wifiRangingErrorCode;
-(NSString *)rangingErrorString;
-(char)useCoreLocation;
-(void)setShouldUnlock:(char)arg1 ;
-(NSDate *)awdlStart;
-(NSError *)coreLocationError;
-(char)rangingTimedOut;
-(NSString *)wifiErrorDomain;
-(void)setAwdlInterval:(double)arg1 ;
-(void)setRangingStart:(NSDate *)arg1 ;
-(void)setAttemptError:(NSError *)arg1 ;
-(void)setRemoteAWDLInfo:(NSDictionary *)arg1 ;
-(void)setLegacyProtocol:(char)arg1 ;
-(void)setSessionRangingKey:(NSData *)arg1 ;
-(NSData *)sessionRangingKey;
-(NSDictionary *)remoteAWDLInfo;
-(id)peerListFromAWDLInfo:(id)arg1 ;
-(NSDictionary *)localAWDLInfo;
-(void)setAwdlStart:(NSDate *)arg1 ;
-(char)inRange;
-(void)setAksSuccess:(char)arg1 ;
-(void)sendData:(id)arg1 bleDevice:(id)arg2 completionHandler:(/*^block*/id)arg3 ;
-(void)sendData:(id)arg1 bleDevice:(id)arg2 direct:(char)arg3 completionHandler:(/*^block*/id)arg4 ;
-(void)sendData:(id)arg1 type:(unsigned short)arg2 errorHandler:(/*^block*/id)arg3 ;
-(void)sendData:(id)arg1 type:(unsigned short)arg2 completionHandler:(/*^block*/id)arg3 ;
-(char)isAcceptor;
-(id)getAppName;
-(void)connectionActivated;
-(void)sendAWDLInfoData:(id)arg1 type:(unsigned short)arg2 completionHandler:(/*^block*/id)arg3 ;
-(void)sendAWDLInfo:(char)arg1 ;
-(NSData *)awdlInfoData;
-(void)setLocalAWDLInfo:(NSDictionary *)arg1 ;
-(NSData *)rangingKey;
-(char)useRealRangingKey;
-(char)legacyProtocol;
-(void)setAwdlInfoData:(NSData *)arg1 ;
-(void)setAcceptor:(char)arg1 ;
-(void)setRangingKey:(NSData *)arg1 ;
-(void)setCoreLocationError:(NSError *)arg1 ;
-(void)setStartAWDLError:(NSError *)arg1 ;
-(CWWiFiClient *)wifiClient;
-(void)setWifiClient:(CWWiFiClient *)arg1 ;
@end

