/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, March 1, 2023 at 11:00:11 PM Israel Standard Time
* Operating System: Version 11.2.3 (Build 20D91)
* Image Source: /usr/libexec/sharingd
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class SDAutoUnlockLogConfiguration;

@interface SDAutoUnlockLogRequest : NSObject {

	SDAutoUnlockLogConfiguration* _currentConfig;

}

@property (nonatomic,retain) SDAutoUnlockLogConfiguration * currentConfig;              //@synthesize currentConfig=_currentConfig - In the implementation block
-(id)init;
-(void)addObservers;
-(void)screenLockUnlocked:(id)arg1 ;
-(void)createRadarWithConfiguration:(id)arg1 ;
-(SDAutoUnlockLogConfiguration *)currentConfig;
-(void)_createRadarWithConfiguration:(id)arg1 ;
-(void)setCurrentConfig:(SDAutoUnlockLogConfiguration *)arg1 ;
-(id)createHoneybeeFileWithIdentifier:(id)arg1 ;
-(void)fileRadarWithConfiguration:(id)arg1 honeybeeFilePath:(id)arg2 ;
@end

