/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, March 1, 2023 at 11:00:13 PM Israel Standard Time
* Operating System: Version 11.2.3 (Build 20D91)
* Image Source: /usr/libexec/sharingd
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <libobjc.A.dylib/CLLocationManagerDelegate.h>
#import <libobjc.A.dylib/CWEventDelegate.h>

@protocol OS_dispatch_source;
@class CWWiFiClient, NSObject, SDAutoUnlockWiFiRequest, CLLocationManager, NSMutableArray, NSString;

@interface SDAutoUnlockWiFiManager : NSObject <CLLocationManagerDelegate, CWEventDelegate> {

	char _awdlStartFailed;
	char _awdlStarting;
	char _awdlTimerFired;
	CWWiFiClient* _wifiClient;
	NSObject*<OS_dispatch_source> _awdlTimer;
	id _awdlNetwork;
	SDAutoUnlockWiFiRequest* _currentRequest;
	CLLocationManager* _locationManager;
	NSMutableArray* _wifiRequestQueue;

}

@property (retain) CWWiFiClient * wifiClient;                                  //@synthesize wifiClient=_wifiClient - In the implementation block
@property (retain) NSObject*<OS_dispatch_source> awdlTimer;                    //@synthesize awdlTimer=_awdlTimer - In the implementation block
@property (retain) id awdlNetwork;                                             //@synthesize awdlNetwork=_awdlNetwork - In the implementation block
@property (assign,nonatomic) char awdlStartFailed;                             //@synthesize awdlStartFailed=_awdlStartFailed - In the implementation block
@property (assign,nonatomic) char awdlStarting;                                //@synthesize awdlStarting=_awdlStarting - In the implementation block
@property (assign,nonatomic) char awdlTimerFired;                              //@synthesize awdlTimerFired=_awdlTimerFired - In the implementation block
@property (retain) SDAutoUnlockWiFiRequest * currentRequest;                   //@synthesize currentRequest=_currentRequest - In the implementation block
@property (nonatomic,retain) CLLocationManager * locationManager;              //@synthesize locationManager=_locationManager - In the implementation block
@property (nonatomic,retain) NSMutableArray * wifiRequestQueue;                //@synthesize wifiRequestQueue=_wifiRequestQueue - In the implementation block
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
+(id)sharedManager;
-(id)init;
-(void)start;
-(void)_removeObservers;
-(void)rangingReportEventForWiFiInterfaceWithName:(id)arg1 data:(id)arg2 error:(id)arg3 ;
-(CLLocationManager *)locationManager;
-(void)setLocationManager:(CLLocationManager *)arg1 ;
-(void)_createLocationManager;
-(void)setCurrentRequest:(SDAutoUnlockWiFiRequest *)arg1 ;
-(SDAutoUnlockWiFiRequest *)currentRequest;
-(void)_addObservers;
-(void)_invalidateCurrentRequest;
-(char)addWiFiRequest:(id)arg1 ;
-(void)cancelWiFiRequest:(id)arg1 ;
-(CWWiFiClient *)wifiClient;
-(void)setWifiClient:(CWWiFiClient *)arg1 ;
-(id)awdlNetwork;
-(void)_createWiFiObserver;
-(void)handleVirtualInterfacesChanged:(id)arg1 ;
-(NSMutableArray *)wifiRequestQueue;
-(void)_processRequestQueue;
-(void)_disableRangeable;
-(void)_stopAWDL;
-(void)setAwdlStarting:(char)arg1 ;
-(void)_startAWDLWithInfo:(id)arg1 ;
-(void)_startRangingIfPeerFoundInStateInfo:(id)arg1 awdlUpSameTime:(char)arg2 ;
-(void)setAwdlStartFailed:(char)arg1 ;
-(void)setAwdlTimerFired:(char)arg1 ;
-(void)invalidateAWDLTimer;
-(NSObject*<OS_dispatch_source>)awdlTimer;
-(void)handleAWDLTimerFired;
-(void)setAwdlTimer:(NSObject*<OS_dispatch_source>)arg1 ;
-(char)_peerFoundInStateInfo:(id)arg1 ;
-(void)_startRanging;
-(void)_handleVirtualInterfacesChanged:(id)arg1 ;
-(void)_handleAWDLDisabledIfNeeded;
-(void)_enableRangeableIfNeeded;
-(void)locationManager:(id)arg1 didRangePeers:(id)arg2 ;
-(void)locationManager:(id)arg1 rangingDidFailForPeer:(id)arg2 withError:(id)arg3 ;
-(void)restartAWDLTimer;
-(void)setAwdlNetwork:(id)arg1 ;
-(char)awdlStartFailed;
-(char)awdlStarting;
-(char)awdlTimerFired;
-(void)setWifiRequestQueue:(NSMutableArray *)arg1 ;
@end

