/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, March 1, 2023 at 11:00:04 PM Israel Standard Time
* Operating System: Version 11.2.3 (Build 20D91)
* Image Source: /usr/libexec/sharingd
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <sharingd/sharingd-Structs.h>
#import <ProtocolBuffer/PBCodable.h>
#import <libobjc.A.dylib/NSCopying.h>

@class NSString, NSData;

@interface SDAutoUnlockAWDLInfo : PBCodable <NSCopying> {

	NSString* _appName;
	NSData* _awdlInfo;
	unsigned _errorCode;
	NSData* _keyData;
	unsigned _version;
	char _authPrompt;
	char _supportsConfirmationACK;
	char _useToken;
	SCD_Struct_SD10 _has;

}

@property (assign,nonatomic) char hasVersion; 
@property (assign,nonatomic) unsigned version;                             //@synthesize version=_version - In the implementation block
@property (nonatomic,readonly) char hasAwdlInfo; 
@property (nonatomic,retain) NSData * awdlInfo;                            //@synthesize awdlInfo=_awdlInfo - In the implementation block
@property (assign,nonatomic) char hasUseToken; 
@property (assign,nonatomic) char useToken;                                //@synthesize useToken=_useToken - In the implementation block
@property (nonatomic,readonly) char hasKeyData; 
@property (nonatomic,retain) NSData * keyData;                             //@synthesize keyData=_keyData - In the implementation block
@property (assign,nonatomic) char hasErrorCode; 
@property (assign,nonatomic) unsigned errorCode;                           //@synthesize errorCode=_errorCode - In the implementation block
@property (assign,nonatomic) char hasAuthPrompt; 
@property (assign,nonatomic) char authPrompt;                              //@synthesize authPrompt=_authPrompt - In the implementation block
@property (assign,nonatomic) char hasSupportsConfirmationACK; 
@property (assign,nonatomic) char supportsConfirmationACK;                 //@synthesize supportsConfirmationACK=_supportsConfirmationACK - In the implementation block
@property (nonatomic,readonly) char hasAppName; 
@property (nonatomic,retain) NSString * appName;                           //@synthesize appName=_appName - In the implementation block
-(id)copyWithZone:(NSZone*)arg1 ;
-(char)isEqual:(id)arg1 ;
-(unsigned long long)hash;
-(id)description;
-(unsigned)version;
-(id)dictionaryRepresentation;
-(void)setVersion:(unsigned)arg1 ;
-(void)mergeFrom:(id)arg1 ;
-(char)readFrom:(id)arg1 ;
-(void)writeTo:(id)arg1 ;
-(void)copyTo:(id)arg1 ;
-(unsigned)errorCode;
-(void)setAppName:(NSString *)arg1 ;
-(NSString *)appName;
-(NSData *)keyData;
-(char)hasVersion;
-(void)setHasVersion:(char)arg1 ;
-(void)setErrorCode:(unsigned)arg1 ;
-(void)setHasErrorCode:(char)arg1 ;
-(char)hasErrorCode;
-(char)hasAppName;
-(char)hasKeyData;
-(void)setKeyData:(NSData *)arg1 ;
-(void)setAwdlInfo:(NSData *)arg1 ;
-(char)hasAwdlInfo;
-(void)setUseToken:(char)arg1 ;
-(void)setHasUseToken:(char)arg1 ;
-(char)hasUseToken;
-(void)setAuthPrompt:(char)arg1 ;
-(void)setHasAuthPrompt:(char)arg1 ;
-(char)hasAuthPrompt;
-(void)setSupportsConfirmationACK:(char)arg1 ;
-(void)setHasSupportsConfirmationACK:(char)arg1 ;
-(char)hasSupportsConfirmationACK;
-(NSData *)awdlInfo;
-(char)useToken;
-(char)authPrompt;
-(char)supportsConfirmationACK;
@end

