/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, March 1, 2023 at 11:00:16 PM Israel Standard Time
* Operating System: Version 11.2.3 (Build 20D91)
* Image Source: /usr/libexec/sharingd
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class NSData, NSUUID, RPIdentity;

@interface SDBLEIdentifiedDevice : NSObject {

	NSData* _authTag;
	NSData* _btAddr;
	unsigned long long _discoveryFlags;
	NSUUID* _identifier;
	RPIdentity* _identity;
	unsigned long long _lastUpdateTicks;

}

@property (nonatomic,copy) NSData * authTag;                                  //@synthesize authTag=_authTag - In the implementation block
@property (nonatomic,copy) NSData * btAddr;                                   //@synthesize btAddr=_btAddr - In the implementation block
@property (assign,nonatomic) unsigned long long discoveryFlags;               //@synthesize discoveryFlags=_discoveryFlags - In the implementation block
@property (nonatomic,retain) NSUUID * identifier;                             //@synthesize identifier=_identifier - In the implementation block
@property (nonatomic,retain) RPIdentity * identity;                           //@synthesize identity=_identity - In the implementation block
@property (assign,nonatomic) unsigned long long lastUpdateTicks;              //@synthesize lastUpdateTicks=_lastUpdateTicks - In the implementation block
-(NSUUID *)identifier;
-(void)setIdentifier:(NSUUID *)arg1 ;
-(RPIdentity *)identity;
-(void)setIdentity:(RPIdentity *)arg1 ;
-(unsigned long long)discoveryFlags;
-(void)setDiscoveryFlags:(unsigned long long)arg1 ;
-(NSData *)authTag;
-(void)setAuthTag:(NSData *)arg1 ;
-(void)setBtAddr:(NSData *)arg1 ;
-(void)setLastUpdateTicks:(unsigned long long)arg1 ;
-(unsigned long long)lastUpdateTicks;
-(NSData *)btAddr;
@end

