/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, March 1, 2023 at 11:00:04 PM Israel Standard Time
* Operating System: Version 11.2.3 (Build 20D91)
* Image Source: /usr/libexec/sharingd
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <sharingd/sharingd-Structs.h>
#import <libobjc.A.dylib/SDAirDropClientDelegate.h>
#import <libobjc.A.dylib/WPAWDLDelegate.h>

@protocol OS_xpc_object, SDBonjourBrowserDelegate;
@class NSString, WPAWDL, NSNumber, NSTimer, SDStatusMonitor, NSMutableSet, NSMutableDictionary, NSObject, SDXPCHelperConnection, NSArray;

@interface SDBonjourBrowser : NSObject <SDAirDropClientDelegate, WPAWDLDelegate> {

	char _isAirDrop;
	char _isNetBIOS;
	char _isWorkgroups;
	int _maxServices;
	NSString* _domain;
	WPAWDL* _proximity;
	NSString* _bundleID;
	NSNumber* _isFinder;
	long long _mode;
	unsigned _awdlIndex;
	NSString* _browserID;
	NSString* _sessionID;
	NSTimer* _restartTimer;
	int _transfersInitiated;
	int _transfersCompleted;
	SDStatusMonitor* _monitor;
	DNSServiceRef_tRef _connection;
	double _firstTime;
	double _startTime;
	NSMutableSet* _discoveredPeers;
	NSMutableDictionary* _servers;
	NSObject*<OS_xpc_object> _xpcConnection;
	NSMutableDictionary* _iconCache;
	NSMutableDictionary* _dnsQueries;
	NSMutableDictionary* _serverCache;
	NSMutableDictionary* _airDropRequests;
	CFDictionaryRef _identityQueries;
	SDXPCHelperConnection* _helperConnection;
	NSArray* _types;
	id<SDBonjourBrowserDelegate> _delegate;

}

@property (assign) long long mode; 
@property (nonatomic,copy) NSString * bundleID;                                            //@synthesize bundleID=_bundleID - In the implementation block
@property (assign,nonatomic,__weak) SDXPCHelperConnection * helperConnection;              //@synthesize helperConnection=_helperConnection - In the implementation block
@property (copy) NSString * sessionID;                                                     //@synthesize sessionID=_sessionID - In the implementation block
@property (copy,readonly) NSArray * types;                                                 //@synthesize types=_types - In the implementation block
@property (copy,readonly) NSArray * nodes; 
@property (copy,readonly) NSString * domain;                                               //@synthesize domain=_domain - In the implementation block
@property (__weak) id<SDBonjourBrowserDelegate> delegate;                                  //@synthesize delegate=_delegate - In the implementation block
@property (retain) NSObject*<OS_xpc_object> xpcConnection;                                 //@synthesize xpcConnection=_xpcConnection - In the implementation block
@property (assign) int transfersInitiated;                                                 //@synthesize transfersInitiated=_transfersInitiated - In the implementation block
@property (assign) int transfersCompleted;                                                 //@synthesize transfersCompleted=_transfersCompleted - In the implementation block
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
+(void)updateRPIdentityForAccountID:(id)arg1 withAirDropClientInfo:(id)arg2 ;
-(void)dealloc;
-(NSString *)description;
-(NSString *)domain;
-(void)invalidate;
-(id<SDBonjourBrowserDelegate>)delegate;
-(void)setDelegate:(id<SDBonjourBrowserDelegate>)arg1 ;
-(NSArray *)types;
-(void)setMode:(long long)arg1 ;
-(NSObject*<OS_xpc_object>)xpcConnection;
-(void)setXpcConnection:(NSObject*<OS_xpc_object>)arg1 ;
-(void)setBundleID:(NSString *)arg1 ;
-(NSString *)bundleID;
-(void)start;
-(void)stop;
-(long long)mode;
-(NSString *)sessionID;
-(void)setSessionID:(NSString *)arg1 ;
-(NSArray *)nodes;
-(void)startConnectionlessAdvertisingWithData:(id)arg1 ;
-(void)stopConnectionlessAdvertising;
-(void)clearCache;
-(void)contactsChanged:(id)arg1 ;
-(void)awdlDidUpdateState:(id)arg1 ;
-(void)awdl:(id)arg1 failedToStartAdvertisingWithError:(id)arg2 ;
-(void)awdl:(id)arg1 foundDevice:(id)arg2 rssi:(id)arg3 ;
-(void)removeObservers;
-(SDXPCHelperConnection *)helperConnection;
-(void)setHelperConnection:(SDXPCHelperConnection *)arg1 ;
-(void)addObservers;
-(char)shouldStart;
-(void)lockStatusChanged:(id)arg1 ;
-(void)restartBrowser:(id)arg1 ;
-(void)notifyClient;
-(void)updateBrowserState;
-(void)somethingChanged:(id)arg1 ;
-(void)airDropPublished:(id)arg1 ;
-(void)consoleUserChanged:(id)arg1 ;
-(void)linkStateChanged:(id)arg1 ;
-(void)wirelessPowerChanged:(id)arg1 ;
-(char)thisIsTheFinder;
-(void)advertiseHashes;
-(unsigned)getInterface:(unsigned)arg1 ;
-(void)cancelIdentityQueries;
-(void)cancelAirDropRequests;
-(void)logAirDropSessionInfo;
-(void)removeInvalidNodes:(id)arg1 ;
-(void)updateSecondaryNameForNodes:(id)arg1 ;
-(void)updateServerCacheIfNeeded;
-(void)startRecordQuery:(id)arg1 type:(id)arg2 domain:(id)arg3 recordType:(unsigned short)arg4 interface:(unsigned)arg5 ;
-(id)queryKey:(id)arg1 type:(id)arg2 domain:(id)arg3 recordType:(unsigned short)arg4 ;
-(void)queryRecordTimerCallBack:(id)arg1 ;
-(void)addQueryToDictionary:(DNSServiceRef_t*)arg1 name:(id)arg2 type:(id)arg3 domain:(id)arg4 recordType:(unsigned short)arg5 ;
-(void)cleanupRecordQueryForKey:(id)arg1 ;
-(void)cleanupRecordQuery:(id)arg1 type:(id)arg2 domain:(id)arg3 recordType:(unsigned short)arg4 ;
-(void)ejectDisksIfNeeded:(id)arg1 diskNames:(id)arg2 ;
-(void)cleanupAirDropRequest:(id)arg1 ;
-(id)odiskMountPoints:(id)arg1 ;
-(SFNodeRef)copyNodeForService:(id)arg1 ;
-(id)colorArrayFromEcolor:(id)arg1 icolor:(id)arg2 ;
-(void)cleanupRecordQueryForNetService:(id)arg1 recordType:(unsigned short)arg2 ;
-(void)logAirDropDiscoveryInfoForNode:(SFNodeRef)arg1 ;
-(void)startIdentityQueryForNode:(SFNodeRef)arg1 ;
-(char)preferVibrantIcons;
-(void)startAirDropRequestForNode:(SFNodeRef)arg1 ;
-(void)clearCacheAndNotify;
-(void)handleIdentity:(id)arg1 withQueryID:(id)arg2 emailOrPhone:(id)arg3 error:(id)arg4 ;
-(void)restartAfterDelay:(double)arg1 ;
-(char)validAirDropInterface:(unsigned)arg1 ;
-(void)addService:(id)arg1 type:(id)arg2 domain:(id)arg3 interface:(unsigned)arg4 ;
-(void)removeService:(id)arg1 type:(id)arg2 domain:(id)arg3 ;
-(void)notifyClientIfDone:(unsigned)arg1 ;
-(id)serviceFromServiceName:(id)arg1 ;
-(id)valueForKey:(id)arg1 inTXTRecord:(const void*)arg2 withLength:(unsigned short)arg3 ;
-(void)deviceInfoChanged:(id)arg1 model:(id)arg2 ecolor:(id)arg3 icolor:(id)arg4 osxvers:(id)arg5 ;
-(void)commentChanged:(id)arg1 comment:(id)arg2 ;
-(void)personInfoChanged:(id)arg1 flags:(id)arg2 atag:(id)arg3 cname:(id)arg4 phash:(id)arg5 ehash:(id)arg6 nhash:(id)arg7 ;
-(void)systemInfoChanged:(id)arg1 diskInfo:(CFDictionaryRef)arg2 ;
-(void)processTXTRecordUpdate:(const char*)arg1 rdlen:(unsigned short)arg2 rdata:(const void*)arg3 ;
-(void)airDropClient:(id)arg1 event:(long long)arg2 withResults:(id)arg3 ;
-(id)initWithDomain:(id)arg1 types:(id)arg2 ;
-(char)checkDiscoveryEntitlement;
-(SFNodeRef)copyNodeForName:(id)arg1 ;
-(void)startPictureQuery:(id)arg1 ;
-(void)screenStatusChanged:(id)arg1 ;
-(void)handleBrowseCallBack:(unsigned)arg1 interface:(unsigned)arg2 error:(int)arg3 name:(const char*)arg4 type:(const char*)arg5 domain:(const char*)arg6 ;
-(void)handleQueryCallBack:(unsigned)arg1 error:(int)arg2 fullname:(const char*)arg3 rrtype:(unsigned short)arg4 rdlen:(unsigned short)arg5 rdata:(const void*)arg6 ;
-(int)transfersInitiated;
-(void)setTransfersInitiated:(int)arg1 ;
-(int)transfersCompleted;
-(void)setTransfersCompleted:(int)arg1 ;
@end

