/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, March 1, 2023 at 11:00:11 PM Israel Standard Time
* Operating System: Version 11.2.3 (Build 20D91)
* Image Source: /usr/libexec/sharingd
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <sharingd/sharingd-Structs.h>
#import <libobjc.A.dylib/CRKShareTargetBrowserDelegate.h>

@class NSMutableDictionary, CRKShareTargetBrowser, NSOperationQueue, NSArray, NSString;

@interface SDClassroomBrowser : NSObject <CRKShareTargetBrowserDelegate> {

	int _clientCount;
	NSMutableDictionary* _personIDToShareTarget;
	CRKShareTargetBrowser* _browser;
	NSOperationQueue* _operationsQueue;
	NSArray* _nodes;
	NSString* _clientBundleID;

}

@property (copy) NSArray * nodes;                                   //@synthesize nodes=_nodes - In the implementation block
@property (copy) NSString * clientBundleID;                         //@synthesize clientBundleID=_clientBundleID - In the implementation block
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
+(id)sharedBrowser;
-(id)init;
-(void)start;
-(void)stop;
-(NSArray *)nodes;
-(void)setNodes:(NSArray *)arg1 ;
-(NSString *)clientBundleID;
-(void)setClientBundleID:(NSString *)arg1 ;
-(void)shareTargetBrowser:(id)arg1 didInterruptWithError:(id)arg2 ;
-(void)shareTargetBrowser:(id)arg1 didFindTargets:(id)arg2 ;
-(void)shareTargetBrowser:(id)arg1 didRemoveTargets:(id)arg2 ;
-(void)potentiallyInvalidate;
-(void)browserInvalidated;
-(void)cancelSendingItemsToPersonWithID:(id)arg1 sessionID:(id)arg2 clientBundleID:(id)arg3 ;
-(void)transferConcluded;
-(id)convertAdvancedDescriptionToSimple:(id)arg1 ;
-(id)operationNameForPersonID:(id)arg1 sessionID:(id)arg2 clientBundleID:(id)arg3 ;
-(void)operationStarted:(id)arg1 ;
-(void)operationMadeProgress:(id)arg1 ;
-(void)operationEnded:(id)arg1 ;
-(SFNodeRef)convertShareTargetToNode:(id)arg1 ;
-(void)startSendingItems:(id)arg1 withProperties:(id)arg2 toPersonWithID:(id)arg3 clientBundleID:(id)arg4 airDropClientDelegate:(id)arg5 ;
@end

