/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, March 1, 2023 at 11:00:04 PM Israel Standard Time
* Operating System: Version 11.2.3 (Build 20D91)
* Image Source: /usr/libexec/sharingd
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <libobjc.A.dylib/SFCompanionXPCManagerProtocol.h>
#import <libobjc.A.dylib/SDCompanionStreamDelegate.h>
#import <libobjc.A.dylib/SDUnlockXPCSesssionDelegate.h>
#import <libobjc.A.dylib/SDCompanionPublisherProtocol.h>

@protocol SDConnectionManagerDelegate;
@class NSString, NSUUID, NSXPCConnection, NSMutableArray, SDServiceManager, NSMutableDictionary, SDHotspotAgent;

@interface SDConnectionManager : NSObject <SFCompanionXPCManagerProtocol, SDCompanionStreamDelegate, SDUnlockXPCSesssionDelegate, SDCompanionPublisherProtocol> {

	id<SDConnectionManagerDelegate> _delegate;
	NSString* _bundleID;
	NSUUID* _identifier;
	NSXPCConnection* _xpcConnection;
	NSMutableArray* _companionStreams;
	SDServiceManager* _serviceManager;
	NSMutableDictionary* _deviceStreamMap;
	NSMutableArray* _unlockSessions;
	NSMutableArray* _streamIdentifiers;
	SDHotspotAgent* _hotspotAgent;

}

@property (retain) NSString * bundleID;                                   //@synthesize bundleID=_bundleID - In the implementation block
@property (retain) NSUUID * identifier;                                   //@synthesize identifier=_identifier - In the implementation block
@property (retain) NSXPCConnection * xpcConnection;                       //@synthesize xpcConnection=_xpcConnection - In the implementation block
@property (retain) NSMutableArray * companionStreams;                     //@synthesize companionStreams=_companionStreams - In the implementation block
@property (retain) SDServiceManager * serviceManager;                     //@synthesize serviceManager=_serviceManager - In the implementation block
@property (retain) NSMutableDictionary * deviceStreamMap;                 //@synthesize deviceStreamMap=_deviceStreamMap - In the implementation block
@property (retain) NSMutableArray * unlockSessions;                       //@synthesize unlockSessions=_unlockSessions - In the implementation block
@property (retain) NSMutableArray * streamIdentifiers;                    //@synthesize streamIdentifiers=_streamIdentifiers - In the implementation block
@property (retain) SDHotspotAgent * hotspotAgent;                         //@synthesize hotspotAgent=_hotspotAgent - In the implementation block
@property (__weak) id<SDConnectionManagerDelegate> delegate;              //@synthesize delegate=_delegate - In the implementation block
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
+(id)sharedManager;
-(id<SDConnectionManagerDelegate>)delegate;
-(void)setDelegate:(id<SDConnectionManagerDelegate>)arg1 ;
-(NSUUID *)identifier;
-(NSXPCConnection *)xpcConnection;
-(void)setXpcConnection:(NSXPCConnection *)arg1 ;
-(void)setBundleID:(NSString *)arg1 ;
-(NSString *)bundleID;
-(id)initWithXPCConnection:(id)arg1 ;
-(void)start;
-(void)setIdentifier:(NSUUID *)arg1 ;
-(NSMutableArray *)streamIdentifiers;
-(void)setServiceManager:(SDServiceManager *)arg1 ;
-(SDServiceManager *)serviceManager;
-(void)unlockSessionDidFinish:(id)arg1 ;
-(void)companionStreamClosedStreams:(id)arg1 ;
-(NSMutableArray *)companionStreams;
-(void)setCompanionStreams:(NSMutableArray *)arg1 ;
-(void)cleanUpConnections;
-(NSMutableArray *)unlockSessions;
-(void)createCompanionServiceManagerWithIdentifier:(id)arg1 clientProxy:(id)arg2 reply:(/*^block*/id)arg3 ;
-(void)createStreamsForMessage:(id)arg1 reply:(/*^block*/id)arg2 ;
-(void)createUnlockManagerWithReply:(/*^block*/id)arg1 ;
-(void)appleAccountSignedIn;
-(void)appleAccountSignedOut;
-(void)createHotspotSessionForClientProxy:(id)arg1 reply:(/*^block*/id)arg2 ;
-(NSMutableDictionary *)deviceStreamMap;
-(void)setDeviceStreamMap:(NSMutableDictionary *)arg1 ;
-(void)setUnlockSessions:(NSMutableArray *)arg1 ;
-(void)setStreamIdentifiers:(NSMutableArray *)arg1 ;
-(SDHotspotAgent *)hotspotAgent;
-(void)setHotspotAgent:(SDHotspotAgent *)arg1 ;
@end

