/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, March 1, 2023 at 11:00:11 PM Israel Standard Time
* Operating System: Version 11.2.3 (Build 20D91)
* Image Source: /usr/libexec/sharingd
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <libobjc.A.dylib/NSStreamDelegate.h>
#import <libobjc.A.dylib/NSNetServiceBrowserDelegate.h>
#import <libobjc.A.dylib/SDStreamHandlerDelegate.h>

@protocol SDCompanionStreamDelegate, OS_dispatch_queue;
@class NSFileHandle, NSString, SDStreamHandler, NSData, NSNetServiceBrowser, NSInputStream, NSOutputStream, NSObject, NSMutableData;

@interface SDCompanionStream : NSObject <NSStreamDelegate, NSNetServiceBrowserDelegate, SDStreamHandlerDelegate> {

	char _initiator;
	char _shouldStop;
	char _clientSent;
	char _clientReceived;
	char _networkBufferSpaceAvailable;
	NSFileHandle* _fileHandle;
	id<SDCompanionStreamDelegate> _delegate;
	NSString* _identifier;
	SDStreamHandler* _streamHandler;
	NSData* _authorData;
	NSNetServiceBrowser* _netServiceBrowser;
	NSInputStream* _clientInputStream;
	NSOutputStream* _clientOutputStream;
	NSObject*<OS_dispatch_queue> _writeQueue;
	NSMutableData* _networkStreamData;
	NSObject*<OS_dispatch_queue> _readQueue;
	NSMutableData* _clientStreamData;
	long long _readFromClient;
	long long _wroteToClient;
	/*^block*/id _streamsRequestHandler;

}

@property (retain) SDStreamHandler * streamHandler;                      //@synthesize streamHandler=_streamHandler - In the implementation block
@property (retain) NSData * authorData;                                  //@synthesize authorData=_authorData - In the implementation block
@property (assign) char initiator;                                       //@synthesize initiator=_initiator - In the implementation block
@property (assign) char shouldStop;                                      //@synthesize shouldStop=_shouldStop - In the implementation block
@property (assign) char clientSent;                                      //@synthesize clientSent=_clientSent - In the implementation block
@property (assign) char clientReceived;                                  //@synthesize clientReceived=_clientReceived - In the implementation block
@property (assign) char networkBufferSpaceAvailable;                     //@synthesize networkBufferSpaceAvailable=_networkBufferSpaceAvailable - In the implementation block
@property (retain) NSNetServiceBrowser * netServiceBrowser;              //@synthesize netServiceBrowser=_netServiceBrowser - In the implementation block
@property (readonly) NSFileHandle * fileHandle;                          //@synthesize fileHandle=_fileHandle - In the implementation block
@property (retain) NSInputStream * clientInputStream;                    //@synthesize clientInputStream=_clientInputStream - In the implementation block
@property (retain) NSOutputStream * clientOutputStream;                  //@synthesize clientOutputStream=_clientOutputStream - In the implementation block
@property (retain) NSObject*<OS_dispatch_queue> writeQueue;              //@synthesize writeQueue=_writeQueue - In the implementation block
@property (retain) NSMutableData * networkStreamData;                    //@synthesize networkStreamData=_networkStreamData - In the implementation block
@property (retain) NSObject*<OS_dispatch_queue> readQueue;               //@synthesize readQueue=_readQueue - In the implementation block
@property (retain) NSMutableData * clientStreamData;                     //@synthesize clientStreamData=_clientStreamData - In the implementation block
@property (assign) long long readFromClient;                             //@synthesize readFromClient=_readFromClient - In the implementation block
@property (assign) long long wroteToClient;                              //@synthesize wroteToClient=_wroteToClient - In the implementation block
@property (copy) id streamsRequestHandler;                               //@synthesize streamsRequestHandler=_streamsRequestHandler - In the implementation block
@property (__weak) id<SDCompanionStreamDelegate> delegate;               //@synthesize delegate=_delegate - In the implementation block
@property (retain) NSString * identifier;                                //@synthesize identifier=_identifier - In the implementation block
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(void)dealloc;
-(id<SDCompanionStreamDelegate>)delegate;
-(void)setDelegate:(id<SDCompanionStreamDelegate>)arg1 ;
-(void)stream:(id)arg1 handleEvent:(unsigned long long)arg2 ;
-(NSString *)identifier;
-(void)setBundleID:(id)arg1 ;
-(void)start;
-(void)setIdentifier:(NSString *)arg1 ;
-(void)stop;
-(NSFileHandle *)fileHandle;
-(char)shouldStop;
-(void)setShouldStop:(char)arg1 ;
-(NSObject*<OS_dispatch_queue>)writeQueue;
-(void)setWriteQueue:(NSObject*<OS_dispatch_queue>)arg1 ;
-(void)setInitiator:(char)arg1 ;
-(char)initiator;
-(void)netServiceBrowser:(id)arg1 didFindService:(id)arg2 moreComing:(char)arg3 ;
-(NSObject*<OS_dispatch_queue>)readQueue;
-(NSNetServiceBrowser *)netServiceBrowser;
-(void)setReadQueue:(NSObject*<OS_dispatch_queue>)arg1 ;
-(void)setNetServiceBrowser:(NSNetServiceBrowser *)arg1 ;
-(id)initWithAuthorData:(id)arg1 streamHandler:(id)arg2 ;
-(void)getStreamsWithCompletionHandler:(/*^block*/id)arg1 ;
-(id)initWithStreamHandler:(id)arg1 ;
-(void)stopIfReady;
-(void)streamHandlerDidClose:(id)arg1 withError:(id)arg2 ;
-(void)streamHandler:(id)arg1 bufferSpaceChanged:(char)arg2 ;
-(void)streamHandler:(id)arg1 didReceiveStreamData:(id)arg2 ;
-(void)streamHandler:(id)arg1 didReceiveMessage:(id)arg2 ;
-(void)sendInitialRequest;
-(void)startBrowser;
-(void)notifyStreamRequestWithError:(id)arg1 ;
-(void)switchToStreaming;
-(void)writeNetworkStream;
-(int)setBufferSize:(int)arg1 socket:(int)arg2 ;
-(void)handleStreamRequest:(id)arg1 ;
-(void)handleStreamResponse:(id)arg1 ;
-(void)sendInitialResponse:(char)arg1 ;
-(char)networkBufferSpaceAvailable;
-(void)setNetworkBufferSpaceAvailable:(char)arg1 ;
-(void)readClientStream;
-(void)writeClientStream;
-(void)handleOpenedStream;
-(void)logClientReceived;
-(void)logClientSent;
-(SDStreamHandler *)streamHandler;
-(void)setStreamHandler:(SDStreamHandler *)arg1 ;
-(NSData *)authorData;
-(void)setAuthorData:(NSData *)arg1 ;
-(char)clientSent;
-(void)setClientSent:(char)arg1 ;
-(char)clientReceived;
-(void)setClientReceived:(char)arg1 ;
-(NSInputStream *)clientInputStream;
-(void)setClientInputStream:(NSInputStream *)arg1 ;
-(NSOutputStream *)clientOutputStream;
-(void)setClientOutputStream:(NSOutputStream *)arg1 ;
-(NSMutableData *)networkStreamData;
-(void)setNetworkStreamData:(NSMutableData *)arg1 ;
-(NSMutableData *)clientStreamData;
-(void)setClientStreamData:(NSMutableData *)arg1 ;
-(long long)readFromClient;
-(void)setReadFromClient:(long long)arg1 ;
-(long long)wroteToClient;
-(void)setWroteToClient:(long long)arg1 ;
-(id)streamsRequestHandler;
-(void)setStreamsRequestHandler:(id)arg1 ;
@end

