/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, March 1, 2023 at 11:00:03 PM Israel Standard Time
* Operating System: Version 11.2.3 (Build 20D91)
* Image Source: /usr/libexec/sharingd
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol SDCompanionPublisherProtocol <NSObject>
@optional
-(void)manager:(id)arg1 connectedToService:(id)arg2 withFileHandle:(id)arg3 acceptHandler:(/*^block*/id)arg4;
-(void)publisher:(id)arg1 didConnectToService:(id)arg2 withStreamHandler:(id)arg3;
-(void)publisher:(id)arg1 companionStreamForService:(id)arg2 streamHandler:(id)arg3;

@end

