/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, March 1, 2023 at 11:00:07 PM Israel Standard Time
* Operating System: Version 11.2.3 (Build 20D91)
* Image Source: /usr/libexec/sharingd
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <sharingd/sharingd-Structs.h>
#import <libobjc.A.dylib/NSNetServiceBrowserDelegate.h>

@protocol OS_dispatch_source;
@class NSMutableSet, NSObject, NSNetServiceBrowser, NSString;

@interface SDDomainBrowser : NSObject <NSNetServiceBrowserDelegate> {

	int _clientCount;
	char _sendNotification;
	NSMutableSet* _domains;
	NSObject*<OS_dispatch_source> _timer;
	CFDictionaryRef _domainTree;
	NSNetServiceBrowser* _domainBrowser;

}

@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
+(id)sharedBrowser;
-(id)init;
-(void)start;
-(void)stop;
-(void)restart;
-(void)postNotification;
-(void)netServiceBrowser:(id)arg1 didNotSearch:(id)arg2 ;
-(void)netServiceBrowser:(id)arg1 didFindDomain:(id)arg2 moreComing:(char)arg3 ;
-(void)netServiceBrowser:(id)arg1 didRemoveDomain:(id)arg2 moreComing:(char)arg3 ;
-(void)statusChanged:(id)arg1 ;
-(void)browseAfterDelay:(double)arg1 ;
-(void)scheduleBrowser;
-(id)displayNameForDomain:(id)arg1 ;
-(void)parseDomain:(id)arg1 ;
-(void)buildNodes;
-(id)childrenForNode:(SFNodeRef)arg1 ;
@end

