/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, March 1, 2023 at 11:00:01 PM Israel Standard Time
* Operating System: Version 11.2.3 (Build 20D91)
* Image Source: /usr/libexec/sharingd
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <sharingd/sharingd-Structs.h>
#import <libobjc.A.dylib/SDHotspotManagerDelegate.h>
#import <libobjc.A.dylib/IDSServiceDelegate.h>
#import <libobjc.A.dylib/SFRemoteHotspotProtocol.h>
#import <libobjc.A.dylib/SFRemoteHotspotClient.h>

@protocol OS_dispatch_source, OS_dispatch_queue;
@class NSObject, NSMutableArray, NSMutableDictionary, RPCompanionLinkClient, SFDeviceDiscovery, NSArray, NSDictionary, IDSService, SDHotspotBrowser, SDHotspotManager, NSNumber, SDStatusMonitor, CUSystemMonitor, NSString;

@interface SDHotspotAgent : NSObject <SDHotspotManagerDelegate, IDSServiceDelegate, SFRemoteHotspotProtocol, SFRemoteHotspotClient> {

	double _advertisementTime;
	NSObject*<OS_dispatch_source> _advertisementTimer;
	char _browserActive;
	NSMutableArray* _browserBundleIDs;
	char _browserClientsInactive;
	NSMutableDictionary* _clientProxyMap;
	RPCompanionLinkClient* _companionLinkClient;
	RPCompanionLinkClient* _companionLinkReceiver;
	SFDeviceDiscovery* _deviceDiscovery;
	NSMutableDictionary* _devices;
	NSMutableDictionary* _devicesCombined;
	NSArray* _devicesLegacy;
	NSObject*<OS_dispatch_queue> _dispatchQueue;
	long long _familyCount;
	NSArray* _idsDeviceArray;
	NSDictionary* _idsDeviceBTDictionary;
	long long _idsLegacyClientDeviceCount;
	long long _idsLegacyHostDeviceCount;
	long long _idsTetheringClientDeviceCount;
	long long _idsTetheringHostDeviceCount;
	IDSService* _idsService;
	char _invalidateCalled;
	char _invalidateDone;
	SDHotspotBrowser* _hotspotBrowser;
	SDHotspotManager* _hotspotManager;
	char _prefAdvertisingDisabled;
	int _prefBatteryLevelOverride;
	char _prefChargingOverrideDisabled;
	char _prefCompanionDiscoveryEnabled;
	NSNumber* _prefFamilyEnabledOverride;
	char _prefLegacyDisabled;
	NSNumber* _prefNetworkTypeOverride;
	char _prefRapportDisabled;
	unsigned char _prefSignalStrengthOverride;
	SDStatusMonitor* _statusMonitor;
	char _systemMonitorActivated;
	CUSystemMonitor* _systemMonitor;
	NSMutableDictionary* _userAlerts;

}

@property (nonatomic,copy,readonly) NSString * hotspotName; 
@property (nonatomic,copy,readonly) NSString * hotspotPassword; 
@property (nonatomic,readonly) char p2pAllowed; 
@property (getter=isTetheringInUse,nonatomic,readonly) char tetheringInUse; 
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
+(id)sharedAgent;
-(NSString *)description;
-(id)init;
-(void)_activate;
-(void)invalidate;
-(void)_invalidate;
-(void)_update;
-(void)activate;
-(void)_invalidated;
-(void)update;
-(void)_prefsChanged:(char)arg1 ;
-(void)service:(id)arg1 devicesChanged:(id)arg2 ;
-(void)_advertiserEnsureStopped;
-(void)stopBrowsing;
-(void)startBrowsing;
-(void)_discoveryDeviceFound:(id)arg1 ;
-(void)_discoveryDeviceLost:(id)arg1 ;
-(void)_idsEnsureStarted;
-(void)_sysMonitorEnsureStarted;
-(void)_companionLinkEnsureStopped;
-(void)_idsEnsureStopped;
-(void)_legacyBrowserEnsureStopped;
-(void)_sysMonitorEnsureStopped;
-(char)_advertiserShouldAdvertise;
-(void)_advertiserUpdate;
-(char)_companionLinkShouldStart;
-(void)_companionLinkEnsureStarted;
-(char)_legacyBrowserShouldStart;
-(void)_legacyBrowserEnsureStarted;
-(void)_addClientID:(id)arg1 bundleID:(id)arg2 proxy:(id)arg3 ;
-(void)_removeClientID:(id)arg1 ;
-(void)_startBrowsingForClientID:(id)arg1 ;
-(id)_appMonitorAppList;
-(void)_appMonitorEnsureStarted;
-(void)_discoveryUpdateCombined:(char)arg1 ;
-(void)stopBrowsingForClientID:(id)arg1 ;
-(void)_stopBrowsingForClientID:(id)arg1 ;
-(void)_appMonitorUpdate;
-(void)_appMonitorEnsureStopped;
-(void)_enableHotspotForDevice:(id)arg1 withCompletionHandler:(/*^block*/id)arg2 ;
-(LogCategory*)_logCategoryCreateWithLabel:(id)arg1 sessionID:(unsigned)arg2 ;
-(char)_sysMonitorAccountIsHSA2;
-(char)_sysMonitorManateeIsAvailable;
-(void)_companionLinkActivateWithRequest:(id)arg1 ;
-(void)enableHotspotForDevice:(id)arg1 withCompletionHandler:(/*^block*/id)arg2 ;
-(char)_companionLinkFamilySupported;
-(void)_discoveryDeviceChanged:(id)arg1 ;
-(long long)_idsTetheringHostDeviceCount;
-(long long)_sysMonitorFamilyCount;
-(id)_idsDeviceArray;
-(void)_companionLinkActivatedRequest:(id)arg1 ;
-(void)_companionLinkHandleResponse:(id)arg1 request:(id)arg2 error:(id)arg3 ;
-(id)_sysMonitorFamilyMemberForAltDSID:(id)arg1 ;
-(id)_sysMonitorFamilyMemberForAppleID:(id)arg1 ;
-(void)_companionLinkStartTetheringWithResponse:(/*^block*/id)arg1 logCategory:(LogCategory*)arg2 canConnectOn5GHz:(char)arg3 ;
-(void)_userAlertForMember:(id)arg1 logCategory:(LogCategory*)arg2 completion:(/*^block*/id)arg3 ;
-(long long)_discoveryGroupForDevice:(id)arg1 ;
-(void)updatedFoundDeviceList:(id)arg1 ;
-(id)_idsDeviceIDForBluetoothID:(id)arg1 ;
-(void)_discoveryUpdateClients;
-(void)_discoveryUpdateLegacyDeviceList:(id)arg1 ;
-(char)_legacyBrowserShouldScan;
-(char)_legacyBrowserShouldBrowse;
-(long long)_idsLegacyHostDeviceCount;
-(long long)_idsLegacyClientDeviceCount;
-(void)_legacyBrowswerUpdateHSA2State;
-(void)hotspotManagerTetheringSupportChanged:(id)arg1 ;
-(void)prefsChanged;
-(unsigned char)_nearbyNetworkTypeForHotspotNetworkType:(unsigned char)arg1 ;
-(void)addClientID:(id)arg1 proxy:(id)arg2 ;
-(void)removeClientID:(id)arg1 ;
-(void)_companionLinkHandleRequest:(id)arg1 options:(id)arg2 responseHandler:(/*^block*/id)arg3 ;
-(long long)_idsTetheringClientDeviceCount;
-(void)disableTethering;
-(char)isTetheringInUse;
-(NSString *)hotspotName;
-(NSString *)hotspotPassword;
-(char)p2pAllowed;
@end

