/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, March 1, 2023 at 11:00:01 PM Israel Standard Time
* Operating System: Version 11.2.3 (Build 20D91)
* Image Source: /usr/libexec/sharingd
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


#import <sharingd/sharingd-Structs.h>
@class RPCompanionLinkClient, SFRemoteHotspotDevice;

@interface SDHotspotRequest : NSObject {

	unsigned _sessionID;
	RPCompanionLinkClient* _companionLinkClient;
	SFRemoteHotspotDevice* _hotspotDevice;
	/*^block*/id _hotspotInfoHandler;
	LogCategory* _logCategory;

}

@property (nonatomic,retain) RPCompanionLinkClient * companionLinkClient;              //@synthesize companionLinkClient=_companionLinkClient - In the implementation block
@property (nonatomic,retain) SFRemoteHotspotDevice * hotspotDevice;                    //@synthesize hotspotDevice=_hotspotDevice - In the implementation block
@property (nonatomic,copy) id hotspotInfoHandler;                                      //@synthesize hotspotInfoHandler=_hotspotInfoHandler - In the implementation block
@property (assign,nonatomic) LogCategory* logCategory;                                 //@synthesize logCategory=_logCategory - In the implementation block
@property (assign,nonatomic) unsigned sessionID;                                       //@synthesize sessionID=_sessionID - In the implementation block
-(void)dealloc;
-(unsigned)sessionID;
-(void)setSessionID:(unsigned)arg1 ;
-(LogCategory*)logCategory;
-(RPCompanionLinkClient *)companionLinkClient;
-(void)setLogCategory:(LogCategory*)arg1 ;
-(void)setCompanionLinkClient:(RPCompanionLinkClient *)arg1 ;
-(SFRemoteHotspotDevice *)hotspotDevice;
-(void)setHotspotDevice:(SFRemoteHotspotDevice *)arg1 ;
-(id)hotspotInfoHandler;
-(void)setHotspotInfoHandler:(id)arg1 ;
@end

