/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, March 1, 2023 at 11:00:08 PM Israel Standard Time
* Operating System: Version 11.2.3 (Build 20D91)
* Image Source: /usr/libexec/sharingd
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


#import <sharingd/sharingd-Structs.h>
@class NSDictionary, NSArray;

@interface SDManagedBrowser : NSObject {

	int _clientCount;
	char _sendNotification;
	NSDictionary* _servers;
	OpaqueLSSharedFileListRefRef _managed;

}

@property (copy,readonly) NSArray * nodes; 
+(id)sharedBrowser;
-(id)init;
-(void)start;
-(void)stop;
-(NSArray *)nodes;
-(void)setServers:(id)arg1 ;
-(void)buildNodesAndNotify;
@end

