/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, March 1, 2023 at 11:00:09 PM Israel Standard Time
* Operating System: Version 11.2.3 (Build 20D91)
* Image Source: /usr/libexec/sharingd
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol SDNetworkEjecterDelegate;
#import <sharingd/sharingd-Structs.h>
@class NSNumber, NSString;

@interface SDNetworkEjecter : NSObject {

	SFNodeRef _node;
	int _mountedCount;
	int _ejectedCount;
	NSNumber* _flags;
	NSString* _protocol;
	id<SDNetworkEjecterDelegate> _delegate;

}

@property (copy) NSNumber * flags;                                     //@synthesize flags=_flags - In the implementation block
@property (copy) NSString * protocol;                                  //@synthesize protocol=_protocol - In the implementation block
@property (__weak) id<SDNetworkEjecterDelegate> delegate;              //@synthesize delegate=_delegate - In the implementation block
-(NSNumber *)flags;
-(void)dealloc;
-(id<SDNetworkEjecterDelegate>)delegate;
-(void)setDelegate:(id<SDNetworkEjecterDelegate>)arg1 ;
-(int)start;
-(NSString *)protocol;
-(void)stop;
-(void)setProtocol:(NSString *)arg1 ;
-(void)setFlags:(NSNumber *)arg1 ;
-(void)eject;
-(id)initWithNode:(SFNodeRef)arg1 ;
-(void)notifyClientAboutEject:(int)arg1 ;
-(void)ejectMountPoints:(id)arg1 useAssistant:(char)arg2 ;
@end

