/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, March 1, 2023 at 11:00:10 PM Israel Standard Time
* Operating System: Version 11.2.3 (Build 20D91)
* Image Source: /usr/libexec/sharingd
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <sharingd/sharingd-Structs.h>
#import <libobjc.A.dylib/SDBonjourResolverDelegate.h>

@protocol SDNetworkResolverDelegate;
@class SDBonjourResolver, NSNumber, NSString;

@interface SDNetworkResolver : NSObject <SDBonjourResolverDelegate> {

	SFNodeRef _node;
	SDBonjourResolver* _resolver;
	void* _session;
	NSNumber* _flags;
	NSString* _protocol;
	id<SDNetworkResolverDelegate> _delegate;

}

@property (copy) NSNumber * flags;                                      //@synthesize flags=_flags - In the implementation block
@property (copy) NSString * protocol;                                   //@synthesize protocol=_protocol - In the implementation block
@property (__weak) id<SDNetworkResolverDelegate> delegate;              //@synthesize delegate=_delegate - In the implementation block
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(NSNumber *)flags;
-(void)dealloc;
-(id<SDNetworkResolverDelegate>)delegate;
-(void)setDelegate:(id<SDNetworkResolverDelegate>)arg1 ;
-(int)start;
-(NSString *)protocol;
-(void)stop;
-(void)setProtocol:(NSString *)arg1 ;
-(void)setFlags:(NSNumber *)arg1 ;
-(void)mount;
-(id)initWithNode:(SFNodeRef)arg1 ;
-(void)bonjourResolverDidChange:(id)arg1 ;
-(int)mountDiskImage;
-(void)notifyClientAboutResolve:(int)arg1 ;
-(id)diskImageURL;
-(id)diskImageOptions;
-(void)handleDiskImageResults:(CFDictionaryRef)arg1 ;
-(char)isAirPortDisk;
-(void)mountDiskImageAsync;
-(void)handleConnectToServerCallBack:(CFDictionaryRef)arg1 withError:(int)arg2 ;
-(void)handleMountCallBack:(void*)arg1 mountInfo:(CFDictionaryRef)arg2 error:(int)arg3 ;
@end

