/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, March 1, 2023 at 11:00:03 PM Israel Standard Time
* Operating System: Version 11.2.3 (Build 20D91)
* Image Source: /usr/libexec/sharingd
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <libobjc.A.dylib/UNUserNotificationCenterDelegate.h>

@protocol OS_dispatch_queue;
@class NSMutableDictionary, UNUserNotificationCenter, NSObject, NSSet, NSString;

@interface SDNotificationManager : NSObject <UNUserNotificationCenterDelegate> {

	char _activated;
	NSMutableDictionary* _autoFillRequests;
	UNUserNotificationCenter* _homePodNotifCenter;
	UNUserNotificationCenter* _homePodMiniNotificationCenter;
	char _homePodNotifGranted;
	NSMutableDictionary* _homePodRequests;
	char _invalidated;
	NSMutableDictionary* _tvKeyboardRequests;
	UNUserNotificationCenter* _tvNotifCenter;
	char _tvNotifGranted;
	NSMutableDictionary* _watchKeyboardRequests;
	UNUserNotificationCenter* _watchNotifCenter;
	char _watchNotifGranted;
	NSObject*<OS_dispatch_queue> _dispatchQueue;

}

@property (nonatomic,retain) NSObject*<OS_dispatch_queue> dispatchQueue;              //@synthesize dispatchQueue=_dispatchQueue - In the implementation block
@property (nonatomic,copy,readonly) NSSet * activeTVAutoFillPrompts; 
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
+(id)sharedManager;
-(NSString *)description;
-(id)init;
-(void)_activate;
-(void)invalidate;
-(void)_invalidate;
-(NSObject*<OS_dispatch_queue>)dispatchQueue;
-(void)_update;
-(void)activate;
-(void)userNotificationCenter:(id)arg1 didReceiveNotificationResponse:(id)arg2 withCompletionHandler:(/*^block*/id)arg3 ;
-(void)setDispatchQueue:(NSObject*<OS_dispatch_queue>)arg1 ;
-(void)prefsChanged;
-(void)_homePodEnsureStarted:(char)arg1 completion:(/*^block*/id)arg2 ;
-(void)_tvEnsureStarted:(char)arg1 completion:(/*^block*/id)arg2 ;
-(void)_watchEnsureStarted:(char)arg1 completion:(/*^block*/id)arg2 ;
-(void)_addRequestWithID:(id)arg1 content:(id)arg2 type:(unsigned)arg3 isHomePodMini:(char)arg4 ;
-(void)tvAutoFillRemove:(id)arg1 ;
-(void)tvKeyboardRemove:(id)arg1 ;
-(void)_tvKeyboardPostIfNeeded:(id)arg1 backgroundAction:(char)arg2 ;
-(id)tvKeyboardContentForDevice:(id)arg1 backgroundAction:(char)arg2 ;
-(void)_addRequestWithID:(id)arg1 content:(id)arg2 type:(unsigned)arg3 ;
-(void)_tvKeyboardRemove:(id)arg1 ;
-(void)_tvKeyboardRemoveAll;
-(void)_tvKeyboardUpdate:(id)arg1 info:(id)arg2 ;
-(void)_tvKeyboardUpdate:(id)arg1 rtiData:(id)arg2 ;
-(void)_tvAutoFillPostIfNeeded:(id)arg1 ;
-(void)_tvAutoFillRemove:(id)arg1 ;
-(void)_tvAutoFillRemoveAll;
-(void)_watchKeyboardPostIfNeeded:(id)arg1 ;
-(id)watchKeyboardContentForDevice:(id)arg1 ;
-(void)_watchKeyboardRemove:(id)arg1 ;
-(void)_watchKeyboardRemoveAll;
-(void)_watchKeyboardUpdate:(id)arg1 rtiData:(id)arg2 ;
-(id)attachmentFromURL:(id)arg1 ;
-(void)_homePodHandoffPostIfNeeded:(id)arg1 info:(id)arg2 ;
-(id)homePodHandoffContentForDevice:(id)arg1 info:(id)arg2 ;
-(void)_homePodHandoffRemove:(id)arg1 reason:(long long)arg2 ;
-(void)_homePodHandoffRemoveAll;
-(void)_homePodHandoffUpdateIfNeeded:(id)arg1 info:(id)arg2 ;
-(void)homePodHandoffUpdateIfNeeded:(id)arg1 info:(id)arg2 ;
-(void)homePodHandoffRemove:(id)arg1 reason:(long long)arg2 ;
-(void)_homePodHandleResponse:(id)arg1 completion:(/*^block*/id)arg2 ;
-(void)_tvHandleResponse:(id)arg1 completion:(/*^block*/id)arg2 ;
-(void)_watchHandleResponse:(id)arg1 completion:(/*^block*/id)arg2 ;
-(void)testAutofillPost;
-(void)testAutoFillRemove;
-(void)testHandoffPost;
-(void)testKeyboardPost;
-(void)testKeyboardPostAutoFill;
-(void)testKeyboardRemove;
-(void)testKeyboardUpdate;
-(void)testWatchKeyboard;
-(void)testWatchKeyboardAutoFill;
-(void)testPostBasic;
-(void)tvAutoFillPostIfNeeded:(id)arg1 ;
-(void)homePodHandoffPostIfNeeded:(id)arg1 info:(id)arg2 ;
-(void)tvKeyboardPostIfNeeded:(id)arg1 backgroundAction:(char)arg2 ;
-(void)tvKeyboardUpdate:(id)arg1 info:(id)arg2 ;
-(void)watchKeyboardPostIfNeeded:(id)arg1 ;
-(void)tvKeyboardRemoveAll;
-(void)tvKeyboardUpdate:(id)arg1 rtiData:(id)arg2 ;
-(NSSet *)activeTVAutoFillPrompts;
-(void)tvAutoFillRemoveAll;
-(void)watchKeyboardRemove:(id)arg1 ;
-(void)watchKeyboardRemoveAll;
-(void)watchKeyboardUpdate:(id)arg1 info:(id)arg2 ;
-(void)_watchKeyboardUpdate:(id)arg1 info:(id)arg2 ;
-(void)watchKeyboardUpdate:(id)arg1 rtiData:(id)arg2 ;
-(void)homePodHandoffRemoveAll;
-(void)testPost:(id)arg1 ;
@end

