/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, March 1, 2023 at 11:00:07 PM Israel Standard Time
* Operating System: Version 11.2.3 (Build 20D91)
* Image Source: /usr/libexec/sharingd
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol OS_dispatch_source, OS_dispatch_queue;
@class SFDeviceDiscovery, NSMutableDictionary, NSObject, SFProxHandoffService, CUCoalescer, RPCompanionLinkClient, SFNotificationProxy, NSMutableSet, SDStatusMonitor, CUSystemMonitor, SFCombinedDevice;

@interface SDProxHandoffAgent : NSObject {

	SFDeviceDiscovery* _bleActionDiscovery;
	NSMutableDictionary* _bleActionDevices;
	NSObject*<OS_dispatch_source> _bleActionScanTimer;
	char _bleActionScanTimedOut;
	SFProxHandoffService* _bleActionService;
	NSObject*<OS_dispatch_source> _bleActionServiceTimer;
	SFDeviceDiscovery* _bleInfoDiscovery;
	NSMutableDictionary* _bleInfoDevices;
	CUCoalescer* _bleMapCoalescer;
	NSMutableDictionary* _bleUnmapped;
	char _candidateNearby;
	char _clientShouldAdvertise;
	RPCompanionLinkClient* _clinkClient;
	NSObject*<OS_dispatch_source> _delayTimer;
	NSMutableDictionary* _mappedDevices;
	char _motionMonitorStarted;
	SFNotificationProxy* _notificationProxy;
	NSMutableSet* _proxClients;
	char _stationary;
	SDStatusMonitor* _statusMonitor;
	NSMutableSet* _suppressedDeviceIDs;
	CUSystemMonitor* _systemMonitor;
	NSObject*<OS_dispatch_source> _transferTimer;
	SFCombinedDevice* _uiDevice;
	char _unansweredCall;
	char _userOnCall;
	double _prefBLEActionScanSecs;
	char _prefEnabled;
	char _prefForceShouldAdvertise;
	char _prefForceStationary;
	char _prefForceOnCall;
	char _prefHighNormal;
	char _prefIgnoreMediumThrottle;
	char _prefMediumBubbleEnabled;
	unsigned long long _prefMediumBubbleLastTicks;
	double _prefRetriggerSecs;
	double _prefTransferSecs;
	unsigned long long _prefThrottleEventCount;
	unsigned long long _prefThrottleEventMax;
	char _preventNotifications;
	NSObject*<OS_dispatch_queue> _dispatchQueue;

}

@property (nonatomic,retain) NSObject*<OS_dispatch_queue> dispatchQueue;              //@synthesize dispatchQueue=_dispatchQueue - In the implementation block
@property (assign,nonatomic) char preventNotifications;                               //@synthesize preventNotifications=_preventNotifications - In the implementation block
+(id)sharedAgent;
-(id)description;
-(id)init;
-(void)invalidate;
-(void)_invalidate;
-(NSObject*<OS_dispatch_queue>)dispatchQueue;
-(void)_update;
-(void)activate;
-(void)setDispatchQueue:(NSObject*<OS_dispatch_queue>)arg1 ;
-(void)_run;
-(id)_routes;
-(id)displayNameForContact:(id)arg1 ;
-(void)prefsChanged;
-(void)notificationDidDismiss:(id)arg1 reason:(long long)arg2 ;
-(void)userDidTapNotification:(id)arg1 ;
-(char)_systemCanTrigger;
-(void)_bleActionDiscoveryEnsureStopped;
-(void)_bleInfoDiscoveryEnsureStopped;
-(void)_commonEnsureStopped;
-(void)_clinkEnsureStopped;
-(void)_serviceEnsureStopped;
-(void)_commonShouldAdvertiseChanged;
-(void)_commonCallCountChanged;
-(void)_motionEnsureStopped;
-(void)_commonEnsureStarted;
-(char)_clinkShouldStart;
-(void)_clinkEnsureStarted;
-(char)_bleActionDiscoveryShouldStart;
-(void)_bleActionDiscoveryEnsureStarted;
-(char)_bleInfoDiscoveryShouldStart;
-(void)_bleInfoDiscoveryEnsureStarted;
-(char)_motionShouldStart;
-(void)_motionEnsureStarted;
-(char)_serviceShouldStart;
-(void)_serviceEnsureStarted;
-(void)_commonScreenStateChanged;
-(void)_bleUpdateMappingAndNearbyCoalesced;
-(void)commonSystemUIChanged;
-(void)_proxiedNotificationDidDismiss:(id)arg1 reason:(long long)arg2 ;
-(void)_proxiedNotificationWasTapped:(id)arg1 ;
-(void)_hapticsEnsureStopped;
-(void)_uiStopIfNeeded:(id)arg1 reason:(long long)arg2 ;
-(void)_resetAllStates;
-(void)_bleUpdateMappingReset;
-(id)_combinedDevicePending;
-(void)_runNotificationPending;
-(void)_runNotificationPendingContent;
-(void)_runNotificationReady;
-(void)_runNotificationPresented;
-(void)_runNotificationDismissed;
-(void)_runTransferInProgress;
-(void)_runTransferPending;
-(void)_runTransferReady;
-(void)_runTransferPendingDismiss;
-(void)_runTransferDone;
-(char)_runStateVerify:(int)arg1 device:(id)arg2 ;
-(void)_combinedDevicePrepareForCallTransferTrigger:(id)arg1 ;
-(void)_proximityClientDeviceWillTrigger:(id)arg1 ;
-(char)_shouldMediumPromptWithInfo:(id)arg1 ;
-(void)_scheduleRunAfter:(double)arg1 ;
-(void)_throttleMediumSetTicks:(unsigned long long)arg1 ;
-(void)_hapticsFireNotificationSuccess;
-(void)_throttleEventDidOccur;
-(void)_runCallHandoffStart:(id)arg1 ;
-(void)_proximityClientDeviceEnteredImmediate:(id)arg1 ;
-(void)_proximityClientDeviceExitedImmediate:(id)arg1 ;
-(void)_runCallHandoffHandleResponse:(id)arg1 error:(id)arg2 ;
-(void)_runCallHandoffStartDelayTimer;
-(void)_runCallHandoffHandleDelayTimerFired;
-(void)_uiDismissWhenReady:(id)arg1 reason:(long long)arg2 ;
-(void)_bleActionDeviceFound:(id)arg1 ;
-(void)_bleActionDeviceLost:(id)arg1 ;
-(void)_bleActionDeviceChanged:(id)arg1 ;
-(void)_bleActionScanTimerActivate;
-(void)_bleActionScanTimerInvalidate;
-(void)_bleActionDeviceFoundCandidate:(id)arg1 ;
-(id)_bleUpdateMappingWithDevice:(id)arg1 ;
-(char)_combinedDeviceIsSuppressed:(id)arg1 ;
-(void)_proximityClientDeviceDidUnTrigger:(id)arg1 ;
-(void)_proximityClientDeviceUpdated:(id)arg1 ;
-(void)_bleDeviceNearbyEnter:(id)arg1 ;
-(void)_bleDeviceNearbyExit:(id)arg1 ;
-(void)_bleActionScanTimerFired;
-(void)_bleInfoDeviceFound:(id)arg1 ;
-(void)_bleInfoDeviceLost:(id)arg1 ;
-(void)_bleInfoDeviceChanged:(id)arg1 ;
-(void)_updateCandidateIsNearby;
-(void)_proximityClientDeviceEnteredNearby:(id)arg1 ;
-(void)_proximityClientDeviceExitedNearby:(id)arg1 ;
-(void)_bleUpdateMappingAndNearby;
-(void)_clinkHandleRequest:(id)arg1 options:(id)arg2 responseHandler:(/*^block*/id)arg3 ;
-(void)_clinkHomePodHandleRequest:(id)arg1 responseHandler:(/*^block*/id)arg2 ;
-(void)_proximityClientSeedInitialDevices:(id)arg1 ;
-(void)_proximityClientSeedWillTriggerDeviceIfNeeded:(id)arg1 ;
-(id)_combinedDeviceForUIID:(id)arg1 ;
-(id)mediaTransferInfoFromInfo:(id)arg1 ;
-(unsigned long long)notificationHomePodTypeForDevice:(id)arg1 ;
-(void)_serviceTimeoutInvalidate;
-(void)_serviceTimeoutFired;
-(void)_throttleEventSet:(unsigned long long)arg1 ;
-(void)_proximityClientDeviceWasDismissed:(id)arg1 reason:(long long)arg2 ;
-(void)_proximityClientDeviceWasSelected:(id)arg1 ;
-(id)_routeForDevice:(id)arg1 ;
-(id)callTransferInfoForDevice:(id)arg1 ;
-(char)_throttleEventsReachedMax;
-(char)_throttleMediumAllowsTrigger;
-(void)setPreventNotifications:(char)arg1 ;
-(int)proximityClientStart:(id)arg1 ;
-(void)proximityClientStop:(id)arg1 ;
-(void)proximityClientUpdate:(id)arg1 ;
-(int)proximityClient:(id)arg1 dismissContentForDevice:(id)arg2 ;
-(int)proximityClient:(id)arg1 provideContent:(id)arg2 forDevice:(id)arg3 force:(char)arg4 ;
-(int)proximityClient:(id)arg1 suppressDevice:(id)arg2 ;
-(int)proximityClient:(id)arg1 stopSuppressingDevice:(id)arg2 ;
-(int)proximityClient:(id)arg1 updateContent:(id)arg2 forDevice:(id)arg3 ;
-(int)proximityClientRequestScannerTimerReset:(id)arg1 ;
-(void)_proximityClientDeviceWasDismissed:(id)arg1 ;
-(void)_serviceTimeoutActivate;
-(void)_throttleEventsReset;
-(void)_throttleMediumReset;
-(void)_hapticsEnsurePrepared;
-(char)_expectingContentForDeviceID:(id)arg1 ;
-(char)callTransferShouldPush:(id)arg1 ;
-(void)testUI:(id)arg1 ;
-(char)preventNotifications;
@end

