/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, March 1, 2023 at 11:00:10 PM Israel Standard Time
* Operating System: Version 11.2.3 (Build 20D91)
* Image Source: /usr/libexec/sharingd
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


#import <sharingd/sharingd-Structs.h>
@class NSMutableDictionary, RPPeopleDiscovery, SDXPCHelperConnection, NSArray;

@interface SDRapportBrowser : NSObject {

	long long _startCount;
	NSMutableDictionary* _cachedNodes;
	RPPeopleDiscovery* _peopleDiscovery;
	SDXPCHelperConnection* _helperConnection;

}

@property (assign,nonatomic,__weak) SDXPCHelperConnection * helperConnection;              //@synthesize helperConnection=_helperConnection - In the implementation block
@property (copy,readonly) NSArray * nodes; 
+(char)deviceIsEligibleForAirDrop:(id)arg1 ;
+(void)updateRangingMeasurementForDevice:(id)arg1 inNode:(SFNodeRef)arg2 ;
+(char)personHasAirDropEligibleDevice:(id)arg1 ;
+(void)updateRangingMeasurementForPerson:(id)arg1 inNode:(SFNodeRef)arg2 ;
+(id)identifiersForPerson:(id)arg1 ;
+(id)deviceTypeFromModelIdentifier:(id)arg1 ;
+(unsigned long long)defaultSFNodeFlags;
+(id)sharedRapportBrowser;
+(id)deviceImageNameFromModelIdentifier:(id)arg1 ;
-(id)init;
-(void)start;
-(void)stop;
-(void)_start;
-(void)_stop;
-(NSArray *)nodes;
-(void)contactsChanged:(id)arg1 ;
-(void)removeObservers;
-(SDXPCHelperConnection *)helperConnection;
-(void)setHelperConnection:(SDXPCHelperConnection *)arg1 ;
-(id)assertionIdentifier;
-(void)addObservers;
-(void)stopHandoffAdvertisingIfAppropriate;
-(void)addOrUpdateNodesForPerson:(id)arg1 withChanges:(unsigned)arg2 ;
-(void)removeNodesForPerson:(id)arg1 ;
-(void)resumeHandoffAdvertisingIfAppropriate;
-(SFNodeRef)createSFNodeFromMyRPDevice:(id)arg1 ;
-(SFNodeRef)createSFNodeFromRPPerson:(id)arg1 ;
-(char)shouldStopHandoffAdvertising;
-(SFNodeRef)createSFNodeFromCNContact:(id)arg1 identifier:(id)arg2 device:(id)arg3 ;
@end

