/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, March 1, 2023 at 11:00:16 PM Israel Standard Time
* Operating System: Version 11.2.3 (Build 20D91)
* Image Source: /usr/libexec/sharingd
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol OS_dispatch_source, OS_dispatch_queue;
@class NSData, SFDeviceDiscovery, NSMutableDictionary, SFService, SFPINPairSession, NSUUID, SFUserAlert, SFPasswordSharingSession, NSObject, NSURL, SDStatusMonitor, CUSystemMonitor, NEVPNConnection, SFBLEScanner, SFDeviceRepairService, SFDeviceRepairSession, SFWiFiHealthMonitor;

@interface SDSetupAgent : NSObject {

	NSData* _bleAuthTagFilter;
	char _clientEnabled;
	SFDeviceDiscovery* _deviceDiscovery;
	NSMutableDictionary* _devices;
	char _hsa2Enabled;
	SFService* _pinPairService;
	SFPINPairSession* _pinPairSession;
	NSUUID* _pinPairUUID;
	int _profilesNotifyToken;
	char _pwsAutoGrantingEnabled;
	char _pwsGrantingEnabled;
	SFUserAlert* _pwsNotification;
	NSUUID* _pwsPresentedID;
	SFPasswordSharingSession* _pwsSession;
	char _scanEligible;
	int _scanSeconds;
	NSObject*<OS_dispatch_source> _scanTimer;
	char _serverEnabled;
	NSURL* _setupURL;
	char _shouldScan;
	SDStatusMonitor* _statusMonitor;
	CUSystemMonitor* _systemMonitor;
	NSMutableDictionary* _triggeredDevices;
	char _triggeredUIAppleTVPair;
	char _triggeredUIAppleTVSetup;
	char _renableB238SetupAfterWiFi;
	char _triggeredUIB238Setup;
	char _triggeredUIiOSSetup;
	char _triggeredUIRepair;
	char _triggeredUIWatchSetup;
	char _triggeredUIWHASetup;
	char _triggeredUIAuthenticateAccounts;
	NEVPNConnection* _vpnCnx;
	unsigned long long _watchFastScanLastEndTicks;
	NSObject*<OS_dispatch_source> _watchFastScanTimer;
	NSMutableDictionary* _watchSetupDevices;
	char _watchMigrationEnabled;
	unsigned long long _watchMigrationLastTicks;
	char _watchSetupEnabled;
	SFBLEScanner* _watchSetupScanner;
	char _airplayActive;
	int _airplayNotifyToken;
	char _cdpEnabled;
	int _cfuNotifyToken;
	int _iTunesNotifyToken;
	CUSystemMonitor* _manateeMonitor;
	char _manateeProblem;
	unsigned long long _problemFlags;
	int _problemNotifyToken;
	char _repairEnabled;
	SFDeviceRepairService* _repairService;
	SFDeviceRepairSession* _repairSession;
	char _repairSilent;
	NSObject*<OS_dispatch_source> _repairTimer;
	SFWiFiHealthMonitor* _wifiHealthMonitor;
	char _wifiBad;
	char _wifiBad8021x;
	char _prefRepairAccounts;
	char _prefRepairHomeKit;
	char _prefRepairVPN;
	char _prefRepairWiFi;
	char _preventRepair;
	NSObject*<OS_dispatch_queue> _dispatchQueue;

}

@property (nonatomic,retain) NSObject*<OS_dispatch_queue> dispatchQueue;              //@synthesize dispatchQueue=_dispatchQueue - In the implementation block
@property (assign,nonatomic) char preventRepair;                                      //@synthesize preventRepair=_preventRepair - In the implementation block
@property (nonatomic,readonly) char uiShowing; 
+(id)sharedSetupAgent;
-(void)dealloc;
-(id)description;
-(id)init;
-(void)_activate;
-(void)invalidate;
-(void)_invalidate;
-(NSObject*<OS_dispatch_queue>)dispatchQueue;
-(void)_update;
-(void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void*)arg4 ;
-(void)activate;
-(void)setDispatchQueue:(NSObject*<OS_dispatch_queue>)arg1 ;
-(id)descriptionWithLevel:(int)arg1 ;
-(char)_screenLocked;
-(void)_wifiStateChanged;
-(void)repairDevice:(id)arg1 flags:(unsigned)arg2 completion:(/*^block*/id)arg3 ;
-(void)_deviceLost:(id)arg1 ;
-(void)prefsChanged;
-(void)_ensureClientStopped;
-(void)_ensureServerStopped;
-(char)_uiShowing;
-(void)_uiStartWithDevice:(id)arg1 viewControllerName:(id)arg2 xpcEndpoint:(id)arg3 label:(id)arg4 unlessApps:(id)arg5 extraInfo:(id)arg6 ;
-(void)_uiStartRepair:(id)arg1 flags:(unsigned)arg2 ;
-(void)_uiStartSetupiOS:(id)arg1 autoStart:(char)arg2 ;
-(void)_uiStartSetupB238:(id)arg1 extraInfo:(id)arg2 ;
-(void)_uiStartWithDevice:(id)arg1 viewControllerName:(id)arg2 label:(id)arg3 unlessApps:(id)arg4 extraInfo:(id)arg5 ;
-(void)_uiStartHomeKitDeviceDetectedWithURL:(id)arg1 ;
-(void)_ensureClientStarted;
-(void)_ensureServerStarted;
-(void)_repairEnsuredStarted;
-(void)_repairEnsuredStopped;
-(void)_iTunesAccountsChanged;
-(void)_appleAccountSignIn:(id)arg1 ;
-(void)_hsa2Changed;
-(void)_uiLockStatusChanged;
-(void)_screenStateChanged;
-(void)_scanTimerFired;
-(void)_deviceFound:(id)arg1 ;
-(void)_watchFound:(id)arg1 ;
-(void)_resetTriggers;
-(void)_postDeviceSetupNotificationForDevice:(id)arg1 present:(char)arg2 ;
-(void)_uiStopIfNeededWithDevice:(id)arg1 ;
-(void)_uiStartPair:(id)arg1 extraInfo:(id)arg2 ;
-(void)_uiStartAppleTVSetup:(id)arg1 extraInfo:(id)arg2 ;
-(void)_launchAppWithMachServiceName:(id)arg1 ;
-(void)_repairSilentStart:(id)arg1 ;
-(void)_uiStartSetupWHA:(id)arg1 ;
-(void)_uiStartAuthenticateAccounts:(id)arg1 ;
-(char)_shouldOfferPassword:(id)arg1 ;
-(void)_uiStartWiFiPasswordSharing:(id)arg1 ;
-(void)_uiStartWithDevice:(id)arg1 viewControllerName:(id)arg2 xpcEndpoint:(id)arg3 label:(id)arg4 extraInfo:(id)arg5 ;
-(void)_uiStartForMacWithDevice:(id)arg1 label:(id)arg2 extraInfo:(id)arg3 ;
-(void)_pwsHandleUserResponse:(int)arg1 device:(id)arg2 info:(id)arg3 ;
-(void)_watchFastScanStop;
-(void)_watchFastScanStartIfAllowed:(id)arg1 ;
-(void)_uiStartSetupWatch:(id)arg1 ;
-(void)_pinPairHandleRequest:(id)arg1 ;
-(void)_pinPairHandleShowPIN:(id)arg1 ;
-(void)_pinPairHandleHidePIN;
-(void)_pwsHandleProgressEvent:(unsigned)arg1 info:(id)arg2 ;
-(void)_repairProblemFlagsChanged;
-(void)_repairHandleCFUItemsChanged;
-(void)_repairHandleManateeChanged;
-(void)_repairVPNError:(id)arg1 ;
-(void)_repairHandleCompletion;
-(void)_repairProblemCheck;
-(void)_repairHandleCFUItems:(id)arg1 ;
-(void)_repairSilentProgress:(unsigned)arg1 info:(id)arg2 ;
-(void)_repairUpdateIDSCache;
-(void)_uiStartProxCardKitTest:(id)arg1 extraInfo:(id)arg2 ;
-(void)setPreventRepair:(char)arg1 ;
-(void)nfcTagReaderUIActivateWithEndpoint:(id)arg1 params:(id)arg2 completion:(/*^block*/id)arg3 ;
-(void)openSetupURL:(id)arg1 ;
-(void)_openSetupURL:(id)arg1 ;
-(char)reenableProxCardType:(unsigned char)arg1 ;
-(void)retriggerProximitySetup:(/*^block*/id)arg1 ;
-(void)setupDevice:(id)arg1 homeIdentifier:(id)arg2 completion:(/*^block*/id)arg3 ;
-(void)showDevicePickerWithInfo:(id)arg1 completion:(/*^block*/id)arg2 ;
-(void)triggerHomeKitDeviceDetectedWithURL:(id)arg1 completion:(/*^block*/id)arg2 ;
-(char)uiShowing;
-(void)testHomeKitDeviceDetected:(id)arg1 ;
-(void)testNFCUI:(id)arg1 ;
-(void)testPairUI:(id)arg1 ;
-(void)testPINShow:(id)arg1 ;
-(void)testPINHide;
-(void)testRepairUI:(id)arg1 ;
-(void)testSetupUIB238:(id)arg1 ;
-(void)testSetupUIiOS:(id)arg1 ;
-(void)testSetupUIPasswordSharing:(id)arg1 ;
-(void)testSetupUIWatch:(id)arg1 ;
-(void)testSetupUIWHA:(id)arg1 ;
-(void)testUIAppleTVSetup:(id)arg1 ;
-(void)testProxCardKit:(id)arg1 ;
-(char)preventRepair;
@end

