/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, March 1, 2023 at 11:00:11 PM Israel Standard Time
* Operating System: Version 11.2.3 (Build 20D91)
* Image Source: /usr/libexec/sharingd
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <sharingd/sharingd-Structs.h>
#import <libobjc.A.dylib/SDBonjourBrowserDelegate.h>
#import <libobjc.A.dylib/SDWindowsBrowserDelegate.h>

@class NSMutableDictionary, NSString;

@interface SDServerBrowser : NSObject <SDBonjourBrowserDelegate, SDWindowsBrowserDelegate> {

	long long _mode;
	NSMutableDictionary* _odiskBrowsers;
	NSMutableDictionary* _bonjourBrowsers;
	NSMutableDictionary* _windowsBrowsers;
	NSMutableDictionary* _airDropBrowsers;

}

@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
+(id)sharedBrowser;
-(NSString *)description;
-(id)init;
-(void)bonjourNodesDidChange:(id)arg1 ;
-(void)stopBrowsingWorkgroup:(id)arg1 ;
-(void)setBonjourBrowserMode:(long long)arg1 ;
-(void)startBrowsingDomain:(id)arg1 ;
-(id)bonjourNodesForDomain:(id)arg1 ;
-(void)startBrowsingWorkgroup:(id)arg1 ;
-(id)windowsNodesForWorkgroup:(id)arg1 ;
-(void)startODiskBrowsing:(id)arg1 ;
-(id)odiskNodesForDomain:(id)arg1 ;
-(void)startAirDropBrowsing:(id)arg1 bundleID:(id)arg2 sessionID:(id)arg3 helperConnection:(id)arg4 ;
-(void)startAirDropBrowsing:(id)arg1 connection:(id)arg2 sessionID:(id)arg3 ;
-(id)airDropNodesForDomain:(id)arg1 ;
-(void)stopBrowsingDomain:(id)arg1 ;
-(void)stopODiskBrowsing:(id)arg1 ;
-(void)stopAirDropBrowsing:(id)arg1 ;
-(void)postNotification:(id)arg1 forNeighborhood:(id)arg2 ;
-(void)setIconData:(id)arg1 iconHash:(id)arg2 forPerson:(SFNodeRef)arg3 ;
-(id)stringForBrowserMode:(long long)arg1 ;
-(void)windowsNodesDidChange:(id)arg1 ;
-(void)incrementTransfersInitiated;
-(void)incrementTransfersCompleted;
-(char)isAirDropEnabled;
@end

