/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, March 1, 2023 at 11:00:07 PM Israel Standard Time
* Operating System: Version 11.2.3 (Build 20D91)
* Image Source: /usr/libexec/sharingd
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol OS_dispatch_source, OS_dispatch_queue;
@class NSMutableSet, NSObject, SFRemoteTextInputClient, NSDate, NSDictionary;

@interface SDSharedRemoteTextInputClient : NSObject {

	char _activateCalled;
	NSMutableSet* _delegates;
	NSObject*<OS_dispatch_source> _overrunTimer;
	SFRemoteTextInputClient* _rtiClient;
	NSDate* _sessionClock;
	NSObject*<OS_dispatch_queue> _dispatchQueue;

}

@property (nonatomic,copy,readonly) NSDictionary * currentPayload; 
@property (nonatomic,retain) NSObject*<OS_dispatch_queue> dispatchQueue;              //@synthesize dispatchQueue=_dispatchQueue - In the implementation block
+(id)sharedClient;
-(id)init;
-(void)invalidate;
-(NSObject*<OS_dispatch_queue>)dispatchQueue;
-(void)activate;
-(void)setDispatchQueue:(NSObject*<OS_dispatch_queue>)arg1 ;
-(void)removeDelegate:(id)arg1 ;
-(void)addDelegate:(id)arg1 ;
-(void)_ensureStarted;
-(void)prefsChanged;
-(void)_rtiHandleEventWithData:(id)arg1 ;
-(void)_rtiHandleInputDidBeginWithFlags:(unsigned long long)arg1 sessionInfo:(id)arg2 ;
-(void)_rtiHandleInputDidEndWithFlags:(unsigned long long)arg1 sessionInfo:(id)arg2 ;
-(NSDictionary *)currentPayload;
-(void)removeAllDelegates;
-(void)_stopClock:(unsigned long long)arg1 ;
-(void)handleTextInputData:(id)arg1 ;
-(void)handleUsername:(id)arg1 password:(id)arg2 ;
-(void)_startClockWithResetIfNeeded;
-(void)_logEvent:(unsigned long long)arg1 stopClock:(char)arg2 ;
@end

