/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, March 1, 2023 at 11:00:11 PM Israel Standard Time
* Operating System: Version 11.2.3 (Build 20D91)
* Image Source: /usr/libexec/sharingd
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol SDStreamHandlerDelegate <NSObject>
@optional
-(void)streamHandlerDidClose:(id)arg1 withError:(id)arg2;
-(void)streamHandler:(id)arg1 bufferSpaceChanged:(char)arg2;
-(void)streamHandler:(id)arg1 didReceiveStreamData:(id)arg2;
-(void)streamHandlerDidClose:(id)arg1;

@required
-(void)streamHandler:(id)arg1 didReceiveMessage:(id)arg2;

@end

