/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, March 1, 2023 at 11:00:13 PM Israel Standard Time
* Operating System: Version 11.2.3 (Build 20D91)
* Image Source: /usr/libexec/sharingd
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol OS_dispatch_queue;
@class NSString, NSArray, SDXPCHelperConnection, NSObject, SDPeopleSuggestionsResult;

@interface SDSuggestionBrowser : NSObject {

	NSString* _bundleID;
	NSArray* _typeIdentifiersBeingShared;
	NSArray* _photosAssetIDs;
	int _predictionNumber;
	NSString* _sessionID;
	SDXPCHelperConnection* _helperConnection;
	NSArray* _nodes;
	NSObject*<OS_dispatch_queue> _primedSuggestionssQueue;
	SDPeopleSuggestionsResult* _primedSuggestionsResult;

}

@property (retain) NSObject*<OS_dispatch_queue> primedSuggestionssQueue;                   //@synthesize primedSuggestionssQueue=_primedSuggestionssQueue - In the implementation block
@property (retain) SDPeopleSuggestionsResult * primedSuggestionsResult;                    //@synthesize primedSuggestionsResult=_primedSuggestionsResult - In the implementation block
@property (nonatomic,copy) NSString * sessionID;                                           //@synthesize sessionID=_sessionID - In the implementation block
@property (assign,nonatomic,__weak) SDXPCHelperConnection * helperConnection;              //@synthesize helperConnection=_helperConnection - In the implementation block
@property (copy,readonly) NSArray * nodes;                                                 //@synthesize nodes=_nodes - In the implementation block
@property (copy,readonly) NSString * bundleID;                                             //@synthesize bundleID=_bundleID - In the implementation block
-(NSString *)bundleID;
-(NSString *)sessionID;
-(void)setSessionID:(NSString *)arg1 ;
-(NSArray *)nodes;
-(SDXPCHelperConnection *)helperConnection;
-(void)setHelperConnection:(SDXPCHelperConnection *)arg1 ;
-(void)setPrimedSuggestionssQueue:(NSObject*<OS_dispatch_queue>)arg1 ;
-(NSObject*<OS_dispatch_queue>)primedSuggestionssQueue;
-(SDPeopleSuggestionsResult *)primedSuggestionsResult;
-(void)setPrimedSuggestionsResult:(SDPeopleSuggestionsResult *)arg1 ;
-(id)startPeopleSuggesterWithPreheating:(char)arg1 ;
-(id)initWithBundleID:(id)arg1 typeIdentifiersBeingShared:(id)arg2 photosAssetIDs:(id)arg3 urlsBeingShared:(id)arg4 shouldSuggestFamilyMembers:(char)arg5 ;
-(void)primeSuggestions;
-(id)peopleSuggestions;
-(void)provideFeedbackForNodeAtIndex:(id)arg1 bundleID:(id)arg2 abandoned:(char)arg3 ;
@end

