/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, March 1, 2023 at 11:00:02 PM Israel Standard Time
* Operating System: Version 11.2.3 (Build 20D91)
* Image Source: /usr/libexec/sharingd
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <sharingd/sharingd-Structs.h>
#import <ProtocolBuffer/PBRequest.h>
#import <libobjc.A.dylib/NSCopying.h>

@class NSData;

@interface SDUnlockSetupRequest : PBRequest <NSCopying> {

	NSData* _longTermKey;
	NSData* _ltkHash;
	unsigned _sessionID;
	unsigned _version;
	char _remoteNeedsLTK;
	SCD_Struct_SD3 _has;

}

@property (assign,nonatomic) char hasVersion; 
@property (assign,nonatomic) unsigned version;                    //@synthesize version=_version - In the implementation block
@property (assign,nonatomic) char hasSessionID; 
@property (assign,nonatomic) unsigned sessionID;                  //@synthesize sessionID=_sessionID - In the implementation block
@property (nonatomic,readonly) char hasLongTermKey; 
@property (nonatomic,retain) NSData * longTermKey;                //@synthesize longTermKey=_longTermKey - In the implementation block
@property (nonatomic,readonly) char hasLtkHash; 
@property (nonatomic,retain) NSData * ltkHash;                    //@synthesize ltkHash=_ltkHash - In the implementation block
@property (assign,nonatomic) char hasRemoteNeedsLTK; 
@property (assign,nonatomic) char remoteNeedsLTK;                 //@synthesize remoteNeedsLTK=_remoteNeedsLTK - In the implementation block
-(id)copyWithZone:(NSZone*)arg1 ;
-(char)isEqual:(id)arg1 ;
-(unsigned long long)hash;
-(id)description;
-(unsigned)version;
-(id)dictionaryRepresentation;
-(void)setVersion:(unsigned)arg1 ;
-(void)mergeFrom:(id)arg1 ;
-(char)readFrom:(id)arg1 ;
-(void)writeTo:(id)arg1 ;
-(void)copyTo:(id)arg1 ;
-(unsigned)sessionID;
-(void)setSessionID:(unsigned)arg1 ;
-(char)hasVersion;
-(void)setHasSessionID:(char)arg1 ;
-(char)hasSessionID;
-(void)setHasVersion:(char)arg1 ;
-(void)setLongTermKey:(NSData *)arg1 ;
-(void)setLtkHash:(NSData *)arg1 ;
-(char)hasLongTermKey;
-(char)hasLtkHash;
-(NSData *)longTermKey;
-(NSData *)ltkHash;
-(void)setRemoteNeedsLTK:(char)arg1 ;
-(void)setHasRemoteNeedsLTK:(char)arg1 ;
-(char)hasRemoteNeedsLTK;
-(char)remoteNeedsLTK;
@end

