/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, March 1, 2023 at 11:00:00 PM Israel Standard Time
* Operating System: Version 11.2.3 (Build 20D91)
* Image Source: /usr/libexec/sharingd
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <libobjc.A.dylib/SFUnlockProtocol.h>
#import <libobjc.A.dylib/SDAutoUnlockSessionManagerObserver.h>

@protocol SDUnlockXPCSesssionDelegate, SFUnlockClientProtocol;
@class NSString, SFAutoUnlockDevice;

@interface SDUnlockXPCSession : NSObject <SFUnlockProtocol, SDAutoUnlockSessionManagerObserver> {

	id<SDUnlockXPCSesssionDelegate> _delegate;
	NSString* _bundleID;
	id<SFUnlockClientProtocol> _clientProxy;
	SFAutoUnlockDevice* _enableDevice;

}

@property (nonatomic,copy) NSString * bundleID;                                   //@synthesize bundleID=_bundleID - In the implementation block
@property (nonatomic,retain) id<SFUnlockClientProtocol> clientProxy;              //@synthesize clientProxy=_clientProxy - In the implementation block
@property (nonatomic,retain) SFAutoUnlockDevice * enableDevice;                   //@synthesize enableDevice=_enableDevice - In the implementation block
@property (retain) id<SDUnlockXPCSesssionDelegate> delegate;                      //@synthesize delegate=_delegate - In the implementation block
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(void)invalidate;
-(id<SDUnlockXPCSesssionDelegate>)delegate;
-(void)setDelegate:(id<SDUnlockXPCSesssionDelegate>)arg1 ;
-(void)setBundleID:(NSString *)arg1 ;
-(NSString *)bundleID;
-(void)notifyDelegate;
-(id<SFUnlockClientProtocol>)clientProxy;
-(void)setClientProxy:(id<SFUnlockClientProtocol>)arg1 ;
-(void)autoUnlockStateWithCompletionHandler:(/*^block*/id)arg1 ;
-(void)cancelAutoUnlock:(char)arg1 ;
-(void)repairCloudPairing;
-(char)checkEntitlementWithHandler:(/*^block*/id)arg1 ;
-(void)setEnableDevice:(SFAutoUnlockDevice *)arg1 ;
-(void)cancelEnablingAutoUnlockForDevice:(id)arg1 ;
-(void)disableAutoUnlockForDevice:(id)arg1 completionHandler:(/*^block*/id)arg2 ;
-(void)cancelAutoUnlock;
-(void)authPromptInfoWithCompletionHandler:(/*^block*/id)arg1 ;
-(SFAutoUnlockDevice *)enableDevice;
-(void)eligibleAutoUnlockDevicesWithCompletionHandler:(/*^block*/id)arg1 ;
-(void)enableAutoUnlockWithDevice:(id)arg1 passcode:(id)arg2 clientProxy:(id)arg3 ;
-(void)attemptAutoUnlockWithClientProxy:(id)arg1 ;
-(void)session:(id)arg1 didReceiveKeyDeviceLocked:(id)arg2 ;
-(void)session:(id)arg1 didEnableWithDevice:(id)arg2 ;
-(void)session:(id)arg1 didFailToEnableDevice:(id)arg2 error:(id)arg3 ;
-(void)session:(id)arg1 didBeginAttemptWithDevice:(id)arg2 ;
-(void)session:(id)arg1 didCompleteUnlockWithDevice:(id)arg2 ;
-(void)session:(id)arg1 didFailUnlockWithResults:(id)arg2 error:(id)arg3 incrementedAttempt:(char)arg4 ;
@end

