/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, March 1, 2023 at 11:00:04 PM Israel Standard Time
* Operating System: Version 11.2.3 (Build 20D91)
* Image Source: /usr/libexec/sharingd
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <libobjc.A.dylib/NSXPCListenerDelegate.h>
#import <libobjc.A.dylib/SDConnectionManagerDelegate.h>

@class NSXPCListener, NSMutableArray, NSString;

@interface SDXPCSession : NSObject <NSXPCListenerDelegate, SDConnectionManagerDelegate> {

	NSXPCListener* _xpcManagerListener;
	NSMutableArray* _connections;

}

@property (retain) NSXPCListener * xpcManagerListener;              //@synthesize xpcManagerListener=_xpcManagerListener - In the implementation block
@property (retain) NSMutableArray * connections;                    //@synthesize connections=_connections - In the implementation block
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
+(id)sharedSession;
-(id)init;
-(char)listener:(id)arg1 shouldAcceptNewConnection:(id)arg2 ;
-(void)start;
-(void)stop;
-(NSMutableArray *)connections;
-(void)setConnections:(NSMutableArray *)arg1 ;
-(void)connectionManagerDidInvalidate:(id)arg1 ;
-(NSXPCListener *)xpcManagerListener;
-(void)setXpcManagerListener:(NSXPCListener *)arg1 ;
@end

