/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, March 1, 2023 at 11:00:16 PM Israel Standard Time
* Operating System: Version 11.2.3 (Build 20D91)
* Image Source: /usr/libexec/sharingd
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <sharingd/sharingd-Structs.h>
#import <libobjc.A.dylib/NSXPCListenerDelegate.h>

@protocol OS_dispatch_queue;
@class SDAppleIDAgent, NSCountedSet, NSObject, SDHotspotAgent, SDNearbyAgent, SDRemoteInteractionAgent, SDSharedRemoteTextInputClient, SDProxHandoffAgent, SDSetupAgent, NSMutableSet, NSXPCInterface, NSXPCListener, NSString;

@interface SDXPCServer : NSObject <NSXPCListenerDelegate> {

	SDAppleIDAgent* _appleIDAgent;
	NSCountedSet* _assertions;
	NSObject*<OS_dispatch_queue> _contactsQueue;
	NSObject*<OS_dispatch_queue> _dispatchQueue;
	SDHotspotAgent* _hotspotAgent;
	SDNearbyAgent* _nearbyAgent;
	int _prefNotifyToken;
	SDRemoteInteractionAgent* _riAgent;
	SDSharedRemoteTextInputClient* _rtiClient;
	SDProxHandoffAgent* _proxHandoffAgent;
	SDSetupAgent* _setupAgent;
	unsigned long long _stateHandle;
	NSMutableSet* _xpcConnections;
	NSXPCInterface* _xpcInterfaceClient;
	NSXPCInterface* _xpcInterfaceServer;
	NSXPCListener* _xpcListener;

}

@property (nonatomic,retain) NSObject*<OS_dispatch_queue> dispatchQueue;              //@synthesize dispatchQueue=_dispatchQueue - In the implementation block
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(id)init;
-(void)_activate;
-(void)invalidate;
-(char)listener:(id)arg1 shouldAcceptNewConnection:(id)arg2 ;
-(void)_invalidate;
-(NSObject*<OS_dispatch_queue>)dispatchQueue;
-(void)activate;
-(void)setDispatchQueue:(NSObject*<OS_dispatch_queue>)arg1 ;
-(void)_connectionInvalidated:(id)arg1 ;
-(os_state_data_s*)_stateDump;
-(void)stateAppendXPCConnections:(id*)arg1 ;
@end

