/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, March 1, 2023 at 11:00:16 PM Israel Standard Time
* Operating System: Version 11.2.3 (Build 20D91)
* Image Source: /usr/libexec/sharingd
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol SDXPCAppleIDAuthInterface
@required
-(void)personInfoWithEmailOrPhone:(id)arg1 completion:(/*^block*/id)arg2;
-(void)requestWithInfo:(id)arg1 completion:(/*^block*/id)arg2;
-(void)accountForAppleID:(id)arg1 withCompletion:(/*^block*/id)arg2;
-(void)myAccountWithCompletion:(/*^block*/id)arg1;
-(void)statusInfoWithCompletion:(/*^block*/id)arg1;

@end

