/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, March 1, 2023 at 11:00:16 PM Israel Standard Time
* Operating System: Version 11.2.3 (Build 20D91)
* Image Source: /usr/libexec/sharingd
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol SDXPCServiceInterface
@required
-(void)serviceActivate:(id)arg1 completion:(/*^block*/id)arg2;
-(void)serviceUpdate:(id)arg1;
-(void)serviceSendEvent:(id)arg1;
-(void)serviceSendFrameType:(unsigned char)arg1 data:(id)arg2 peer:(id)arg3;
-(void)serviceSendRequest:(id)arg1;
-(void)serviceSendResponse:(id)arg1;

@end

