/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, March 1, 2023 at 11:00:14 PM Israel Standard Time
* Operating System: Version 11.2.3 (Build 20D91)
* Image Source: /usr/libexec/sharingd
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol OS_dispatch_queue;
#import <sharingd/sharingd-Structs.h>
@class NSObject, NSXPCConnection, NSString, NSMutableDictionary, NSMutableArray;

@interface SDXPCHelperConnection : NSObject {

	char _activated;
	char _needsTransactionRelease;
	char _invalidateCalled;
	NSObject*<OS_dispatch_queue> _queue;
	NSXPCConnection* _connectionToService;
	unsigned long long _intervalID;
	NSString* _signpostName;
	long long _cacheAccessCount;
	NSMutableDictionary* _cacheAccessDict;
	os_unfair_lock_s _cacheAccessLock;
	NSMutableArray* _queuedBlocks;
	/*^block*/id _interruptionHandler;
	/*^block*/id _invalidationHandler;

}

@property (nonatomic,copy) id interruptionHandler;              //@synthesize interruptionHandler=_interruptionHandler - In the implementation block
@property (nonatomic,copy) id invalidationHandler;              //@synthesize invalidationHandler=_invalidationHandler - In the implementation block
+(void)updateCacheFromSFCGImageData:(id)arg1 cacheKey:(id)arg2 contactIDs:(id)arg3 ;
+(id)makeActivatedConnection;
-(void)dealloc;
-(void)invalidate;
-(void)setInterruptionHandler:(id)arg1 ;
-(void)setInvalidationHandler:(id)arg1 ;
-(id)initWithQueue:(id)arg1 ;
-(void)activate;
-(id)interruptionHandler;
-(id)invalidationHandler;
-(id)whitelistedDownloadsFolderURL;
-(void)setSessionKeepAliveTransactionIdentifier:(id)arg1 ;
@end

