/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, March 1, 2023 at 11:00:16 PM Israel Standard Time
* Operating System: Version 11.2.3 (Build 20D91)
* Image Source: /usr/libexec/sharingd
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol SDXPCDiagnosticsInterface
@required
-(void)diagnosticControl:(id)arg1 completion:(/*^block*/id)arg2;
-(void)diagnosticShow:(id)arg1 completion:(/*^block*/id)arg2;
-(void)diagnosticLogControl:(id)arg1 completion:(/*^block*/id)arg2;
-(void)bluetoothUserInteraction;
-(void)diagnosticBLEModeWithCompletion:(/*^block*/id)arg1;
-(void)diagnosticMock:(id)arg1 device:(id)arg2 completion:(/*^block*/id)arg3;
-(void)diagnosticMockStart:(/*^block*/id)arg1;
-(void)diagnosticMockStop:(/*^block*/id)arg1;
-(void)diagnosticUnlockTestClientWithDevice:(id)arg1;
-(void)diagnosticUnlockTestServer;

@end

