/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, March 1, 2023 at 11:00:17 PM Israel Standard Time
* Operating System: Version 11.2.3 (Build 20D91)
* Image Source: /usr/libexec/sharingd
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol SDXPCSessionInterface
@required
-(void)sessionActivate:(id)arg1 completion:(/*^block*/id)arg2;
-(void)sessionSendEvent:(id)arg1;
-(void)sessionSendFrameType:(unsigned char)arg1 data:(id)arg2;
-(void)sessionSendRequest:(id)arg1;
-(void)sessionSendResponse:(id)arg1;

@end

