/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, March 1, 2023 at 11:00:06 PM Israel Standard Time
* Operating System: Version 11.2.3 (Build 20D91)
* Image Source: /usr/libexec/sharingd
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol SFActivityAdvertiserProtocol <SDXPCDaemonProtocol>
@required
-(void)loginIDWithOptions:(id)arg1 completionHandler:(/*^block*/id)arg2;
-(void)peerForUUID:(id)arg1 completionHandler:(/*^block*/id)arg2;
-(void)pairedSFPeerDevicesWithOptions:(id)arg1 completionHandler:(/*^block*/id)arg2;
-(void)advertiseAdvertisementPayload:(id)arg1 options:(id)arg2 withErrorHandler:(/*^block*/id)arg3;

@end

