/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, March 1, 2023 at 11:00:06 PM Israel Standard Time
* Operating System: Version 11.2.3 (Build 20D91)
* Image Source: /usr/libexec/sharingd
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class NSURL, SFDevice, RPCompanionLinkDevice, NSString, SFBubbleEstimator, SFNotificationInfo, TURoute;

@interface SFCombinedDevice : NSObject {

	char _forced;
	char _medBubbleDelayed;
	int _nextState;
	unsigned _notificationType;
	int _state;
	NSURL* _attachmentURL;
	SFDevice* _bleDevice;
	RPCompanionLinkDevice* _clinkDevice;
	long long _dismissReason;
	NSString* _forcedID;
	SFBubbleEstimator* _notificationBubble;
	SFNotificationInfo* _notificationInfo;
	TURoute* _route;
	SFBubbleEstimator* _transferBubble;
	unsigned long long _notificationTicks;
	double _notificationDurationSecs;
	unsigned long long _pendingContentTicks;
	double _pendingContentDurationSecs;
	unsigned long long _transferDoneTicks;
	double _transferDoneDurationSecs;
	unsigned long long _transferPendingStartTicks;
	double _transferPendingDurationSecs;

}

@property (nonatomic,retain) NSURL * attachmentURL;                                     //@synthesize attachmentURL=_attachmentURL - In the implementation block
@property (nonatomic,retain) SFDevice * bleDevice;                                      //@synthesize bleDevice=_bleDevice - In the implementation block
@property (nonatomic,retain) RPCompanionLinkDevice * clinkDevice;                       //@synthesize clinkDevice=_clinkDevice - In the implementation block
@property (assign,nonatomic) long long dismissReason;                                   //@synthesize dismissReason=_dismissReason - In the implementation block
@property (assign,nonatomic) char forced;                                               //@synthesize forced=_forced - In the implementation block
@property (nonatomic,retain) NSString * forcedID;                                       //@synthesize forcedID=_forcedID - In the implementation block
@property (assign,nonatomic) int nextState;                                             //@synthesize nextState=_nextState - In the implementation block
@property (nonatomic,retain) SFBubbleEstimator * notificationBubble;                    //@synthesize notificationBubble=_notificationBubble - In the implementation block
@property (nonatomic,retain) SFNotificationInfo * notificationInfo;                     //@synthesize notificationInfo=_notificationInfo - In the implementation block
@property (assign,nonatomic) unsigned notificationType;                                 //@synthesize notificationType=_notificationType - In the implementation block
@property (assign,nonatomic) char medBubbleDelayed;                                     //@synthesize medBubbleDelayed=_medBubbleDelayed - In the implementation block
@property (nonatomic,retain) TURoute * route;                                           //@synthesize route=_route - In the implementation block
@property (assign,nonatomic) int state;                                                 //@synthesize state=_state - In the implementation block
@property (nonatomic,retain) SFBubbleEstimator * transferBubble;                        //@synthesize transferBubble=_transferBubble - In the implementation block
@property (assign,nonatomic) unsigned long long notificationTicks;                      //@synthesize notificationTicks=_notificationTicks - In the implementation block
@property (assign,nonatomic) double notificationDurationSecs;                           //@synthesize notificationDurationSecs=_notificationDurationSecs - In the implementation block
@property (assign,nonatomic) unsigned long long pendingContentTicks;                    //@synthesize pendingContentTicks=_pendingContentTicks - In the implementation block
@property (assign,nonatomic) double pendingContentDurationSecs;                         //@synthesize pendingContentDurationSecs=_pendingContentDurationSecs - In the implementation block
@property (assign,nonatomic) unsigned long long transferDoneTicks;                      //@synthesize transferDoneTicks=_transferDoneTicks - In the implementation block
@property (assign,nonatomic) double transferDoneDurationSecs;                           //@synthesize transferDoneDurationSecs=_transferDoneDurationSecs - In the implementation block
@property (assign,nonatomic) unsigned long long transferPendingStartTicks;              //@synthesize transferPendingStartTicks=_transferPendingStartTicks - In the implementation block
@property (assign,nonatomic) double transferPendingDurationSecs;                        //@synthesize transferPendingDurationSecs=_transferPendingDurationSecs - In the implementation block
@property (nonatomic,readonly) char isReady; 
@property (nonatomic,copy,readonly) NSString * effectiveID; 
@property (nonatomic,copy,readonly) NSString * name; 
-(id)description;
-(NSString *)name;
-(int)state;
-(void)setState:(int)arg1 ;
-(char)isReady;
-(int)nextState;
-(void)setNotificationInfo:(SFNotificationInfo *)arg1 ;
-(void)setNotificationType:(unsigned)arg1 ;
-(unsigned)notificationType;
-(SFNotificationInfo *)notificationInfo;
-(TURoute *)route;
-(void)setRoute:(TURoute *)arg1 ;
-(SFDevice *)bleDevice;
-(void)setBleDevice:(SFDevice *)arg1 ;
-(NSURL *)attachmentURL;
-(void)setAttachmentURL:(NSURL *)arg1 ;
-(void)setForced:(char)arg1 ;
-(char)forced;
-(void)setNextState:(int)arg1 ;
-(char)_canTransition:(int)arg1 ;
-(void)setNotificationDurationSecs:(double)arg1 ;
-(void)setNotificationTicks:(unsigned long long)arg1 ;
-(void)setPendingContentDurationSecs:(double)arg1 ;
-(void)setPendingContentTicks:(unsigned long long)arg1 ;
-(void)setTransferDoneDurationSecs:(double)arg1 ;
-(void)setTransferDoneTicks:(unsigned long long)arg1 ;
-(void)setTransferPendingDurationSecs:(double)arg1 ;
-(void)setTransferPendingStartTicks:(unsigned long long)arg1 ;
-(SFBubbleEstimator *)notificationBubble;
-(SFBubbleEstimator *)transferBubble;
-(char)stateIsClose;
-(char)stateIsMedium;
-(char)canTransition:(int)arg1 ;
-(NSString *)effectiveID;
-(void)resetTicks;
-(char)stateIsNearby;
-(RPCompanionLinkDevice *)clinkDevice;
-(void)setClinkDevice:(RPCompanionLinkDevice *)arg1 ;
-(long long)dismissReason;
-(void)setDismissReason:(long long)arg1 ;
-(NSString *)forcedID;
-(void)setForcedID:(NSString *)arg1 ;
-(void)setNotificationBubble:(SFBubbleEstimator *)arg1 ;
-(char)medBubbleDelayed;
-(void)setMedBubbleDelayed:(char)arg1 ;
-(void)setTransferBubble:(SFBubbleEstimator *)arg1 ;
-(unsigned long long)notificationTicks;
-(double)notificationDurationSecs;
-(unsigned long long)pendingContentTicks;
-(double)pendingContentDurationSecs;
-(unsigned long long)transferDoneTicks;
-(double)transferDoneDurationSecs;
-(unsigned long long)transferPendingStartTicks;
-(double)transferPendingDurationSecs;
@end

