/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, March 1, 2023 at 11:00:17 PM Israel Standard Time
* Operating System: Version 11.2.3 (Build 20D91)
* Image Source: /usr/libexec/sharingd
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

typedef struct _NSZone* NSZoneRef;

typedef struct {
	unsigned version : 1;
} SCD_Struct_SD1;

typedef struct {
	unsigned errorCode : 1;
	unsigned sessionID : 1;
	unsigned version : 1;
	unsigned usingRecord : 1;
} SCD_Struct_SD2;

typedef struct {
	unsigned errorCode : 1;
	unsigned sessionID : 1;
	unsigned version : 1;
} SCD_Struct_SD3;

typedef struct {
	unsigned errorCode : 1;
	unsigned failureReasons : 1;
	unsigned sessionID : 1;
	unsigned version : 1;
	unsigned watchNewLTKSyncStatus : 1;
	unsigned watchOldLTKSyncStatus : 1;
	unsigned ltkSyncing : 1;
} SCD_Struct_SD4;

typedef struct {
	unsigned sessionID : 1;
	unsigned version : 1;
} SCD_Struct_SD5;

typedef struct __SecKey* SecKeyRef;

typedef struct __SecCertificate* SecCertificateRef;

typedef struct __CFReadStream* CFReadStreamRef;

typedef struct __CFWriteStream* CFWriteStreamRef;

typedef struct {
	unsigned errorCode : 1;
	unsigned version : 1;
	unsigned authPrompt : 1;
	unsigned supportsConfirmationACK : 1;
	unsigned useToken : 1;
} SCD_Struct_SD10;

typedef struct _DNSServiceRef_t* DNSServiceRef_tRef;

typedef struct __CFDictionary* CFDictionaryRef;

typedef struct __SFNode* SFNodeRef;

typedef struct __SecIdentity* SecIdentityRef;

typedef struct __CFNetService* CFNetServiceRef;

typedef struct {
	long long field1;
	int field2;
} SCD_Struct_SD16;

typedef struct __CFBag* CFBagRef;

typedef struct OpaqueLSSharedFileListRef* OpaqueLSSharedFileListRefRef;

typedef struct {
	unsigned timestamp : 1;
	unsigned deviceRole : 1;
	unsigned deviceSide : 1;
	unsigned primaryLocation : 1;
	unsigned rssi : 1;
	unsigned secondaryLocation : 1;
	unsigned smoothedRSSI : 1;
	unsigned outOfBoxMode : 1;
} SCD_Struct_AW19;

typedef struct {
	unsigned timestamp : 1;
	unsigned bannerVisibleMs : 1;
	unsigned beginEditingCount : 1;
	unsigned closeAction : 1;
	unsigned endEditingCount : 1;
	unsigned mainUIVisibleMs : 1;
	unsigned openAction : 1;
	unsigned directInput : 1;
	unsigned externalInput : 1;
	unsigned secureInput : 1;
} SCD_Struct_AW20;

typedef struct _BOMBom* BOMBomRef;

typedef struct _BOMCopier* BOMCopierRef;

typedef struct _qtn_file* qtn_fileRef;

typedef struct {
	unsigned val[8];
} SCD_Struct_SD24;

typedef struct __CFURL* CFURLRef;

typedef struct __CFArray* CFArrayRef;

typedef struct {
	unsigned timeIntervalSinceLastWatch : 1;
	unsigned timestamp : 1;
	unsigned errorCode : 1;
	unsigned errorType : 1;
	unsigned flags : 1;
	unsigned keyRequestExchangeTime : 1;
	unsigned macNewLTKSyncStatus : 1;
	unsigned macOldLTKSyncStatus : 1;
	unsigned messageTimeout : 1;
	unsigned responseTimeout : 1;
	unsigned tokenExchangeTime : 1;
	unsigned watchNewLTKSyncStatus : 1;
	unsigned watchOldLTKSyncStatus : 1;
	unsigned keyDeviceLocked : 1;
	unsigned messageTimeoutFromServer : 1;
	unsigned receivedSetupACK : 1;
	unsigned receivedTokenACK : 1;
	unsigned responseTimeoutFromServer : 1;
	unsigned setupRetry : 1;
	unsigned setupSucceeded : 1;
	unsigned upsell : 1;
	unsigned watchExistedInUnlockList : 1;
} SCD_Struct_AW27;

typedef struct {
	unsigned timestamp : 1;
	unsigned awdlVersion : 1;
	unsigned bluetoothDiscovery : 1;
	unsigned bonjourDiscovery : 1;
	unsigned bonjourResolveComplete : 1;
	unsigned bonjourTXTRecordDiscovery : 1;
	unsigned errorCode : 1;
	unsigned identityQueryComplete : 1;
	unsigned platform : 1;
	unsigned rssi : 1;
	unsigned tcpConnectionComplete : 1;
	unsigned tlsHandshakeComplete : 1;
	unsigned totalDiscovery : 1;
	unsigned verifiableIdentity : 1;
} SCD_Struct_AW28;

typedef struct {
	unsigned timestamp : 1;
	unsigned audioSourceCount : 1;
	unsigned audioState : 1;
	unsigned caseBatteryLevel : 1;
	unsigned caseBatteryPercent : 1;
	unsigned deviceRole : 1;
	unsigned deviceSide : 1;
	unsigned myBatteryLevel : 1;
	unsigned myBatteryPercent : 1;
	unsigned otherBatteryLevel : 1;
	unsigned otherBatteryPercent : 1;
	unsigned primaryLocation : 1;
	unsigned rssi : 1;
	unsigned secondaryLocation : 1;
	unsigned smoothedRSSI : 1;
	unsigned caseBatteryCharging : 1;
	unsigned myBatteryCharging : 1;
	unsigned otherBatteryCharging : 1;
	unsigned otherDeviceInCase : 1;
	unsigned outOfBoxMode : 1;
	unsigned paired : 1;
} SCD_Struct_AW29;

typedef struct {
	unsigned char field1;
	unsigned char field2;
	unsigned char field3;
	unsigned char field4;
	unsigned char field5;
	unsigned char field6;
	unsigned char field7;
	unsigned char field8;
	unsigned char field9;
	unsigned char field10;
	unsigned char field11;
	unsigned char field12;
	unsigned char field13;
	unsigned char field14;
} SCD_Struct_SD30;

typedef struct __ACMHandle* ACMHandleRef;

typedef struct {
	unsigned startTimestamp : 1;
	unsigned timestamp : 1;
	unsigned firstDiscovery : 1;
	unsigned maxPeersDiscovered : 1;
	unsigned sessionDuration : 1;
	unsigned totalPeersDiscovered : 1;
	unsigned transfersCompleted : 1;
	unsigned transfersInitiated : 1;
	unsigned legacyMode : 1;
} SCD_Struct_AW32;

typedef struct __CFString* CFStringRef;

typedef struct __CFNumber* CFNumberRef;

typedef struct __CFRunLoopSource* CFRunLoopSourceRef;

typedef struct IONotificationPort* IONotificationPortRef;

typedef struct __IOPMConnection* IOPMConnectionRef;

typedef struct __SCPreferences* SCPreferencesRef;

typedef struct _Apple80211* Apple80211Ref;

typedef struct _CFVolumeObserver* CFVolumeObserverRef;

typedef struct __SCDynamicStore* SCDynamicStoreRef;

typedef struct CGImage* CGImageRef;

typedef struct __SecTrust* SecTrustRef;

typedef struct __CFData* CFDataRef;

typedef struct _CFHTTPServerRequest* CFHTTPServerRequestRef;

typedef struct _CFHTTPServerConnection* CFHTTPServerConnectionRef;

typedef struct __CFError* CFErrorRef;

typedef struct _CFHTTPServerResponse* CFHTTPServerResponseRef;

typedef struct _CFHTTPServer* CFHTTPServerRef;

typedef struct os_unfair_lock_s {
	unsigned _os_unfair_lock_opaque;
} os_unfair_lock_s;

typedef struct {
	unsigned timeIntervalSinceLastDarkWake : 1;
	unsigned timestamp : 1;
	unsigned attemptType : 1;
	unsigned awdlBringUpTime : 1;
	unsigned awdlPeerDiscoveryTime : 1;
	unsigned awdlRangingTime : 1;
	unsigned bleAWDLInfoExchangeTime : 1;
	unsigned bleAuthTokenExchangeTime : 1;
	unsigned bleConfirmationTime : 1;
	unsigned bleKeyConnectionTime : 1;
	unsigned bleKeyDiscoveryTime : 1;
	unsigned bleKeyRequestExchangeTime : 1;
	unsigned bleProxyConnectionTime : 1;
	unsigned bleProxyDiscoveryTime : 1;
	unsigned bluetoothConnectedDevices : 1;
	unsigned cancelReason : 1;
	unsigned cancelTime : 1;
	unsigned clamshellWaitTime : 1;
	unsigned displayWaitTime : 1;
	unsigned distance : 1;
	unsigned errorCode : 1;
	unsigned errorType : 1;
	unsigned flags : 1;
	unsigned keyBluetoothRSSI : 1;
	unsigned lastSleepType : 1;
	unsigned proxyBluetoothRSSI : 1;
	unsigned timeIntervalSinceLastWake : 1;
	unsigned totalUnlockTime : 1;
	unsigned clamshellClosed : 1;
	unsigned externalDisplay : 1;
	unsigned unlockSucceeded : 1;
	unsigned usingProxy : 1;
	unsigned usingTool : 1;
	unsigned withinRange : 1;
} SCD_Struct_AW51;

typedef struct {
	unsigned bytesPerSec : 1;
	unsigned timestamp : 1;
	unsigned errorCode : 1;
	unsigned legacy : 1;
	unsigned sender : 1;
	unsigned success : 1;
} SCD_Struct_AW52;

