/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, March 1, 2023 at 11:00:17 PM Israel Standard Time
* Operating System: Version 11.2.3 (Build 20D91)
* Image Source: /usr/libexec/sharingd
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <sharingd/SDAirDropHandler.h>

@class NSString;

@interface sharingd.SDAirDropHandlerIPA : SDAirDropHandler

@property (readonly,nonatomic) char canHandleTransfer; 
@property (readonly,nonatomic) NSString * suitableContentsDescription; 
@property (readonly,nonatomic) NSString * singleItemActionTitle; 
-(long long)transferTypes;
-(id)initWithTransfer:(id)arg1 bundleIdentifier:(id)arg2 ;
-(char)canHandleTransfer;
-(NSString *)suitableContentsDescription;
-(NSString *)singleItemActionTitle;
@end

